//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MyRSA, NSLock, NSMutableDictionary;

@interface ADBHelper : NSObject
{
    NSLock *poolLock;
    NSMutableDictionary *_socketPool;
    MyRSA *_rsa;
}

+ (id)sharedHelper;
- (void).cxx_destruct;
- (void)closeAdbConnection:(id)arg1;
- (void)closeSocket:(id)arg1;
- (id)connect:(id)arg1;
- (id)fileDataAddingDataHeader:(id)arg1;
- (id)getAdbPublicKeyPayload;
- (id)init;
- (_Bool)installApk:(id)arg1 deviceIp:(id)arg2;
@property(retain, nonatomic) MyRSA *rsa; // @synthesize rsa=_rsa;
- (void)sendData:(id)arg1 socket:(id)arg2;
- (_Bool)sendFile:(id)arg1 toPath:(id)arg2 deviceIp:(id)arg3;
@property(retain, nonatomic) NSMutableDictionary *socketPool; // @synthesize socketPool=_socketPool;
- (id)shellCommand:(id)arg1 deviceIp:(id)arg2;

@end

