//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSMutableCopying.h"

@class NSString, WKRouterModel;

@interface AppCenterBoutiqueItemDataModel : NSObject <NSMutableCopying>
{
    NSString *_name;
    NSString *_desc;
    WKRouterModel *_router;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSString *desc; // @synthesize desc=_desc;
- (id)mutableCopyWithZone:(struct _NSZone *)arg1;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(retain, nonatomic) WKRouterModel *router; // @synthesize router=_router;

@end

