//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class AppCenterBoutiqueItemListModel, UIButton, UIImageView;

@interface AppCenterNewUserGuideCollectionViewCell : UICollectionViewCell
{
    UIImageView *_appIconImageView;
    UIButton *_appNameButtton;
    AppCenterBoutiqueItemListModel *_itemListModel;
}

- (void).cxx_destruct;
@property(nonatomic) __weak UIImageView *appIconImageView; // @synthesize appIconImageView=_appIconImageView;
@property(nonatomic) __weak UIButton *appNameButtton; // @synthesize appNameButtton=_appNameButtton;
- (void)awakeFromNib;
- (void)cellSetDataSource:(id)arg1;
@property(retain, nonatomic) AppCenterBoutiqueItemListModel *itemListModel; // @synthesize itemListModel=_itemListModel;
- (void)refreshViewWith:(_Bool)arg1;

@end

