//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AppMonitorMeasureValueSet, NSLock, NSMutableArray;

@interface AppMonitorEntity : NSObject
{
    _Bool _isDetail;
    long long _count;
    long long _noise;
    AppMonitorMeasureValueSet *_measureValues;
    NSMutableArray *_measureValuesArray;
    NSLock *_lock;
}

- (void).cxx_destruct;
@property(nonatomic) long long count; // @synthesize count=_count;
- (void)incrCount;
- (void)incrNoise;
- (id)init;
@property _Bool isDetail; // @synthesize isDetail=_isDetail;
@property(retain, nonatomic) NSLock *lock; // @synthesize lock=_lock;
@property(retain, nonatomic) AppMonitorMeasureValueSet *measureValues; // @synthesize measureValues=_measureValues;
@property(retain, nonatomic) NSMutableArray *measureValuesArray; // @synthesize measureValuesArray=_measureValuesArray;
- (void)merge:(id)arg1 metric:(id)arg2;
@property(nonatomic) long long noise; // @synthesize noise=_noise;

@end

