//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AppMonitorBase.h"

@interface AppMonitorAlarm : AppMonitorBase
{
}

+ (void)commitFailWithPage:(id)arg1 monitorPoint:(id)arg2 errorCode:(id)arg3 errorMsg:(id)arg4;
+ (void)commitFailWithPage:(id)arg1 monitorPoint:(id)arg2 errorCode:(id)arg3 errorMsg:(id)arg4 arg:(id)arg5;
+ (void)commitSuccessWithPage:(id)arg1 monitorPoint:(id)arg2;
+ (void)commitSuccessWithPage:(id)arg1 monitorPoint:(id)arg2 arg:(id)arg3;
+ (void)flushAllLog;
+ (void)setWriteLogInterval:(long long)arg1;
+ (long long)writeLogInterval;

@end

