//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSLock, NSMutableOrderedSet;

@interface AppMonitorMetricSet : NSObject
{
    NSMutableOrderedSet *_metrics;
    NSLock *_lock;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (void)addMetric:(id)arg1;
- (id)init;
@property(retain, nonatomic) NSLock *lock; // @synthesize lock=_lock;
- (id)metricForModule:(id)arg1 monitorPoint:(id)arg2;
@property(retain, nonatomic) NSMutableOrderedSet *metrics; // @synthesize metrics=_metrics;

@end

