//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSLock, NSString;

@interface AppMonitorConfigSystem : NSObject
{
    _Bool _useUT;
    _Bool _discardAp;
    int _cacheFlushInterval;
    int _cacheTriggeCount;
    int _uploadInterval;
    int _orangeUploadInterval;
    NSDictionary *_systemDict;
    NSDictionary *_defaultSystemDict;
    NSString *_hotpatchVersion;
    NSLock *_lock;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
@property(nonatomic) int cacheFlushInterval; // @synthesize cacheFlushInterval=_cacheFlushInterval;
@property(nonatomic) int cacheTriggeCount; // @synthesize cacheTriggeCount=_cacheTriggeCount;
- (int)cacheTriggeCount:(id)arg1;
- (void)dealloc;
@property(retain, nonatomic) NSDictionary *defaultSystemDict; // @synthesize defaultSystemDict=_defaultSystemDict;
@property _Bool discardAp; // @synthesize discardAp=_discardAp;
@property(copy, nonatomic) NSString *hotpatchVersion; // @synthesize hotpatchVersion=_hotpatchVersion;
- (id)init;
@property(retain, nonatomic) NSLock *lock; // @synthesize lock=_lock;
@property(nonatomic) int orangeUploadInterval; // @synthesize orangeUploadInterval=_orangeUploadInterval;
- (id)reflectHotpatchVersion;
- (id)restoreHotpatchVersion;
- (void)setDicContent:(id)arg1;
@property(retain, nonatomic) NSDictionary *systemDict; // @synthesize systemDict=_systemDict;
@property(nonatomic) int uploadInterval; // @synthesize uploadInterval=_uploadInterval;
@property(nonatomic) _Bool useUT; // @synthesize useUT=_useUT;
- (void)tbHotpatchDownloadRunPatch:(id)arg1;

@end

