//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AppMonitorSwitchDataConverter.h"

@class NSLock, NSMutableDictionary;

@interface AppMonitorCannotSwitchDataConverter : AppMonitorSwitchDataConverter
{
    NSLock *lock;
    NSMutableDictionary *_countDict;
    NSMutableDictionary *_alarmDict;
    NSMutableDictionary *_statDict;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableDictionary *alarmDict; // @synthesize alarmDict=_alarmDict;
@property(retain, nonatomic) NSMutableDictionary *countDict; // @synthesize countDict=_countDict;
- (id)getSwitchResultForCountAndAlarm:(id)arg1 monitorPoint:(id)arg2 Type:(id)arg3 Arg:(id)arg4 RandomNum:(int)arg5;
- (id)getSwitchResultForStat:(id)arg1 monitorPoint:(id)arg2 Dimension:(id)arg3 RandomNum:(int)arg4;
- (id)init;
- (_Bool)isEmptyofDic;
- (void)removeDicContent;
- (void)setDicContent:(id)arg1;
@property(retain, nonatomic) NSMutableDictionary *statDict; // @synthesize statDict=_statDict;

@end

