//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface AppMonitor : NSObject
{
}

+ (void)disableSample;
+ (_Bool)isInit;
+ (_Bool)isTurnOnRealTimeDebug;
+ (id)realTimeDebugId;
+ (id)realTimeDebugUploadUrl;
+ (void)setSampling:(id)arg1;
+ (void)setSamplingConfigWithJson:(id)arg1;
+ (id)sharedInstance;
+ (void)turnOffAppMonitorRealtimeDebug;
+ (void)turnOnAppMonitorRealtimeDebug:(id)arg1;
- (void)appDidEnterBackground;
- (id)init;

@end

