//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class UIImageView, UILabel, UIView;

@interface AppViewCell : UICollectionViewCell
{
    float ava_h;
    float ava_w;
    UIImageView *_iconView;
    UILabel *_nameLabel;
    UIImageView *_typeView;
    UIView *_shadowView;
    CDUnknownBlockType _appInfoCellDidClicked;
    id _dataModel;
}

- (void).cxx_destruct;
@property(copy, nonatomic) CDUnknownBlockType appInfoCellDidClicked; // @synthesize appInfoCellDidClicked=_appInfoCellDidClicked;
- (void)buildThumbnailIcon:(id)arg1;
@property(retain, nonatomic) id dataModel; // @synthesize dataModel=_dataModel;
- (void)handleLongPress:(id)arg1;
@property(retain, nonatomic) UIImageView *iconView; // @synthesize iconView=_iconView;
- (void)initView;
- (id)initWithFrame:(struct CGRect)arg1;
@property(retain, nonatomic) UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
- (void)prepareForReuse;
- (void)setRowData:(id)arg1;
@property(retain, nonatomic) UIView *shadowView; // @synthesize shadowView=_shadowView;
@property(retain, nonatomic) UIImageView *typeView; // @synthesize typeView=_typeView;

@end

