//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface BaiduMobAdCrashReporter : NSObject
{
    _Bool _die;
    NSString *_appsid;
}

+ (id)instance;
- (void)_kill;
- (void)_setUncaughtExceptionHandler;
@property(copy, nonatomic) NSString *appsid; // @synthesize appsid=_appsid;
- (void)dealloc;
@property(nonatomic) _Bool die; // @synthesize die=_die;
- (id)init;
- (void)report:(id)arg1;

@end

