//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IBaiduMobAdRenderEventDelegate.h"

@class BaiduMobAdRenderer, BaiduMobAdRequestInfo, BaiduMobAdResponse, BaiduMobAdURLConnection, NSArray, NSDate, NSDictionary, NSNumber, NSString, UIView;

@interface BaiduMobAdSlotTemplate : NSObject <IBaiduMobAdRenderEventDelegate>
{
    int _currentPlayingAdIndex;
    _Bool _isLoadCalled;
    _Bool _isStartCalled;
    _Bool _enableLocation;
    _Bool _autoplayEnabled;
    _Bool _isReady;
    int _userGender;
    BaiduMobAdRenderer *_currentAdRenderer;
    CDUnknownBlockType _willDisplayAdBlock;
    CDUnknownBlockType _failedDisplayAdBlock;
    CDUnknownBlockType _didAdImpressedBlock;
    CDUnknownBlockType _didAdClickedBlock;
    CDUnknownBlockType _didDismissLandingPageBlock;
    CDUnknownBlockType _didAdPlayEndBlock;
    CDUnknownBlockType _interstitialSuccessToLoadAdBlock;
    CDUnknownBlockType _interstitialFailToLoadAdBlock;
    CDUnknownBlockType _interstitialDidDismissScreenBlock;
    CDUnknownBlockType _readyDisplayAdBlock;
    CDUnknownBlockType _startDisplayAdBlock;
    CDUnknownBlockType _finishDisplayAdBlock;
    BaiduMobAdRequestInfo *_requestInfo;
    BaiduMobAdResponse *_adResponse;
    BaiduMobAdURLConnection *_urlConnection;
    UIView *_renderBaseView;
    NSString *_publisherId;
    NSString *_adId;
    NSString *_channelId;
    NSArray *_keywords;
    NSDate *_userBirthday;
    NSString *_userCity;
    NSString *_userPostalCode;
    NSString *_userWork;
    long long _userEducation;
    long long _userSalary;
    NSArray *_userHobbies;
    NSDictionary *_userOtherAttributes;
    NSNumber *_w;
    NSNumber *_h;
    NSNumber *_lw;
    NSNumber *_lh;
    double _startTimeStamp;
}

- (void)_startNextAd;
@property(copy, nonatomic) NSString *adId; // @synthesize adId=_adId;
@property(retain, nonatomic) BaiduMobAdResponse *adResponse; // @synthesize adResponse=_adResponse;
- (id)allAdInstances;
@property(nonatomic) _Bool autoplayEnabled; // @synthesize autoplayEnabled=_autoplayEnabled;
- (id)buildRequestInfo:(id)arg1;
@property(copy, nonatomic) NSString *channelId; // @synthesize channelId=_channelId;
- (void)close;
@property(retain, nonatomic) BaiduMobAdRenderer *currentAdRenderer; // @synthesize currentAdRenderer=_currentAdRenderer;
- (void)dealloc;
@property(copy, nonatomic) CDUnknownBlockType didAdClickedBlock; // @synthesize didAdClickedBlock=_didAdClickedBlock;
@property(copy, nonatomic) CDUnknownBlockType didAdImpressedBlock; // @synthesize didAdImpressedBlock=_didAdImpressedBlock;
@property(copy, nonatomic) CDUnknownBlockType didAdPlayEndBlock; // @synthesize didAdPlayEndBlock=_didAdPlayEndBlock;
@property(copy, nonatomic) CDUnknownBlockType didDismissLandingPageBlock; // @synthesize didDismissLandingPageBlock=_didDismissLandingPageBlock;
@property(nonatomic) _Bool enableLocation; // @synthesize enableLocation=_enableLocation;
- (void)errorCallback:(id)arg1 withRequestAndResponseDic:(id)arg2;
@property(copy, nonatomic) CDUnknownBlockType failedDisplayAdBlock; // @synthesize failedDisplayAdBlock=_failedDisplayAdBlock;
@property(copy, nonatomic) CDUnknownBlockType finishDisplayAdBlock; // @synthesize finishDisplayAdBlock=_finishDisplayAdBlock;
@property(retain, nonatomic) NSNumber *h; // @synthesize h=_h;
- (id)init;
@property(copy, nonatomic) CDUnknownBlockType interstitialDidDismissScreenBlock; // @synthesize interstitialDidDismissScreenBlock=_interstitialDidDismissScreenBlock;
@property(copy, nonatomic) CDUnknownBlockType interstitialFailToLoadAdBlock; // @synthesize interstitialFailToLoadAdBlock=_interstitialFailToLoadAdBlock;
@property(copy, nonatomic) CDUnknownBlockType interstitialSuccessToLoadAdBlock; // @synthesize interstitialSuccessToLoadAdBlock=_interstitialSuccessToLoadAdBlock;
@property(nonatomic) _Bool isReady; // @synthesize isReady=_isReady;
@property(retain, nonatomic) NSArray *keywords; // @synthesize keywords=_keywords;
@property(retain, nonatomic) NSNumber *lh; // @synthesize lh=_lh;
- (void)load;
@property(retain, nonatomic) NSNumber *lw; // @synthesize lw=_lw;
- (void)onAdClicked:(id)arg1 withAdInstance:(id)arg2 withDictionary:(id)arg3;
- (void)onAdDismissLp;
- (void)onAdError:(int)arg1;
- (void)onAdError:(id)arg1 withAdInstance:(id)arg2 reason:(int)arg3 withDictionary:(id)arg4;
- (void)onAdFinish:(id)arg1 withAdInstance:(id)arg2 withDictionary:(id)arg3;
- (void)onAdImpression:(id)arg1 withAdInstance:(id)arg2 withDictionary:(id)arg3;
- (void)onAdLoaded:(id)arg1 withAdInstance:(id)arg2 withDictionary:(id)arg3;
- (void)onAdStart:(id)arg1 withAdInstance:(id)arg2 withDictionary:(id)arg3;
- (void)onAdSwitch:(id)arg1 withAdInstance:(id)arg2 withDictionary:(id)arg3;
- (void)onInterstitialAdDismissScreen:(id)arg1 withAdInstance:(id)arg2 withDictionary:(id)arg3;
- (void)onInterstitialAdFailtoLoadAd:(id)arg1 withAdInstance:(id)arg2 reason:(int)arg3 withDictionary:(id)arg4;
- (void)onInterstitialAdLoaded:(id)arg1 withAdInstance:(id)arg2 withDictionary:(id)arg3;
- (void)pause;
- (double)playheadTime;
@property(copy, nonatomic) NSString *publisherId; // @synthesize publisherId=_publisherId;
@property(copy, nonatomic) CDUnknownBlockType readyDisplayAdBlock; // @synthesize readyDisplayAdBlock=_readyDisplayAdBlock;
- (void)reload;
@property(nonatomic) UIView *renderBaseView; // @synthesize renderBaseView=_renderBaseView;
- (void)request;
@property(retain, nonatomic) BaiduMobAdRequestInfo *requestInfo; // @synthesize requestInfo=_requestInfo;
- (void)resume;
@property(copy, nonatomic) CDUnknownBlockType startDisplayAdBlock; // @synthesize startDisplayAdBlock=_startDisplayAdBlock;
@property(nonatomic) double startTimeStamp; // @synthesize startTimeStamp=_startTimeStamp;
@property(retain, nonatomic) BaiduMobAdURLConnection *urlConnection; // @synthesize urlConnection=_urlConnection;
@property(retain, nonatomic) NSDate *userBirthday; // @synthesize userBirthday=_userBirthday;
@property(copy, nonatomic) NSString *userCity; // @synthesize userCity=_userCity;
@property(nonatomic) long long userEducation; // @synthesize userEducation=_userEducation;
@property(nonatomic) int userGender; // @synthesize userGender=_userGender;
@property(retain, nonatomic) NSArray *userHobbies; // @synthesize userHobbies=_userHobbies;
@property(retain, nonatomic) NSDictionary *userOtherAttributes; // @synthesize userOtherAttributes=_userOtherAttributes;
@property(copy, nonatomic) NSString *userPostalCode; // @synthesize userPostalCode=_userPostalCode;
@property(nonatomic) long long userSalary; // @synthesize userSalary=_userSalary;
@property(copy, nonatomic) NSString *userWork; // @synthesize userWork=_userWork;
- (void)setVisibility:(_Bool)arg1;
@property(retain, nonatomic) NSNumber *w; // @synthesize w=_w;
@property(copy, nonatomic) CDUnknownBlockType willDisplayAdBlock; // @synthesize willDisplayAdBlock=_willDisplayAdBlock;
- (_Bool)shouldCreateRender;
- (id)slotBase;
- (id)slotId;
- (void)start;
- (void)stop;
- (void)successCallback:(id)arg1 withRequestAndResponseDic:(id)arg2;
- (double)totalDuration;
- (id)type;
- (_Bool)visible;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

