//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class BaiduMobAdSplashSlot, NSString, UIView;

@interface BaiduMobAdSplash : NSObject
{
    _Bool _canSplashClick;
    _Bool _splashUsesWindow;
    id <BaiduMobAdSplashDelegate> _delegate;
    NSString *_AdUnitTag;
    BaiduMobAdSplashSlot *_splashSlot;
    UIView *_splashContainerView;
}

@property(copy, nonatomic) NSString *AdUnitTag; // @synthesize AdUnitTag=_AdUnitTag;
@property(readonly, nonatomic) NSString *Version;
- (void)buildCallbackBlock;
- (id)buildSlotInfo:(id)arg1;
@property(nonatomic) _Bool canSplashClick; // @synthesize canSplashClick=_canSplashClick;
- (id)channelId;
- (void)dealloc;
@property(nonatomic) id <BaiduMobAdSplashDelegate> delegate; // @synthesize delegate=_delegate;
- (_Bool)enableLocation;
- (id)init;
- (id)keywords;
- (void)loadAndDisplayUsingContainerView:(id)arg1;
- (void)loadAndDisplayUsingKeyWindow:(id)arg1;
- (id)publisherId;
@property(retain, nonatomic) UIView *splashContainerView; // @synthesize splashContainerView=_splashContainerView;
@property(retain, nonatomic) BaiduMobAdSplashSlot *splashSlot; // @synthesize splashSlot=_splashSlot;
@property(nonatomic) _Bool splashUsesWindow; // @synthesize splashUsesWindow=_splashUsesWindow;
- (id)userBirthday;
- (id)userCity;
- (long long)userEducation;
- (int)userGender;
- (id)userHobbies;
- (id)userOtherAttributes;
- (id)userPostalCode;
- (long long)userSalary;
- (id)userWork;

@end

