//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSURLConnectionDataDelegate.h"
#import "NSURLConnectionDelegate.h"

@class NSMutableData, NSMutableURLRequest, NSString, NSURLConnection, NSURLResponse;

@interface BaiduMobAdURLConnection : NSObject <NSURLConnectionDelegate, NSURLConnectionDataDelegate>
{
    id _target;
    SEL _callback;
    SEL _errback;
    NSMutableData *_receivedData;
    _Bool _requestCompleted;
    _Bool _callbackWithDetail;
    NSMutableURLRequest *_currentRequest;
    NSURLResponse *_currentResponse;
    NSURLConnection *_connection;
}

+ (id)connect:(id)arg1 timeoutInterval:(double)arg2 target:(id)arg3 callback:(SEL)arg4 errback:(SEL)arg5;
+ (id)connect:(id)arg1 timeoutInterval:(double)arg2 target:(id)arg3 callback:(SEL)arg4 errback:(SEL)arg5 callbackWithDetail:(_Bool)arg6;
+ (id)httpGetUrl:(id)arg1 timeoutInterval:(double)arg2 target:(id)arg3 callback:(SEL)arg4 errback:(SEL)arg5;
+ (id)httpGetUrl:(id)arg1 timeoutInterval:(double)arg2 target:(id)arg3 callback:(SEL)arg4 errback:(SEL)arg5 callbackWithDetail:(_Bool)arg6;
+ (void)httpGetUrls:(id)arg1 timeoutInterval:(double)arg2;
+ (void)pseudeoHttpGetUrl:(id)arg1 target:(id)arg2 callback:(SEL)arg3;
- (id)_connect:(id)arg1 timeoutInterval:(double)arg2 target:(id)arg3 callback:(SEL)arg4 errback:(SEL)arg5 callbackWithDetail:(_Bool)arg6;
- (void)_onTimeout:(id)arg1;
@property(nonatomic) SEL callback; // @synthesize callback=_callback;
- (void)cancel;
@property(retain, nonatomic) NSURLConnection *connection; // @synthesize connection=_connection;
- (_Bool)connection:(id)arg1 canAuthenticateAgainstProtectionSpace:(id)arg2;
- (void)connection:(id)arg1 didFailWithError:(id)arg2;
- (void)connection:(id)arg1 didReceiveAuthenticationChallenge:(id)arg2;
- (void)connection:(id)arg1 didReceiveData:(id)arg2;
- (void)connection:(id)arg1 didReceiveResponse:(id)arg2;
- (id)connection:(id)arg1 willCacheResponse:(id)arg2;
- (id)connection:(id)arg1 willSendRequest:(id)arg2 redirectResponse:(id)arg3;
- (void)connectionDidFinishLoading:(id)arg1;
@property(retain, nonatomic) NSMutableURLRequest *currentRequest; // @synthesize currentRequest=_currentRequest;
@property(retain, nonatomic) NSURLResponse *currentResponse; // @synthesize currentResponse=_currentResponse;
- (void)dealloc;
@property(nonatomic) SEL errback; // @synthesize errback=_errback;
- (id)init;
@property(retain, nonatomic) NSMutableData *receivedData; // @synthesize receivedData=_receivedData;
- (void)reportUrlError:(id)arg1;
@property(nonatomic) _Bool requestCompleted; // @synthesize requestCompleted=_requestCompleted;
@property(nonatomic) id target; // @synthesize target=_target;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

