//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UIAlertViewDelegate.h"

@class NSString, UIWebView;

@interface BaiduMobAdNotifyManager : NSObject <UIAlertViewDelegate>
{
    UIWebView *_webView;
    NSString *_confirmJsToken;
}

+ (id)getManagerForWebView:(id)arg1;
+ (void)removeManagerForWebView:(id)arg1;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)confirm:(id)arg1 options:(id)arg2;
@property(retain, nonatomic) NSString *confirmJsToken; // @synthesize confirmJsToken=_confirmJsToken;
- (void)dealloc;
- (id)initWithWebView:(id)arg1;
- (void)showDialogWithMessage:(id)arg1 title:(id)arg2 buttons:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

