//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class BaiduMobAdInterstitialSlot, BaiduMobAdInterstitialView, NSString;

@interface BaiduMobAdInterstitial : NSObject
{
    _Bool _isReady;
    int _interstitialType;
    id <BaiduMobAdInterstitialDelegate> _delegate;
    NSString *_AdUnitTag;
    NSString *_Version;
    BaiduMobAdInterstitialSlot *_interstitialSlot;
    BaiduMobAdInterstitialView *_interstitialView;
}

@property(copy, nonatomic) NSString *AdUnitTag; // @synthesize AdUnitTag=_AdUnitTag;
@property(readonly, nonatomic) NSString *Version; // @synthesize Version=_Version;
- (void)buildCallbackBlock;
- (id)buildSlotInfo:(id)arg1;
- (id)channelId;
- (void)dealloc;
@property(nonatomic) id <BaiduMobAdInterstitialDelegate> delegate; // @synthesize delegate=_delegate;
- (_Bool)enableLocation;
- (id)init;
@property(retain, nonatomic) BaiduMobAdInterstitialSlot *interstitialSlot; // @synthesize interstitialSlot=_interstitialSlot;
@property(nonatomic) int interstitialType; // @synthesize interstitialType=_interstitialType;
@property(retain, nonatomic) BaiduMobAdInterstitialView *interstitialView; // @synthesize interstitialView=_interstitialView;
@property(nonatomic) _Bool isReady; // @synthesize isReady=_isReady;
- (id)keywords;
- (void)load;
- (void)loadAd:(_Bool)arg1;
- (void)loadAndDisplayUsingKeyWindow:(id)arg1;
- (void)loadUsingSize:(struct CGRect)arg1;
- (void)presentFromRootViewController:(id)arg1;
- (void)presentFromView:(id)arg1;
- (id)publisherId;
- (_Bool)sizeValid:(struct CGRect)arg1;
- (id)userBirthday;
- (id)userCity;
- (long long)userEducation;
- (int)userGender;
- (id)userHobbies;
- (id)userOtherAttributes;
- (id)userPostalCode;
- (long long)userSalary;
- (id)userWork;

@end

