//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class BaiduMobAdPrerollSlot, NSString, UIView;

@interface BaiduMobAdPreroll : NSObject
{
    _Bool _supportTimeLabel;
    _Bool _supportActImage;
    id <BaiduMobAdPrerollDelegate> _delegate;
    NSString *_publisherId;
    NSString *_adId;
    UIView *_renderBaseView;
    BaiduMobAdPrerollSlot *_slot;
}

@property(copy, nonatomic) NSString *adId; // @synthesize adId=_adId;
- (void)buildCallbackBlock;
- (id)buildSlotInfo:(id)arg1;
- (id)channelId;
- (void)dealloc;
@property(nonatomic) id <BaiduMobAdPrerollDelegate> delegate; // @synthesize delegate=_delegate;
- (_Bool)enableLocation;
- (id)init;
- (id)keywords;
@property(copy, nonatomic) NSString *publisherId; // @synthesize publisherId=_publisherId;
@property(retain, nonatomic) UIView *renderBaseView; // @synthesize renderBaseView=_renderBaseView;
- (void)request;
@property(retain, nonatomic) BaiduMobAdPrerollSlot *slot; // @synthesize slot=_slot;
@property _Bool supportActImage; // @synthesize supportActImage=_supportActImage;
@property _Bool supportTimeLabel; // @synthesize supportTimeLabel=_supportTimeLabel;
- (id)userBirthday;
- (id)userCity;
- (long long)userEducation;
- (int)userGender;
- (id)userHobbies;
- (id)userOtherAttributes;
- (id)userPostalCode;
- (long long)userSalary;
- (id)userWork;

@end

