//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "XNonLinearAdSlot.h"

@interface BaiduMobAdInterstitialSlot : XNonLinearAdSlot
{
    _Bool _interstitialPreLoad;
    _Bool _didShowInterstitialAd;
    int _interstitialType;
    long long _initOrientation;
    long long _showOrientation;
}

- (id)buildFixedResponse;
- (void)dealloc;
@property(nonatomic) _Bool didShowInterstitialAd; // @synthesize didShowInterstitialAd=_didShowInterstitialAd;
- (id)init;
@property(nonatomic) long long initOrientation; // @synthesize initOrientation=_initOrientation;
@property(nonatomic) _Bool interstitialPreLoad; // @synthesize interstitialPreLoad=_interstitialPreLoad;
@property(nonatomic) int interstitialType; // @synthesize interstitialType=_interstitialType;
- (_Bool)isInconsistentOrientation;
- (void)load;
- (void)onAdImpression:(id)arg1 withAdInstance:(id)arg2 withDictionary:(id)arg3;
- (void)reload;
- (void)request;
@property(nonatomic) long long showOrientation; // @synthesize showOrientation=_showOrientation;
- (void)start;
- (void)statusBarFrameOrOrientationChanged:(id)arg1;
- (void)successCallback:(id)arg1 withRequestAndResponseDic:(id)arg2;
- (id)type;

@end

