//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaiduMobAdRenderer.h"

#import "BaiduMobAdActionComposerDelegate.h"
#import "UIWebViewDelegate.h"

@class BaiduMobAdMraidBridge, BaiduMobAdRendererHelper, BaiduMobAdURLConnection, NSString, UILabel, UIView, UIWebView;

@interface BaiduMobAdHTMLRenderer : BaiduMobAdRenderer <UIWebViewDelegate, BaiduMobAdActionComposerDelegate>
{
    BaiduMobAdRendererHelper *_rendererHelper;
    UIView *_rendererBaseView;
    _Bool _shouldAddTimer;
    int _timeCount;
    UIWebView *_adDefaultWebView;
    UIView *_adResizedTransparentView;
    UIWebView *_adExpandedWebViewForAnimation;
    UIWebView *_adExpandedWebView;
    UIView *_fullscreenView;
    BaiduMobAdURLConnection *_connection;
    BaiduMobAdMraidBridge *_bridge;
    UILabel *_timeLabel;
}

- (void)_onRequestAdFail:(id)arg1 requestInfo:(id)arg2;
- (void)_onRequestAdSuccess:(id)arg1 requestInfo:(id)arg2;
@property(retain, nonatomic) UIWebView *adDefaultWebView; // @synthesize adDefaultWebView=_adDefaultWebView;
@property(retain, nonatomic) UIWebView *adExpandedWebView; // @synthesize adExpandedWebView=_adExpandedWebView;
@property(retain, nonatomic) UIWebView *adExpandedWebViewForAnimation; // @synthesize adExpandedWebViewForAnimation=_adExpandedWebViewForAnimation;
@property(retain, nonatomic) UIView *adResizedTransparentView; // @synthesize adResizedTransparentView=_adResizedTransparentView;
- (void)addTimerInRenderWithSeconds:(int)arg1;
@property(retain, nonatomic) BaiduMobAdMraidBridge *bridge; // @synthesize bridge=_bridge;
- (_Bool)checkMsspNeedsIAP;
- (void)cleanupViews;
@property(retain, nonatomic) BaiduMobAdURLConnection *connection; // @synthesize connection=_connection;
- (void)dealloc;
- (void)didFinishWithResult:(id)arg1;
- (void)didVideoFinishWithResult:(id)arg1;
- (void)evalScript:(id)arg1;
@property(retain, nonatomic) UIView *fullscreenView; // @synthesize fullscreenView=_fullscreenView;
- (id)getTargetView:(id)arg1;
- (id)initWithAdRendererHelper:(id)arg1;
- (void)initializeMraidData;
- (void)lazyStartWithHTML:(id)arg1 inWebView:(id)arg2;
- (void)load;
- (long long)mraidFullscreenOrientation;
- (void)onAdPlayEnd;
- (void)pause;
- (void)playInterstitialVideo;
- (void)playVideoForInterstitial:(id)arg1;
- (void)playVideoForVideoSdk:(id)arg1;
- (double)playheadTime;
- (id)preparePropertyString;
- (void)prepareViews;
- (void)prepareWebView:(id)arg1;
- (void)processClick:(id)arg1;
- (void)reload;
- (void)resizeRendererBaseView;
- (void)resume;
- (void)setIAPBuy:(_Bool)arg1;
@property(nonatomic) _Bool shouldAddTimer; // @synthesize shouldAddTimer=_shouldAddTimer;
@property(nonatomic) int timeCount; // @synthesize timeCount=_timeCount;
@property(retain, nonatomic) UILabel *timeLabel; // @synthesize timeLabel=_timeLabel;
- (void)setVisibility:(_Bool)arg1;
- (void)start;
- (void)stop;
- (void)timeAnimation;
- (void)webView:(id)arg1 didFailLoadWithError:(id)arg2;
- (_Bool)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(long long)arg3;
- (void)webViewDidFinishLoad:(id)arg1;
- (void)webViewDidStartLoad:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

