//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaiduMobAdWebRequestInfo.h"

@interface BaiduMobAdBannerRequestInfo : BaiduMobAdWebRequestInfo
{
}

- (int)adType;
- (id)addFetForInterstitialVideo;
- (_Bool)preLoad;
- (id)prodProp;

@end

