//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaiduMobAdRenderer.h"

#import "BaiduMobAdActionComposerDelegate.h"
#import "UIAlertViewDelegate.h"

@class AVPlayer, AVPlayerLayer, BaiduMobAdActionComposer, BaiduMobAdInstance, BaiduMobAdMraidBridge, NSString, NSTimer, NSURL, UIActivityIndicatorView, UIButton, UIImageView, UILabel, UITapGestureRecognizer, UIView;

@interface BaiduMobAdVideoRenderer : BaiduMobAdRenderer <BaiduMobAdActionComposerDelegate, UIAlertViewDelegate>
{
    _Bool _supportTimeLabel;
    _Bool _supportActImage;
    _Bool _supportPause;
    _Bool _isOriginStatusBarHidden;
    _Bool _shouldShowEndCard;
    _Bool _isAppActive;
    _Bool _isFullScreen;
    _Bool _isFirstTimePlay;
    _Bool _metaLoaded;
    int _remainTimeValue;
    BaiduMobAdMraidBridge *_bridge;
    UIView *_videoBaseView;
    UIButton *_btnLP;
    UIActivityIndicatorView *_indicatorView;
    UILabel *_timecountLabel;
    NSString *_endcardUrlString;
    UIImageView *_endcardview;
    UIButton *_btnEndCardClose;
    UITapGestureRecognizer *_endCardTapGesture;
    NSTimer *_countTimer;
    BaiduMobAdActionComposer *_composer;
    double _backgroundTimeStamp;
    BaiduMobAdInstance *_associatedObject;
    UIView *_displayView;
    NSURL *_url;
    AVPlayer *_player;
    AVPlayerLayer *_playerLayer;
    UITapGestureRecognizer *_tapGesture;
    UIView *_originSuperView;
    struct CGRect _originFrame;
}

- (void).cxx_destruct;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (id)apoUrl:(id)arg1;
@property(retain, nonatomic) BaiduMobAdInstance *associatedObject; // @synthesize associatedObject=_associatedObject;
@property double backgroundTimeStamp; // @synthesize backgroundTimeStamp=_backgroundTimeStamp;
@property(nonatomic) __weak BaiduMobAdMraidBridge *bridge; // @synthesize bridge=_bridge;
@property(retain, nonatomic) UIButton *btnEndCardClose; // @synthesize btnEndCardClose=_btnEndCardClose;
@property(retain, nonatomic) UIButton *btnLP; // @synthesize btnLP=_btnLP;
- (void)checkVisible;
- (void)cleanUp;
- (void)completePlayback;
@property(retain, nonatomic) BaiduMobAdActionComposer *composer; // @synthesize composer=_composer;
@property(retain, nonatomic) NSTimer *countTimer; // @synthesize countTimer=_countTimer;
- (double)currentTime;
- (void)dealloc;
- (void)didEnterBackground;
- (void)didFinishWithResult:(id)arg1;
- (void)displayVideo;
@property(retain, nonatomic) UIView *displayView; // @synthesize displayView=_displayView;
- (void)doAction:(id)arg1;
- (double)duration;
@property(retain, nonatomic) UITapGestureRecognizer *endCardTapGesture; // @synthesize endCardTapGesture=_endCardTapGesture;
@property(retain, nonatomic) NSString *endcardUrlString; // @synthesize endcardUrlString=_endcardUrlString;
@property(retain, nonatomic) UIImageView *endcardview; // @synthesize endcardview=_endcardview;
- (void)handleTapGesture:(id)arg1;
- (id)imageResoureForName:(id)arg1;
@property(retain, nonatomic) UIActivityIndicatorView *indicatorView; // @synthesize indicatorView=_indicatorView;
- (id)initWithAdRendererHelper:(id)arg1;
@property _Bool isAppActive; // @synthesize isAppActive=_isAppActive;
@property(nonatomic) _Bool isFirstTimePlay; // @synthesize isFirstTimePlay=_isFirstTimePlay;
@property(nonatomic) _Bool isFullScreen; // @synthesize isFullScreen=_isFullScreen;
@property _Bool isOriginStatusBarHidden; // @synthesize isOriginStatusBarHidden=_isOriginStatusBarHidden;
- (void)layoutDisplayArea;
@property(nonatomic) _Bool metaLoaded; // @synthesize metaLoaded=_metaLoaded;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)onAdShowCallback;
- (void)onPlaybackLikelyToKeepUpChange;
- (void)onPlayerItemDidReachEnd:(id)arg1;
- (void)onPlayerItemFail:(id)arg1;
- (void)onPlayerRateChange;
- (void)onVideoPlayEndCallBack:(id)arg1;
@property(nonatomic) struct CGRect originFrame; // @synthesize originFrame=_originFrame;
@property(nonatomic) UIView *originSuperView; // @synthesize originSuperView=_originSuperView;
- (void)pause;
- (void)playClick:(id)arg1;
- (void)playbackFail:(id)arg1;
@property(retain, nonatomic) AVPlayer *player; // @synthesize player=_player;
@property(retain, nonatomic) AVPlayerLayer *playerLayer; // @synthesize playerLayer=_playerLayer;
- (void)prepareAction;
@property(nonatomic) int remainTimeValue; // @synthesize remainTimeValue=_remainTimeValue;
- (void)resizePlaybackFrame:(struct CGRect)arg1;
- (void)sendUnRetryUrl:(id)arg1;
- (void)sendVideoEvent:(int)arg1 currentTime:(double)arg2;
- (void)setRemainTime;
@property _Bool shouldShowEndCard; // @synthesize shouldShowEndCard=_shouldShowEndCard;
@property _Bool supportActImage; // @synthesize supportActImage=_supportActImage;
@property(nonatomic) _Bool supportPause; // @synthesize supportPause=_supportPause;
@property _Bool supportTimeLabel; // @synthesize supportTimeLabel=_supportTimeLabel;
@property(retain, nonatomic) UITapGestureRecognizer *tapGesture; // @synthesize tapGesture=_tapGesture;
@property(retain, nonatomic) UILabel *timecountLabel; // @synthesize timecountLabel=_timecountLabel;
@property(retain, nonatomic) NSURL *url; // @synthesize url=_url;
@property(retain, nonatomic) UIView *videoBaseView; // @synthesize videoBaseView=_videoBaseView;
- (void)setupUI;
- (void)start;
- (void)startPlayback;
- (void)stop;
- (void)videoAdClick;
- (void)willEnterForeground;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

