//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCacheDelegate.h"

@class BaiduMobAdDiskLRUCache, NSCache, NSString;

@interface BaiduMobAdNativeCache : NSObject <NSCacheDelegate>
{
    int _cacheMethod;
    NSCache *_memoryCache;
    BaiduMobAdDiskLRUCache *_diskCache;
}

+ (id)sharedCache;
- (void).cxx_destruct;
- (void)cache:(id)arg1 willEvictObject:(id)arg2;
@property(nonatomic) int cacheMethod; // @synthesize cacheMethod=_cacheMethod;
- (_Bool)cachedDataExistsForKey:(id)arg1;
- (_Bool)cachedDataExistsForKey:(id)arg1 withCacheMethod:(int)arg2;
- (void)dealloc;
- (void)didReceiveMemoryWarning:(id)arg1;
@property(retain, nonatomic) BaiduMobAdDiskLRUCache *diskCache; // @synthesize diskCache=_diskCache;
- (id)init;
@property(retain, nonatomic) NSCache *memoryCache; // @synthesize memoryCache=_memoryCache;
- (void)removeAllDataFromCache;
- (void)removeAllDataFromDisk;
- (void)removeAllDataFromMemory;
- (id)retrieveDataForKey:(id)arg1;
- (id)retrieveDataForKey:(id)arg1 withCacheMethod:(int)arg2;
- (void)setInMemoryCacheEnabled:(_Bool)arg1;
- (void)storeData:(id)arg1 forKey:(id)arg2;
- (void)storeData:(id)arg1 forKey:(id)arg2 withCacheMethod:(int)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

