//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "XLinearAdSlot.h"

@interface BaiduMobAdPrerollSlot : XLinearAdSlot
{
    _Bool _isNative;
    _Bool _supportTimeLabel;
    _Bool _supportActImage;
}

- (id)init;
@property(nonatomic) _Bool isNative; // @synthesize isNative=_isNative;
- (void)onAdLoaded:(id)arg1 withAdInstance:(id)arg2 withDictionary:(id)arg3;
- (void)request;
@property _Bool supportActImage; // @synthesize supportActImage=_supportActImage;
@property _Bool supportTimeLabel; // @synthesize supportTimeLabel=_supportTimeLabel;
- (_Bool)shouldCreateRender;
- (void)start;
- (void)successCallback:(id)arg1 withRequestAndResponseDic:(id)arg2;
- (id)type;

@end

