//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UIViewControllerAnimatedTransitioning.h"

@class NSString;

@interface BaiduMobAdLPTransitionAnimation : NSObject <UIViewControllerAnimatedTransitioning>
{
    _Bool _isPresentAnimation;
    _Bool _isCancel;
    _Bool _isFinish;
    id <UIViewControllerContextTransitioning> _transitionContext;
}

- (void)animateTransition:(id)arg1;
- (void)cancel;
@property _Bool isCancel; // @synthesize isCancel=_isCancel;
@property _Bool isFinish; // @synthesize isFinish=_isFinish;
@property _Bool isPresentAnimation; // @synthesize isPresentAnimation=_isPresentAnimation;
@property(nonatomic) id <UIViewControllerContextTransitioning> transitionContext; // @synthesize transitionContext=_transitionContext;
- (double)transitionDuration:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

