//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface BaiduMobAdDiskLRUCacheFile : NSObject
{
    NSString *_filePath;
    double _lastModTimestamp;
    unsigned long long _fileSize;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSString *filePath; // @synthesize filePath=_filePath;
@property(nonatomic) unsigned long long fileSize; // @synthesize fileSize=_fileSize;
@property(nonatomic) double lastModTimestamp; // @synthesize lastModTimestamp=_lastModTimestamp;

@end

