//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSDictionary, NSMutableArray, NSString;

@interface BaiduMobAdResponse : NSObject
{
    NSArray *_allAdInstances;
    int _n;
    NSDictionary *_adData;
    NSString *_errorCode;
    NSString *_errorMessage;
    NSMutableArray *_adInstanceArray;
}

@property(retain, nonatomic) NSDictionary *adData; // @synthesize adData=_adData;
@property(retain, nonatomic) NSMutableArray *adInstanceArray; // @synthesize adInstanceArray=_adInstanceArray;
- (id)allAdInstances;
- (id)currentAdInstance;
- (void)dealloc;
@property(copy, nonatomic) NSString *errorCode; // @synthesize errorCode=_errorCode;
@property(copy, nonatomic) NSString *errorMessage; // @synthesize errorMessage=_errorMessage;
- (id)initWithDictonary:(id)arg1;
- (id)initWithNSData:(id)arg1;
@property int n; // @synthesize n=_n;

@end

