//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CLLocationManagerDelegate.h"

@class CLLocation, CLLocationManager, NSString;

@interface BaiduMobAdLocationHelper : NSObject <CLLocationManagerDelegate>
{
    _Bool _locationUpdating;
    CLLocationManager *_locationManager;
    double _timestamp;
    CDUnknownBlockType _locationBlock;
    CLLocation *_mapSdkLocation;
    struct CLLocationCoordinate2D _currentLocation;
}

+ (id)sharedInstance;
- (void)cleanUpLocationManager;
@property(nonatomic) struct CLLocationCoordinate2D currentLocation; // @synthesize currentLocation=_currentLocation;
- (void)dealloc;
- (id)init;
- (_Bool)isAuthorizationStatusEnable;
- (_Bool)isLocationPlistSet;
@property(copy, nonatomic) CDUnknownBlockType locationBlock; // @synthesize locationBlock=_locationBlock;
@property(retain, nonatomic) CLLocationManager *locationManager; // @synthesize locationManager=_locationManager;
- (void)locationManager:(id)arg1 didFailWithError:(id)arg2;
- (void)locationManager:(id)arg1 didUpdateLocations:(id)arg2;
- (void)locationManager:(id)arg1 didUpdateToLocation:(id)arg2 fromLocation:(id)arg3;
@property(nonatomic) _Bool locationUpdating; // @synthesize locationUpdating=_locationUpdating;
@property(retain, nonatomic) CLLocation *mapSdkLocation; // @synthesize mapSdkLocation=_mapSdkLocation;
@property(nonatomic) double timestamp; // @synthesize timestamp=_timestamp;
- (void)updateLocationOnce:(CDUnknownBlockType)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

