//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface BCEAppEntity : NSObject
{
    _Bool _showNewFlag;
    int _appType;
    int _devFlag;
    int _unreadCount;
    long long _appId;
    NSString *_code;
    NSString *_name;
    NSString *_icon;
    long long _msgBoxId;
    NSString *_introduce;
    NSString *_appkey;
    NSString *_appsecret;
    NSString *_appVersion;
    NSString *_callbackUrl;
    NSString *_downloadUrl;
    long long _categoryId;
    NSString *_localIcon;
}

- (void).cxx_destruct;
@property(nonatomic) long long appId; // @synthesize appId=_appId;
@property(nonatomic) int appType; // @synthesize appType=_appType;
@property(retain, nonatomic) NSString *appVersion; // @synthesize appVersion=_appVersion;
@property(retain, nonatomic) NSString *appkey; // @synthesize appkey=_appkey;
@property(retain, nonatomic) NSString *appsecret; // @synthesize appsecret=_appsecret;
@property(retain, nonatomic) NSString *callbackUrl; // @synthesize callbackUrl=_callbackUrl;
@property(nonatomic) long long categoryId; // @synthesize categoryId=_categoryId;
@property(retain, nonatomic) NSString *code; // @synthesize code=_code;
- (id)description;
@property(nonatomic) int devFlag; // @synthesize devFlag=_devFlag;
@property(retain, nonatomic) NSString *downloadUrl; // @synthesize downloadUrl=_downloadUrl;
@property(retain, nonatomic) NSString *icon; // @synthesize icon=_icon;
- (id)initWithId:(long long)arg1;
@property(retain, nonatomic) NSString *introduce; // @synthesize introduce=_introduce;
@property(retain, nonatomic) NSString *localIcon; // @synthesize localIcon=_localIcon;
@property(nonatomic) long long msgBoxId; // @synthesize msgBoxId=_msgBoxId;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
@property(nonatomic) _Bool showNewFlag; // @synthesize showNewFlag=_showNewFlag;
@property(nonatomic) int unreadCount; // @synthesize unreadCount=_unreadCount;

@end

