//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BCCall.h"

@class BCPermission, NSString;

@interface BCHandler : BCCall
{
    _Bool _shouldOpenUI;
    id <WQHandlerCallback> callback;
    CDUnknownBlockType syncCallbackBlock;
    CDUnknownBlockType asyncCallbackBlock;
    NSString *handlerEvent;
    BCPermission *_eventPermission;
    NSString *_bindAppKey;
}

- (void).cxx_destruct;
@property(copy, nonatomic) CDUnknownBlockType asyncCallbackBlock; // @synthesize asyncCallbackBlock;
@property(retain, nonatomic) NSString *bindAppKey; // @synthesize bindAppKey=_bindAppKey;
@property(retain, nonatomic) id <WQHandlerCallback> callback; // @synthesize callback;
- (_Bool)enable;
@property(retain, nonatomic) BCPermission *eventPermission; // @synthesize eventPermission=_eventPermission;
@property(retain, nonatomic) NSString *handlerEvent; // @synthesize handlerEvent;
- (id)initWithEvent:(id)arg1;
- (id)initWithEvent:(id)arg1 shouldOpenUI:(_Bool)arg2;
- (id)initWithEvent:(id)arg1 withAsyncBlock:(CDUnknownBlockType)arg2 needRunInMainThread:(_Bool)arg3 shouldOpenUI:(_Bool)arg4;
- (id)initWithEvent:(id)arg1 withCallback:(id)arg2 withContext:(id)arg3 needRunInMainThread:(_Bool)arg4 shouldOpenUI:(_Bool)arg5;
- (id)initWithEvent:(id)arg1 withSyncBlock:(CDUnknownBlockType)arg2 needRunInMainThread:(_Bool)arg3 shouldOpenUI:(_Bool)arg4;
- (void)onAddedToConnector;
- (void)onRemovedFromConnector;
@property(nonatomic) _Bool shouldOpenUI; // @synthesize shouldOpenUI=_shouldOpenUI;
@property(copy, nonatomic) CDUnknownBlockType syncCallbackBlock; // @synthesize syncCallbackBlock;

@end

