//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class BCConnector, NSString;

@interface BCHybridConnector : NSObject
{
    BCConnector *_attachedWQConnector;
    NSString *_appKey;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *appKey; // @synthesize appKey=_appKey;
@property(retain, nonatomic) BCConnector *attachedWQConnector; // @synthesize attachedWQConnector=_attachedWQConnector;
- (id)getRegisteredEvents;
- (_Bool)hasRegesteredEvent:(id)arg1;
- (id)initWithAppKey:(id)arg1;
- (void)mapEventFrom:(id)arg1 toEvent:(id)arg2;
- (void)registerBridgeEvent:(id)arg1 handler:(CDUnknownBlockType)arg2;
- (void)registerBridgeEvent:(id)arg1 target:(id)arg2 selector:(SEL)arg3;
- (void)registerBridgeModule:(id)arg1 andMethod:(id)arg2 handler:(CDUnknownBlockType)arg3;
- (void)registerEventHandler:(id)arg1;
- (int)sendEventRequest:(id)arg1 params:(id)arg2 callBackBlock:(CDUnknownBlockType)arg3;
- (int)sendEventRequest:(id)arg1 params:(id)arg2 callBackBlock:(CDUnknownBlockType)arg3 extraParams:(id)arg4;
- (void)unregisterAll;
- (void)unregisterBridgeEvent:(id)arg1;
- (void)unregisterBridgeModule:(id)arg1 andMethod:(id)arg2;

@end

