//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface BLYBinaryImage : NSObject
{
    unsigned long long _baseAddress;
    unsigned long long _endAddress;
    NSString *_name;
    NSString *_arch;
    NSString *_uuid;
    NSString *_path;
}

+ (id)formatAddress:(unsigned long long)arg1;
- (void).cxx_destruct;
@property(copy, nonatomic) NSString *arch; // @synthesize arch=_arch;
@property(nonatomic) unsigned long long baseAddress; // @synthesize baseAddress=_baseAddress;
- (id)debugDescription;
@property(nonatomic) unsigned long long endAddress; // @synthesize endAddress=_endAddress;
- (id)init;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(copy, nonatomic) NSString *path; // @synthesize path=_path;
@property(copy, nonatomic) NSString *uuid; // @synthesize uuid=_uuid;

@end

