//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSDictionary, NSError, NSException, NSString;

@interface BLYCrashUserException : NSObject
{
    int _backtraceLength;
    unsigned long long _category;
    NSString *_name;
    NSError *_userError;
    NSException *_userException;
    NSString *_reason;
    NSDictionary *_extraInfo;
    NSArray *_userCallStack;
    double _occurTime;
    unsigned long long *_backtrace;
}

+ (id)exceptionWithCategory:(unsigned long long)arg1 name:(id)arg2;
+ (id)exceptionWithError:(id)arg1;
+ (id)exceptionWithException:(id)arg1;
+ (_Bool)isSupportedCategory:(unsigned long long)arg1;
- (void).cxx_destruct;
@property(nonatomic) unsigned long long *backtrace; // @synthesize backtrace=_backtrace;
@property(nonatomic) int backtraceLength; // @synthesize backtraceLength=_backtraceLength;
- (id)callStack;
@property(nonatomic) unsigned long long category; // @synthesize category=_category;
- (id)exceptionName;
- (id)exceptionReason;
@property(copy, nonatomic) NSDictionary *extraInfo; // @synthesize extraInfo=_extraInfo;
- (id)init;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(nonatomic) double occurTime; // @synthesize occurTime=_occurTime;
@property(copy, nonatomic) NSString *reason; // @synthesize reason=_reason;
@property(copy, nonatomic) NSArray *userCallStack; // @synthesize userCallStack=_userCallStack;
@property(retain, nonatomic) NSError *userError; // @synthesize userError=_userError;
@property(retain, nonatomic) NSException *userException; // @synthesize userException=_userException;

@end

