//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BLYAbstractModule.h"

@class NSMutableArray, NSString;

@interface BLYExtensionExceptionManager : BLYAbstractModule
{
    _Bool _uploading;
    _Bool _wcsessionExist;
    _Bool _appGroupAvailable;
    NSString *_appGroupIdentifier;
    NSMutableArray *_uploadingFiles;
}

+ (id)constructSelector;
+ (id)sharedManager;
- (void).cxx_destruct;
- (id)appGroupDirectoryPath;
@property(copy, nonatomic) NSString *appGroupIdentifier; // @synthesize appGroupIdentifier=_appGroupIdentifier;
- (void)buglyMartian_wcSessionDelegate;
- (void)checkAndUpload;
- (_Bool)disableModule;
- (id)documentDirectoryPath;
- (_Bool)enableModule;
- (id)exceptionFromFileURL:(id)arg1;
- (id)exceptionsFromOldPath;
@property(nonatomic, getter=isAppGroupAvailable) _Bool appGroupAvailable; // @synthesize appGroupAvailable=_appGroupAvailable;
@property(nonatomic, getter=isUploading) _Bool uploading; // @synthesize uploading=_uploading;
- (id)packageDataWithException:(id)arg1;
- (id)packetExtraValues:(id)arg1;
- (void)saveException:(id)arg1;
@property(retain, nonatomic) NSMutableArray *uploadingFiles; // @synthesize uploadingFiles=_uploadingFiles;
@property(nonatomic) _Bool wcsessionExist; // @synthesize wcsessionExist=_wcsessionExist;

@end

