//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class BLYJCEPair, NSString;

@interface BLYJCEPropertyInfo : NSObject
{
    _Bool _dynamic;
    _Bool _weak;
    _Bool _required;
    _Bool _isJCE;
    long long _tag;
    SEL _getter;
    SEL _setter;
    NSString *_name;
    NSString *_type;
    BLYJCEPair *_ext;
    long long _memoryManagementPolicy;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool dynamic; // @synthesize dynamic=_dynamic;
@property(retain, nonatomic) BLYJCEPair *ext; // @synthesize ext=_ext;
@property(nonatomic) SEL getter; // @synthesize getter=_getter;
@property(nonatomic) _Bool isJCE; // @synthesize isJCE=_isJCE;
@property(nonatomic) long long memoryManagementPolicy; // @synthesize memoryManagementPolicy=_memoryManagementPolicy;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
@property(nonatomic) _Bool required; // @synthesize required=_required;
@property(nonatomic) SEL setter; // @synthesize setter=_setter;
@property(nonatomic) long long tag; // @synthesize tag=_tag;
@property(retain, nonatomic) NSString *type; // @synthesize type=_type;
@property(nonatomic) _Bool weak; // @synthesize weak=_weak;

@end

