//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BLYAbstractModule.h"

@class NSObject<OS_dispatch_semaphore>, NSString, NSThread;

@interface BLYMainRunloopMonitorManager : BLYAbstractModule
{
    struct __CFRunLoopObserver *_runloopObserver;
    NSThread *_monitorThread;
    _Bool _monitorThreadCanceled;
    double _duration;
    NSString *_runloopTimeoutEvent;
    NSObject<OS_dispatch_semaphore> *_semaphore;
    unsigned long long _activity;
    double _runloopTimeoutThreshold;
    long long _runloopCPURatioThreshold;
    long long _runloopReportCountForWiFi;
    long long _runloopReportTrafficForWiFi;
    long long _runloopReportCountForCellular;
    long long _runloopReportTrafficForCellular;
}

+ (id)constructSelector;
+ (id)sharedManager;
- (void).cxx_destruct;
- (void)addRunloopObserver;
- (void)dataManagerNotifyValue:(id)arg1 changedForKey:(id)arg2;
- (_Bool)disableModule;
- (void)dumpMainThreadCallStackSymbols;
- (_Bool)enableModule;
- (id)init;
- (void)monitorThreadRun;
- (id)packageModelFromCrashReport:(id)arg1;
- (void)removeRunloopObserver;
@property(nonatomic) long long runloopCPURatioThreshold; // @synthesize runloopCPURatioThreshold=_runloopCPURatioThreshold;
@property(nonatomic) long long runloopReportCountForCellular; // @synthesize runloopReportCountForCellular=_runloopReportCountForCellular;
@property(nonatomic) long long runloopReportCountForWiFi; // @synthesize runloopReportCountForWiFi=_runloopReportCountForWiFi;
@property(nonatomic) long long runloopReportTrafficForCellular; // @synthesize runloopReportTrafficForCellular=_runloopReportTrafficForCellular;
@property(nonatomic) long long runloopReportTrafficForWiFi; // @synthesize runloopReportTrafficForWiFi=_runloopReportTrafficForWiFi;
@property(nonatomic) double runloopTimeoutThreshold; // @synthesize runloopTimeoutThreshold=_runloopTimeoutThreshold;
- (void)sendPendingData;
- (void)start;
- (void)startMonitorThread;
- (void)stop;
- (void)stopMonitorThread;
- (id)strategyGetterSelector;
- (id)strategyValueMapKey;
- (void)updateStrategy:(id)arg1;

@end

