//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface BLYStackFrame : NSObject
{
    unsigned char _index;
    NSString *_module;
    unsigned long long _loadAddress;
    unsigned long long _baseAddress;
    unsigned long long _offset;
    NSString *_symbol;
}

- (void).cxx_destruct;
@property(nonatomic) unsigned long long baseAddress; // @synthesize baseAddress=_baseAddress;
- (id)debugDescription;
- (id)frame;
- (id)frameSymbol;
@property(nonatomic) unsigned char index; // @synthesize index=_index;
- (id)init;
@property(nonatomic) unsigned long long loadAddress; // @synthesize loadAddress=_loadAddress;
@property(copy, nonatomic) NSString *module; // @synthesize module=_module;
@property(nonatomic) unsigned long long offset; // @synthesize offset=_offset;
@property(copy, nonatomic) NSString *symbol; // @synthesize symbol=_symbol;

@end

