//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BLYRequestPacket.h"

@class BLYUniAttribute;

@interface BLYUniPacket : BLYRequestPacket
{
    BLYUniAttribute *_attributes;
}

+ (id)packet;
- (void).cxx_destruct;
- (void)__pack:(id)arg1;
- (void)__unpack:(id)arg1;
@property(readonly, nonatomic) BLYUniAttribute *attributes; // @synthesize attributes=_attributes;
- (id)description;
- (id)getObjectAttr:(id)arg1 forClass:(Class)arg2;
- (id)init;
- (id)objectKeyWithName:(id)arg1;
- (void)putDataAttr:(id)arg1 value:(id)arg2;
- (void)putObjectAttr:(id)arg1 type:(id)arg2 value:(id)arg3;
- (void)putObjectAttr:(id)arg1 value:(id)arg2;

@end

