//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface DecideTVHelper : NSObject
{
}

+ (void)decideConnectTvSuccess:(CDUnknownBlockType)arg1 failture:(CDUnknownBlockType)arg2;
+ (void)gotoInstallHelperVc;
+ (void)installTVSuccess:(CDUnknownBlockType)arg1 failture:(CDUnknownBlockType)arg2;
+ (_Bool)isConnectedDevice;
+ (_Bool)isConnectedServerOnline;
+ (_Bool)isWiFiConneted;
+ (void)showContectTVAltert;
+ (void)showInstallTVAlert;
+ (void)showNoWiFiAlert;

@end

