//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSError, NSString;

@interface FastServerSocket : NSObject
{
    long long timeout;
    int sockfd;
    NSString *port;
    NSError *lastError;
}

- (void).cxx_destruct;
- (id)accept;
- (_Bool)close;
- (void)dealloc;
- (id)initWithFileDescriptor:(int)arg1;
- (id)initWithPort:(id)arg1;
@property(readonly, nonatomic) NSError *lastError; // @synthesize lastError;
- (_Bool)listen;
@property(readonly, nonatomic) NSString *port; // @synthesize port;
- (_Bool)setTimeout:(long long)arg1;
@property(readonly, nonatomic) int sockfd; // @synthesize sockfd;
- (long long)timeout;

@end

