//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSError, NSString;

@interface FastSocket : NSObject
{
    void *_buffer;
    long long _size;
    long long _timeout;
    int _segmentSize;
    int _sockfd;
    NSString *_host;
    NSString *_port;
    NSError *_lastError;
}

- (void).cxx_destruct;
- (void)buffer:(void **)arg1 size:(long long *)arg2;
- (_Bool)close;
- (_Bool)connect;
- (_Bool)connect:(long long)arg1;
- (void)dealloc;
@property(readonly, nonatomic) NSString *host; // @synthesize host=_host;
- (id)initWithFileDescriptor:(int)arg1;
- (id)initWithHost:(id)arg1 andPort:(id)arg2;
- (_Bool)isConnected;
@property(readonly, nonatomic) NSError *lastError; // @synthesize lastError=_lastError;
@property(readonly, nonatomic) NSString *port; // @synthesize port=_port;
- (long long)receiveBytes:(void *)arg1 count:(long long)arg2;
- (long long)receiveBytes:(void *)arg1 limit:(long long)arg2;
- (long long)receiveFile:(id)arg1 length:(long long)arg2;
- (long long)receiveFile:(id)arg1 length:(long long)arg2 md5:(id *)arg3;
- (int)segmentSize;
- (long long)sendBytes:(const void *)arg1 count:(long long)arg2;
- (long long)sendFile:(id)arg1;
- (_Bool)setSegmentSize:(int)arg1;
- (_Bool)setTimeout:(long long)arg1;
@property(readonly, nonatomic) int sockfd; // @synthesize sockfd=_sockfd;
- (long long)timeout;

@end

