//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class NSArray, UIView;

@interface FindFontTableViewCell : UITableViewCell
{
    UIView *_wrapView;
    NSArray *_models;
}

- (void).cxx_destruct;
- (void)awakeFromNib;
- (void)btnClicked:(id)arg1;
- (void)cellSetDataSource:(id)arg1;
@property(retain, nonatomic) NSArray *models; // @synthesize models=_models;
- (void)setButtonTheme:(id)arg1 withIndex:(long long)arg2;
@property(nonatomic) __weak UIView *wrapView; // @synthesize wrapView=_wrapView;

@end

