//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class WKBannerBottomGuideView;

@interface FindChoiceTableViewCell : UITableViewCell
{
    WKBannerBottomGuideView *_choiceView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) WKBannerBottomGuideView *choiceView; // @synthesize choiceView=_choiceView;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)setDataModel:(id)arg1;

@end

