//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface GDTAntiSpamParam : NSObject
{
    _Bool _closeBtnDisplayed;
    int _adType;
    long long _playBeginTime;
    double _aa;
    double _ab;
    double _ba;
    double _bb;
    long long _g;
    long long _ec;
    long long _sc;
    NSString *_d;
    NSString *_f;
    NSString *_sz;
    long long _p;
    NSString *_x;
    long long _preClickTime;
    long long _postClickTime;
}

- (void).cxx_destruct;
@property(nonatomic) double aa; // @synthesize aa=_aa;
@property(nonatomic) double ab; // @synthesize ab=_ab;
@property(nonatomic) int adType; // @synthesize adType=_adType;
@property(nonatomic) double ba; // @synthesize ba=_ba;
@property(nonatomic) double bb; // @synthesize bb=_bb;
@property(nonatomic) _Bool closeBtnDisplayed; // @synthesize closeBtnDisplayed=_closeBtnDisplayed;
@property(copy, nonatomic) NSString *d; // @synthesize d=_d;
@property(nonatomic) long long ec; // @synthesize ec=_ec;
@property(copy, nonatomic) NSString *f; // @synthesize f=_f;
@property(nonatomic) long long g; // @synthesize g=_g;
- (id)initWithAdType:(int)arg1;
@property(nonatomic) long long p; // @synthesize p=_p;
@property(nonatomic) long long playBeginTime; // @synthesize playBeginTime=_playBeginTime;
@property(nonatomic) long long postClickTime; // @synthesize postClickTime=_postClickTime;
@property(nonatomic) long long preClickTime; // @synthesize preClickTime=_preClickTime;
@property(nonatomic) long long sc; // @synthesize sc=_sc;
- (void)setPreClickTime:(long long)arg1 postClickTime:(long long)arg2;
@property(copy, nonatomic) NSString *sz; // @synthesize sz=_sz;
@property(copy, nonatomic) NSString *x; // @synthesize x=_x;
- (id)splashAntiParam;

@end

