//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "GDTClickControllerDelegate.h"
#import "UIWebViewDelegate.h"

@class GDTAdWebView, GDTClickController, GDTHandlerManager, NSString, UIViewController;

@interface GDTAdWebViewClient : NSObject <GDTClickControllerDelegate, UIWebViewDelegate>
{
    GDTHandlerManager *_handlerManager;
    UIViewController *_rootViewController;
    GDTClickController *_clickController;
    GDTAdWebView *_gdtAdWebView;
}

- (void).cxx_destruct;
- (void)bindHandlers:(id)arg1;
@property(retain, nonatomic) GDTClickController *clickController; // @synthesize clickController=_clickController;
@property(nonatomic) __weak GDTAdWebView *gdtAdWebView; // @synthesize gdtAdWebView=_gdtAdWebView;
@property(retain, nonatomic) GDTHandlerManager *handlerManager; // @synthesize handlerManager=_handlerManager;
- (id)init;
- (void)leaveApp;
- (void)modalDidDismiss;
- (void)modalDidPresent;
- (void)modalWillDismiss;
- (void)modalWillPresent;
@property(nonatomic) __weak UIViewController *rootViewController; // @synthesize rootViewController=_rootViewController;
- (void)webView:(id)arg1 didFailLoadWithError:(id)arg2;
- (_Bool)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(long long)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

