//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSString;

@interface GDTClickParam : NSObject
{
    _Bool _innerBrowser;
    _Bool _adxIframeGDTjs;
    int _clickActionType;
    int _productType;
    NSString *_clickUrl;
    NSString *_itunesId;
    NSString *_campaignId;
    NSString *_providerId;
    NSString *_appname;
    NSDictionary *_deepLinkParams;
    NSString *_aid;
    NSString *_adReqUrl;
    NSString *_traceId;
    NSString *_landpageUrl;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSString *adReqUrl; // @synthesize adReqUrl=_adReqUrl;
@property(nonatomic) _Bool adxIframeGDTjs; // @synthesize adxIframeGDTjs=_adxIframeGDTjs;
@property(copy, nonatomic) NSString *aid; // @synthesize aid=_aid;
@property(copy, nonatomic) NSString *appname; // @synthesize appname=_appname;
@property(copy, nonatomic) NSString *campaignId; // @synthesize campaignId=_campaignId;
@property(nonatomic) int clickActionType; // @synthesize clickActionType=_clickActionType;
@property(copy, nonatomic) NSString *clickUrl; // @synthesize clickUrl=_clickUrl;
@property(retain, nonatomic) NSDictionary *deepLinkParams; // @synthesize deepLinkParams=_deepLinkParams;
@property(nonatomic) _Bool innerBrowser; // @synthesize innerBrowser=_innerBrowser;
@property(copy, nonatomic) NSString *itunesId; // @synthesize itunesId=_itunesId;
@property(copy, nonatomic) NSString *landpageUrl; // @synthesize landpageUrl=_landpageUrl;
@property(nonatomic) int productType; // @synthesize productType=_productType;
@property(copy, nonatomic) NSString *providerId; // @synthesize providerId=_providerId;
@property(copy, nonatomic) NSString *traceId; // @synthesize traceId=_traceId;

@end

