//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "GDTAppLinkServiceDelegate.h"
#import "GDTWebViewControllerDelegate.h"
#import "SFSafariViewControllerDelegate.h"
#import "UIAlertViewDelegate.h"

@class GDTAppLinkService, GDTClickParam, GDTStoreProductCurrentController, NSString, UIViewController;

@interface GDTClickController : NSObject <SFSafariViewControllerDelegate, UIAlertViewDelegate, GDTWebViewControllerDelegate, GDTAppLinkServiceDelegate>
{
    GDTAppLinkService *_appLinkService;
    GDTClickParam *_clickParam;
    id <GDTClickControllerDelegate> _stateListener;
    UIViewController *_currentViewController;
    GDTStoreProductCurrentController *_storeProductCurrentVC;
}

+ (_Bool)canOpenUrlScheme:(id)arg1;
+ (id)generateGDTUrlScheme:(id)arg1 clickId:(id)arg2 adId:(id)arg3;
- (void).cxx_destruct;
@property(nonatomic) __weak UIViewController *currentViewController; // @synthesize currentViewController=_currentViewController;
- (void)dealloc;
- (void)handleClick:(id)arg1;
- (void)handleDeepLink;
- (id)initWithCurrentViewController:(id)arg1;
- (void)innerSafariBrower:(id)arg1;
- (void)innerWebViewBrower:(id)arg1;
- (void)notifyListenerLeaveApp;
- (void)notifyListenerModalDidDismiss;
- (void)notifyListenerModalDidPresent;
- (void)notifyListenerModalWillDismiss;
- (void)notifyListenerModalWillPresent;
- (void)openInAppStore;
- (void)openInnerBrowserWithActtype:(int)arg1 url:(id)arg2;
- (void)openLandingPage;
- (_Bool)openUrlScheme:(id)arg1;
- (void)parseFailure:(id)arg1;
- (void)parseSuccessWithAppLinkHeader:(id)arg1;
- (void)popUpWebViewDidClosed;
- (void)popUpWebViewWillClosed;
- (void)reportEvokeSuccess:(id)arg1;
- (void)resignActive;
- (void)safariViewControllerDidFinish:(id)arg1;
@property(nonatomic) __weak id <GDTClickControllerDelegate> stateListener; // @synthesize stateListener=_stateListener;
@property(retain, nonatomic) GDTStoreProductCurrentController *storeProductCurrentVC; // @synthesize storeProductCurrentVC=_storeProductCurrentVC;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

