//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GDTAdMgr, GDTAdWebView, GDTAdWebViewClient, GDTBaseInterstitialDialog, GDTInterstitialLifeCycleStateListener, GDTInterstitialService, NSString;

@interface GDTMobInterstitial : NSObject
{
    GDTAdWebView *_webView;
    GDTAdWebViewClient *_webViewClient;
    NSString *_placementId;
    NSString *_appkey;
    GDTInterstitialLifeCycleStateListener *_listener;
    GDTAdMgr *_adMgr;
    GDTInterstitialService *_interstitialService;
    GDTBaseInterstitialDialog *_dialog;
    _Bool _fullScreen;
    _Bool _isReady;
    _Bool _isGpsOn;
    id <GDTMobInterstitialDelegate> _delegate;
}

- (void).cxx_destruct;
- (_Bool)checkParams;
- (void)cleanWebView;
- (void)dealloc;
@property(nonatomic) __weak id <GDTMobInterstitialDelegate> delegate; // @synthesize delegate=_delegate;
- (id)getHandlers;
- (void)initAdMgr;
- (void)initWebView;
- (void)initWebViewClient;
- (id)initWithAppkey:(id)arg1 placementId:(id)arg2;
- (void)interstitialDidPresent;
- (void)interstitialWillPresent;
@property(nonatomic) _Bool isGpsOn; // @synthesize isGpsOn=_isGpsOn;
@property(nonatomic) _Bool isReady; // @synthesize isReady=_isReady;
- (void)loadAd;
- (void)presentFromRootViewController:(id)arg1;
- (void)setFullScreen:(id)arg1;
- (void)showError:(int)arg1;

@end

