//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSString;

@interface GDTNativeAdData : NSObject
{
    _Bool _isAppAd;
    _Bool _isExposured;
    int _productType;
    NSDictionary *_properties;
    NSString *_rl;
    NSString *_apUrl;
    NSString *_itunesId;
    NSString *_campaignId;
    NSString *_providerId;
    NSString *_urlScheme;
    NSString *_cl;
    NSString *_appname;
    NSString *_traceId;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *apUrl; // @synthesize apUrl=_apUrl;
@property(copy, nonatomic) NSString *appname; // @synthesize appname=_appname;
@property(retain, nonatomic) NSString *campaignId; // @synthesize campaignId=_campaignId;
@property(copy, nonatomic) NSString *cl; // @synthesize cl=_cl;
@property(nonatomic) _Bool isAppAd; // @synthesize isAppAd=_isAppAd;
- (_Bool)isAvailableAd;
@property(nonatomic) _Bool isExposured; // @synthesize isExposured=_isExposured;
@property(retain, nonatomic) NSString *itunesId; // @synthesize itunesId=_itunesId;
@property(nonatomic) int productType; // @synthesize productType=_productType;
@property(readonly, retain, nonatomic) NSDictionary *properties; // @synthesize properties=_properties;
@property(retain, nonatomic) NSString *providerId; // @synthesize providerId=_providerId;
@property(retain, nonatomic) NSString *rl; // @synthesize rl=_rl;
- (void)setProperties:(id)arg1;
@property(copy, nonatomic) NSString *traceId; // @synthesize traceId=_traceId;
@property(retain, nonatomic) NSString *urlScheme; // @synthesize urlScheme=_urlScheme;

@end

