//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface GDTRequestHelper : NSObject
{
}

+ (struct AdSize)adaptBannerSize:(int)arg1;
+ (struct AdSize)adaptIntersitialSize;
+ (struct AdSize)adaptSplashSize:(int)arg1;
+ (id)buildRequestDataFromJsRequest:(id)arg1;
+ (id)buildRequestDataFromNativeRequest:(id)arg1 adCount:(int)arg2 httpsSupport:(int)arg3;
+ (id)buildRequestDataFromSplashRequest:(id)arg1 adCount:(int)arg2 splashSizeType:(int)arg3 httpsSupport:(int)arg4;
+ (id)buildRequestExtData;
+ (id)buildTrackRequestData:(int)arg1 withValue:(int)arg2;
+ (id)convertAdStringFromType:(int)arg1;
+ (int)convertAdTypefromString:(id)arg1;
+ (id)generateExposureRequest:(id)arg1;
+ (id)generateLoadAdRequest:(id)arg1;
+ (id)generatePingRequest:(id)arg1;
+ (id)generateTrackRequest:(id)arg1;

@end

