//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SKStoreProductViewController.h"

@class NSString, NSTimer, UIActivityIndicatorView;

@interface GDTStoreProductController : SKStoreProductViewController
{
    _Bool _stop;
    UIActivityIndicatorView *_loadingView;
    int _loadingtime;
    NSTimer *_loadingTimer;
    _Bool _onceToken;
    _Bool _noLoadingTimer;
    double _generateTimeSecondsFrom1970;
    NSString *_appname;
    id <GDTStoreProductRequestDelegate> _storeProductDelegate;
    long long _state;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSString *appname; // @synthesize appname=_appname;
- (void)dealloc;
- (void)didReceiveMemoryWarning;
@property(nonatomic) double generateTimeSecondsFrom1970; // @synthesize generateTimeSecondsFrom1970=_generateTimeSecondsFrom1970;
- (void)hiddenStoreProductLoadingView:(_Bool)arg1;
- (id)init;
- (void)loadStoreProductRequest:(id)arg1;
- (void)loadStoreProductRequest:(id)arg1 campaignId:(id)arg2 providerId:(id)arg3;
- (void)loadStoreProductTimeout;
- (void)loadStoreProductWithParam:(id)arg1;
@property(nonatomic) _Bool noLoadingTimer; // @synthesize noLoadingTimer=_noLoadingTimer;
@property(nonatomic) _Bool onceToken; // @synthesize onceToken=_onceToken;
- (long long)preferredInterfaceOrientationForPresentation;
@property(nonatomic) long long state; // @synthesize state=_state;
@property(nonatomic) __weak id <GDTStoreProductRequestDelegate> storeProductDelegate; // @synthesize storeProductDelegate=_storeProductDelegate;
- (_Bool)shouldAutorotate;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;

@end

