//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GDTSplashSkipView.h"

#import "GDTGestureDelegate.h"

@class NSString, UILabel, UIView;

@interface GDTSplashDefaultSkipView : GDTSplashSkipView <GDTGestureDelegate>
{
    UILabel *_skipText;
    UILabel *_background;
    UILabel *_exposure;
    UIView *_split;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UILabel *background; // @synthesize background=_background;
@property(retain, nonatomic) UILabel *exposure; // @synthesize exposure=_exposure;
- (void)handleSingleTapGesture:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)setExposureTime:(int)arg1;
@property(retain, nonatomic) UILabel *skipText; // @synthesize skipText=_skipText;
@property(retain, nonatomic) UIView *split; // @synthesize split=_split;
- (void)startTick:(int)arg1;
- (void)stopTick;
- (void)tick;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

