//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class GDTSplashSkipView, GDTSplashView, UIView;

@interface GDTSplashViewController : UIViewController
{
    float _offset;
    GDTSplashView *_splashView;
    UIView *_iconView;
    GDTSplashSkipView *_skipView;
}

- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
@property(nonatomic) __weak UIView *iconView; // @synthesize iconView=_iconView;
@property(nonatomic) float offset; // @synthesize offset=_offset;
- (_Bool)prefersStatusBarHidden;
@property(nonatomic) __weak GDTSplashSkipView *skipView; // @synthesize skipView=_skipView;
@property(nonatomic) __weak GDTSplashView *splashView; // @synthesize splashView=_splashView;
- (_Bool)shouldAutorotate;
- (unsigned long long)supportedInterfaceOrientations;
- (void)viewDidLoad;

@end

