//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "GDTAdLifeEventListener.h"

@class GDTSplashAd, NSString;

@interface GDTSplashLifeCycleStateListener : NSObject <GDTAdLifeEventListener>
{
    id <GDTSplashAdDelegate> _delegate;
    GDTSplashAd *_splash;
}

- (void).cxx_destruct;
@property(nonatomic) __weak id <GDTSplashAdDelegate> delegate; // @synthesize delegate=_delegate;
- (void)handleAdLoadFailEvent:(id)arg1;
- (id)initWithSplash:(id)arg1;
- (void)onEvent:(id)arg1;
@property(nonatomic) __weak GDTSplashAd *splash; // @synthesize splash=_splash;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

