//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "GDTGestureDelegate.h"
#import "GDTSplashBottomViewDelegate.h"
#import "GDTSplashImageViewDelegate.h"

@class GDTSplashAdData, GDTSplashBottomView, GDTSplashImageView, GDTSplashViewClickData, NSString, UIImageView;

@interface GDTSplashView : UIView <GDTSplashBottomViewDelegate, GDTSplashImageViewDelegate, GDTGestureDelegate>
{
    GDTSplashAdData *_splashAdData;
    id <GDTSplashViewDelegate> _delegate;
    GDTSplashBottomView *_bottomView;
    GDTSplashImageView *_adImage;
    UIImageView *_tsaLogo;
    GDTSplashViewClickData *_clickData;
}

- (void).cxx_destruct;
@property(retain, nonatomic) GDTSplashImageView *adImage; // @synthesize adImage=_adImage;
@property(retain, nonatomic) GDTSplashBottomView *bottomView; // @synthesize bottomView=_bottomView;
@property(retain, nonatomic) GDTSplashViewClickData *clickData; // @synthesize clickData=_clickData;
- (void)clickSplashBottom:(id)arg1;
- (void)clickSplashImageView:(id)arg1;
@property(nonatomic) __weak id <GDTSplashViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)handleSingleTapGesture:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)setFrame:(struct CGRect)arg1;
@property(retain, nonatomic) GDTSplashAdData *splashAdData; // @synthesize splashAdData=_splashAdData;
@property(retain, nonatomic) UIImageView *tsaLogo; // @synthesize tsaLogo=_tsaLogo;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

