//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSString;

@interface GDTTrackMgr : NSObject
{
    NSMutableDictionary *_trackData;
    NSString *_clickId;
}

+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)instance;
+ (id)sharedGDTTrackMgr;
- (void).cxx_destruct;
- (void)appDidBecomeActive;
- (void)appWillResignActive;
@property(copy, nonatomic) NSString *clickId; // @synthesize clickId=_clickId;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (id)init;
- (_Bool)isActivated;
- (_Bool)isOneNewSession;
- (void)loadTrackData;
- (void)reportEventInfoToServer:(int)arg1 withValue:(int)arg2;
@property(retain, nonatomic) NSMutableDictionary *trackData; // @synthesize trackData=_trackData;
- (void)updateEventTime:(id)arg1;
- (void)updateTrackDataToFile;

@end

