//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData;

@interface GTMUMSocialStringEncoding : NSObject
{
    NSData *charMapData_;
    char *charMap_;
    int reverseCharMap_[128];
    int shift_;
    int mask_;
    _Bool doPad_;
    BOOL paddingChar_;
    int padLen_;
}

+ (id)binaryStringEncoding;
+ (id)crockfordBase32StringEncoding;
+ (id)hexStringEncoding;
+ (id)rfc4648Base32HexStringEncoding;
+ (id)rfc4648Base32StringEncoding;
+ (id)rfc4648Base64StringEncoding;
+ (id)rfc4648Base64WebsafeStringEncoding;
+ (id)stringEncodingWithString:(id)arg1;
- (void)addDecodeSynonyms:(id)arg1;
- (void)dealloc;
- (id)decode:(id)arg1;
- (id)description;
- (_Bool)doPad;
- (id)encode:(id)arg1;
- (id)encodeString:(id)arg1;
- (void)ignoreCharacters:(id)arg1;
- (id)initWithString:(id)arg1;
- (void)setDoPad:(_Bool)arg1;
- (void)setPaddingChar:(BOOL)arg1;
- (id)stringByDecoding:(id)arg1;

@end

