//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface HTTPAuthenticationRequest : NSObject
{
    _Bool isBasic;
    _Bool isDigest;
    NSString *base64Credentials;
    NSString *username;
    NSString *realm;
    NSString *nonce;
    NSString *uri;
    NSString *qop;
    NSString *nc;
    NSString *cnonce;
    NSString *response;
}

- (void).cxx_destruct;
- (id)base64Credentials;
- (id)cnonce;
- (id)initWithRequest:(id)arg1;
- (_Bool)isBasic;
- (_Bool)isDigest;
- (id)nc;
- (id)nonce;
- (id)nonquotedSubHeaderFieldValue:(id)arg1 fromHeaderFieldValue:(id)arg2;
- (id)qop;
- (id)quotedSubHeaderFieldValue:(id)arg1 fromHeaderFieldValue:(id)arg2;
- (id)realm;
- (id)response;
- (id)uri;
- (id)username;

@end

