//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GCDAsyncSocket, HTTPConfig, HTTPMessage, NSMutableArray, NSObject<HTTPResponse>, NSObject<OS_dispatch_queue>, NSString;

@interface HTTPConnection : NSObject
{
    NSObject<OS_dispatch_queue> *connectionQueue;
    GCDAsyncSocket *asyncSocket;
    HTTPConfig *config;
    _Bool started;
    HTTPMessage *request;
    unsigned int numHeaderLines;
    _Bool sentResponseHeaders;
    NSString *nonce;
    long long lastNC;
    NSObject<HTTPResponse> *httpResponse;
    NSMutableArray *ranges;
    NSMutableArray *ranges_headers;
    NSString *ranges_boundry;
    int rangeIndex;
    unsigned long long requestContentLength;
    unsigned long long requestContentLengthReceived;
    unsigned long long requestChunkSize;
    unsigned long long requestChunkSizeReceived;
    NSMutableArray *responseDataSizes;
}

+ (id)generateNonce;
+ (_Bool)hasRecentNonce:(id)arg1;
+ (void)initialize;
- (void).cxx_destruct;
- (void)addBasicAuthChallenge:(id)arg1;
- (void)addDigestAuthChallenge:(id)arg1;
- (id)chunkedTransferFooter;
- (id)chunkedTransferSizeLineForLength:(unsigned long long)arg1;
- (void)continueSendingMultiRangeResponseBody;
- (void)continueSendingSingleRangeResponseBody;
- (void)continueSendingStandardResponseBody;
- (id)dateAsString:(id)arg1;
- (void)dealloc;
- (void)die;
- (id)directoryIndexFileNames;
- (_Bool)expectsRequestBodyFromMethod:(id)arg1 atPath:(id)arg2;
- (id)filePathForURI:(id)arg1;
- (id)filePathForURI:(id)arg1 allowDirectory:(_Bool)arg2;
- (void)finishBody;
- (void)finishResponse;
- (void)handleAuthenticationFailed;
- (void)handleInvalidRequest:(id)arg1;
- (void)handleResourceNotFound;
- (void)handleUnknownMethod:(id)arg1;
- (void)handleVersionNotSupported:(id)arg1;
- (id)httpResponseForMethod:(id)arg1 URI:(id)arg2;
- (id)initWithAsyncSocket:(id)arg1 configuration:(id)arg2;
- (_Bool)isAuthenticated;
- (_Bool)isPasswordProtected:(id)arg1;
- (_Bool)isSecureServer;
- (id)newMultiRangeResponse:(unsigned long long)arg1;
- (id)newUniRangeResponse:(unsigned long long)arg1;
- (id)parseGetParams;
- (id)parseParams:(id)arg1;
- (_Bool)parseRangeRequest:(id)arg1 withContentLength:(unsigned long long)arg2;
- (id)passwordForUser:(id)arg1;
- (void)prepareForBodyWithSize:(unsigned long long)arg1;
- (id)preprocessErrorResponse:(id)arg1;
- (id)preprocessResponse:(id)arg1;
- (void)processBodyData:(id)arg1;
- (id)realm;
- (void)replyToHTTPRequest;
- (id)requestURI;
- (void)responseDidAbort:(id)arg1;
- (void)responseHasAvailableData:(id)arg1;
- (void)sendResponseHeadersAndBody;
- (_Bool)shouldDie;
- (void)socket:(id)arg1 didReadData:(id)arg2 withTag:(long long)arg3;
- (void)socket:(id)arg1 didWriteDataWithTag:(long long)arg2;
- (void)socketDidDisconnect:(id)arg1 withError:(id)arg2;
- (id)sslIdentityAndCertificates;
- (void)start;
- (void)startConnection;
- (void)startReadingRequest;
- (void)stop;
- (_Bool)supportsMethod:(id)arg1 atPath:(id)arg2;
- (_Bool)useDigestAccessAuthentication;
- (id)webSocketForURI:(id)arg1;
- (unsigned long long)writeQueueSize;

@end

