//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "HTTPResponse.h"

@interface HTTPErrorResponse : NSObject <HTTPResponse>
{
    long long _status;
}

- (unsigned long long)contentLength;
- (id)initWithErrorCode:(int)arg1;
- (_Bool)isDone;
- (unsigned long long)offset;
- (id)readDataOfLength:(unsigned long long)arg1;
- (void)setOffset:(unsigned long long)arg1;
- (long long)status;

@end

