//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

@interface IFlyParam : NSObject
{
    NSMutableDictionary *_params;
    id <IFlyParamMapProtocol> _delegate;
    id _owner;
}

- (void)dealloc;
@property(nonatomic) id <IFlyParamMapProtocol> delegate; // @synthesize delegate=_delegate;
- (id)init;
@property(nonatomic) id owner; // @synthesize owner=_owner;
@property(retain, nonatomic) NSMutableDictionary *params; // @synthesize params=_params;
- (void)removeAllParams;
- (void)setDefault;
- (_Bool)setValue:(id)arg1 forKey:(id)arg2;
- (void)setWithKeysAndValues:(id)arg1;
- (id)toString:(_Bool)arg1;
- (id)valueForKey:(id)arg1;

@end

