//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate, NSMutableDictionary;

@interface IFlySessionInfoLogger : NSObject
{
    NSDate *_appStart;
    NSMutableDictionary *_events;
}

+ (id)sharedLogger;
- (void)addLog:(id)arg1 forKey:(id)arg2;
@property(retain, nonatomic) NSDate *appStart; // @synthesize appStart=_appStart;
- (void)dealloc;
@property(retain, nonatomic) NSMutableDictionary *events; // @synthesize events=_events;
- (id)getCurrentTime;
- (id)init;
- (void)logAppCallerAppid:(id)arg1;
- (void)logAppStartTime;
- (void)logAppStopTime;
- (void)logFirstAudioTime;
- (void)logFirstResultPresentTime;
- (void)logFirstResultTime;
- (void)logLastAudioTime;
- (void)logLastResultPresentTime;
- (void)logLastResultTime;
- (void)logSessionBegin;
- (void)logStartAudioQueueRecordingSecceedTime;
- (void)logStartAudioQueueRecordingTime;
- (void)logStopAudioQueueRecordingTime;
- (void)logUserStopRecording:(_Bool)arg1;
- (void)logfirstAuidoFromAudioQueueTime;
- (id)relativeTimeSiceAppStart;
- (void)resetEvents;
- (id)toJsonString;

@end

