//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface IFlyDebugLog : NSObject
{
}

+ (void)addString:(id)arg1;
+ (void)createFile;
+ (void)setShowLog:(_Bool)arg1;
+ (void)showLog:(id)arg1;
+ (void)writeLog;

@end

