//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface IFlySpeechError : NSObject
{
    int _errorCode;
    int _errorType;
    NSString *_errorDesc;
}

+ (id)initWithError:(int)arg1;
- (void)dealloc;
@property(nonatomic) int errorCode; // @synthesize errorCode=_errorCode;
@property(retain, nonatomic) NSString *errorDesc; // @synthesize errorDesc=_errorDesc;
@property(nonatomic) int errorType; // @synthesize errorType=_errorType;
- (id)getErrorDesc;
- (id)init:(int)arg1;
- (void)initErrorType:(int)arg1;

@end

