//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate, NSMutableDictionary;

@interface IFlySessionPerfLogger : NSObject
{
    NSDate *_dateAppStart;
    NSMutableDictionary *_logs;
}

+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (void)purgeSharedInstance;
+ (id)sharedInstance;
+ (id)sharedInstanceNoSynch;
+ (id)sharedInstanceSynch;
- (void)addInfoLog:(id)arg1 forKey:(id)arg2;
- (void)addLog:(id)arg1 forKey:(id)arg2;
- (void)addLogForKey:(id)arg1;
- (void)addNumberLog:(id)arg1 forKey:(id)arg2;
- (id)autorelease;
- (id)autoreleaseDoNothing;
- (id)autoreleaseDoSomething;
- (void)clearAllLogs;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(retain, nonatomic) NSDate *dateAppStart; // @synthesize dateAppStart=_dateAppStart;
- (void)dealloc;
- (id)init;
@property(retain, nonatomic) NSMutableDictionary *logs; // @synthesize logs=_logs;
- (oneway void)release;
- (void)releaseDoNothing;
- (void)releaseDoSomething;
- (id)retain;
- (unsigned long long)retainCount;
- (unsigned long long)retainCountDoNothing;
- (unsigned long long)retainCountDoSomething;
- (id)timeIntervalSinceAppStart;
- (id)toJsonString;

@end

