//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface IFlyResourceUtil : NSObject
{
}

+ (id)ASR_RES_PATH;
+ (id)ENGINE_DESTROY;
+ (id)ENGINE_START;
+ (id)GRAMMARTYPE;
+ (id)GRM_BUILD_PATH;
+ (id)IVW_RES_PATH;
+ (id)PLUS_LOCAL_DEFAULT_RES_PATH;
+ (id)TTS_RES_PATH;
+ (id)generateResourcePath:(id)arg1;
+ (id)identifierForVoiceName:(id)arg1;

@end

