//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IFlySpeechRecognizer;

@interface IFlySpeechUnderstander : NSObject
{
    id <IFlySpeechRecognizerDelegate> _delegate;
    IFlySpeechRecognizer *_recognizer;
}

+ (id)sharedInstance;
- (void)cancel;
- (void)dealloc;
@property(retain, nonatomic) id <IFlySpeechRecognizerDelegate> delegate; // @synthesize delegate=_delegate;
- (_Bool)destroy;
- (id)getDelegate;
@property(readonly) _Bool isUnderstanding;
@property(retain) IFlySpeechRecognizer *recognizer; // @synthesize recognizer=_recognizer;
- (_Bool)setParameter:(id)arg1 forKey:(id)arg2;
- (_Bool)startListening;
- (void)stopListening;
- (_Bool)writeAudio:(id)arg1;

@end

