//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "IFlyRecognizerViewImpDelegate.h"
#import "NSObject.h"

@class IFlyRecognizerViewImp, NSString;

@interface IFlyRecognizerView : UIView <IFlyRecognizerViewImpDelegate, NSObject>
{
    IFlyRecognizerViewImp *_iFlyRecognizerViewImp;
    double _offset;
    _Bool _autoRotate;
    id <IFlyRecognizerViewDelegate> _delegate;
}

- (void)cancel;
- (void)dealloc;
@property(nonatomic) id <IFlyRecognizerViewDelegate> delegate; // @synthesize delegate=_delegate;
- (id)initWithCenter:(struct CGPoint)arg1;
- (id)initWithOrigin:(struct CGPoint)arg1;
- (void)onError:(id)arg1;
- (void)onResults:(id)arg1 isLast:(_Bool)arg2;
- (id)parameterForKey:(id)arg1;
- (void)respondNotification:(id)arg1;
- (void)rotationToInterfaceOrientation:(long long)arg1;
- (void)setAutoRotate:(_Bool)arg1;
- (_Bool)setParameter:(id)arg1 forKey:(id)arg2;
- (_Bool)start;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

