//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface IFlySpeechConstant : NSObject
{
}

+ (id)ACCENT;
+ (id)ACCENT_CANTONESE;
+ (id)ACCENT_HENANESE;
+ (id)ACCENT_MANDARIN;
+ (id)APPID;
+ (id)ASR_AUDIO_PATH;
+ (id)ASR_PTT;
+ (id)ASR_PTT_HAVEDOT;
+ (id)ASR_PTT_NODOT;
+ (id)ASR_SCH;
+ (id)AUDIO_SOURCE;
+ (id)CLOUD_GRAMMAR;
+ (id)DATA_TYPE;
+ (id)ENGINE_TYPE;
+ (id)FACE_ALIGN;
+ (id)FACE_ATTR;
+ (id)FACE_AUE;
+ (id)FACE_AUTH_ID;
+ (id)FACE_DETECT;
+ (id)FACE_DVC;
+ (id)FACE_GID;
+ (id)FACE_PSET;
+ (id)FACE_RAW;
+ (id)FACE_REG;
+ (id)FACE_SKIP;
+ (id)FACE_SST;
+ (id)FACE_SUB;
+ (id)FACE_VERIFY;
+ (id)FACE_WFR;
+ (id)GRAMMAR_CONTENT;
+ (id)GRAMMAR_LIST;
+ (id)GRAMMAR_TYPE;
+ (id)IFLY_DOMAIN;
+ (id)ISE_AUDIO_PATH;
+ (id)ISE_AUTO_TRACKING;
+ (id)ISE_CATEGORY;
+ (id)ISE_INTERRUPT_ERROR;
+ (id)ISE_PARSED;
+ (id)ISE_RESULT_LEVEL;
+ (id)ISE_RESULT_TYPE;
+ (id)ISE_TRACK_TYPE;
+ (id)ISE_USER_MODEL_ID;
+ (id)IVW_ONESHOT;
+ (id)IVW_SST;
+ (id)IVW_THRESHOLD;
+ (id)KEEP_ALIVE;
+ (id)LANGUAGE;
+ (id)LANGUAGE_CHINESE;
+ (id)LANGUAGE_CHINESE_TW;
+ (id)LANGUAGE_ENGLISH;
+ (id)LEXICON_CONTENT;
+ (id)LEXICON_NAME;
+ (id)LOCAL_GRAMMAR;
+ (id)MFV_AFC;
+ (id)MFV_AUTH_ID;
+ (id)MFV_DATA_ENCODING;
+ (id)MFV_DATA_FORMAT;
+ (id)MFV_DATA_PATH;
+ (id)MFV_FIN;
+ (id)MFV_PTXT;
+ (id)MFV_PWDT;
+ (id)MFV_RGN;
+ (id)MFV_SCENES;
+ (id)MFV_SST;
+ (id)MFV_SUB;
+ (id)MFV_TSD;
+ (id)MFV_VCM;
+ (id)MFV_WTT;
+ (id)MPPLAYINGINFOCENTER;
+ (id)MSCSKIN;
+ (id)NET_TIMEOUT;
+ (id)NEXT_TEXT;
+ (id)NLP_VERSION;
+ (id)PARAMS;
+ (id)PITCH;
+ (id)PLAYER_INIT;
+ (id)PLUS_LOCAL_ALL;
+ (id)PLUS_LOCAL_ASR;
+ (id)PLUS_LOCAL_IVW;
+ (id)PLUS_LOCAL_TTS;
+ (id)POWER_CYCLE;
+ (id)PROT_TYPE;
+ (id)RECORDER_INIT;
+ (id)REQUEST_AUDIO_URL;
+ (id)RESULT_ENCODING;
+ (id)RESULT_TYPE;
+ (id)SAMPLE_RATE;
+ (id)SAMPLE_RATE_16K;
+ (id)SAMPLE_RATE_8K;
+ (id)SPEECH_TIMEOUT;
+ (id)SPEED;
+ (id)SSL_CERT;
+ (id)SUBJECT;
+ (id)TEXT_ENCODING;
+ (id)TTS_AUDIO_PATH;
+ (id)TTS_AUDIO_URI;
+ (id)TTS_AUTO_PLAY;
+ (id)TTS_BUFFER_TIME;
+ (id)TTS_DATA_NOTIFY;
+ (id)TYPE_AUTO;
+ (id)TYPE_CLOUD;
+ (id)TYPE_LOCAL;
+ (id)TYPE_MIX;
+ (id)VAD_BOS;
+ (id)VAD_ENABLE;
+ (id)VAD_EOS;
+ (id)VOICE_ID;
+ (id)VOICE_LANG;
+ (id)VOICE_NAME;
+ (id)VOLUME;

@end

