//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IFlySpeechSynthesizerDelegate.h"

@class IFlySpeechSynthesizerImp, IFlyTTSParam, NSString;

@interface IFlySpeechSynthesizer : NSObject <IFlySpeechSynthesizerDelegate>
{
    _Bool _isListening;
    IFlySpeechSynthesizerImp *_operation;
    IFlySpeechSynthesizerImp *_preOperation;
    IFlyTTSParam *_sessionConfig;
    _Bool _isUri;
    id <IFlySpeechSynthesizerDelegate> _delegate;
}

+ (_Bool)checkFilePathAvailable:(id)arg1;
+ (_Bool)destroy;
+ (id)sharedInstance;
- (void)dealloc;
@property(nonatomic) id <IFlySpeechSynthesizerDelegate> delegate; // @synthesize delegate=_delegate;
- (id)init;
@property(readonly, nonatomic) _Bool isSpeaking;
- (void)movePreToNormal;
- (void)onBufferProgress:(int)arg1 message:(id)arg2;
- (void)onCompleted:(id)arg1;
- (void)onEvent:(int)arg1 arg0:(int)arg2 arg1:(int)arg3 data:(id)arg4;
- (void)onSpeakBegin;
- (void)onSpeakCancel;
- (void)onSpeakPaused;
- (void)onSpeakProgress:(int)arg1 beginPos:(int)arg2 endPos:(int)arg3;
- (void)onSpeakResumed;
- (id)parameterForKey:(id)arg1;
- (void)pauseSpeaking;
- (void)resumeSpeaking;
- (void)runSpeaking:(id)arg1;
- (_Bool)setParameter:(id)arg1 forKey:(id)arg2;
- (void)startPreTTS:(id)arg1;
- (void)startSpeaking:(id)arg1;
- (void)stopSpeaking;
- (void)synthesize:(id)arg1 toUri:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

