//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData, NSString;

@protocol IOpenDynamicDataStoreComponent <NSObject>
- (_Bool)getBool:(NSString *)arg1;
- (NSData *)getData:(NSString *)arg1;
- (NSData *)getDataDDp:(NSString *)arg1;
- (NSData *)getDataDDpEx:(NSString *)arg1 flag:(int)arg2;
- (double)getDouble:(NSString *)arg1;
- (float)getFloat:(NSString *)arg1;
- (long long)getInteger:(NSString *)arg1;
- (NSString *)getString:(NSString *)arg1;
- (NSString *)getStringDDp:(NSString *)arg1;
- (NSString *)getStringDDpEx:(NSString *)arg1 flag:(int)arg2;
- (int)putBool:(_Bool)arg1 forKey:(NSString *)arg2;
- (int)putData:(NSData *)arg1 forKey:(NSString *)arg2;
- (int)putDataDDp:(NSData *)arg1 forKey:(NSString *)arg2;
- (_Bool)putDataDDpEx:(NSData *)arg1 forKey:(NSString *)arg2 flag:(int)arg3;
- (int)putDouble:(double)arg1 forKey:(NSString *)arg2;
- (int)putFloat:(float)arg1 forKey:(NSString *)arg2;
- (int)putInteger:(long long)arg1 forKey:(NSString *)arg2;
- (int)putString:(NSString *)arg1 forKey:(NSString *)arg2;
- (int)putStringDDp:(NSString *)arg1 forKey:(NSString *)arg2;
- (_Bool)putStringDDpEx:(NSString *)arg1 forKey:(NSString *)arg2 flag:(int)arg3;
- (void)removeBoolForKey:(NSString *)arg1;
- (void)removeDataDDpEx:(NSString *)arg1 flag:(int)arg2;
- (void)removeDataForKey:(NSString *)arg1;
- (void)removeDataForKeyDDp:(NSString *)arg1;
- (void)removeDoubleForKey:(NSString *)arg1;
- (void)removeFloatForKey:(NSString *)arg1;
- (void)removeIntegerForKey:(NSString *)arg1;
- (void)removeStringDDpEx:(NSString *)arg1 flag:(int)arg2;
- (void)removeStringForKey:(NSString *)arg1;
- (void)removeStringForKeyDDp:(NSString *)arg1;
@end

