//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IFlyEngine.h"

@interface ISEEngine : IFlyEngine
{
    char _szSessionID[128];
    _Bool _hasResults;
}

- (int)beginWithParams:(id)arg1 extraParams:(id)arg2;
- (int)end;
- (id)getParam:(id)arg1;
- (int)getResult;
- (int)getVolume;
@property(nonatomic) _Bool hasResults; // @synthesize hasResults=_hasResults;
- (id)init;
- (int)putAudio:(id)arg1 length:(unsigned long long)arg2 status:(int)arg3;
- (int)putAudioEnd;
- (int)putText:(id)arg1 withParams:(id)arg2;

@end

