//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IFlyISVParam, NSString;

@interface ISVEngine : NSObject
{
    char _szSession[128];
    _Bool _haveResult;
    NSString *sessionID;
    IFlyISVParam *_sessionConfig;
    NSString *param;
    NSString *_sst;
    _Bool isTvp;
    NSString *_usr;
    NSString *_pwd;
    NSString *_appid;
    NSString *_dataString;
    id <ISVEngineDelegate> _delegate;
}

+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)sharedInstance;
@property(retain, nonatomic) NSString *appid; // @synthesize appid=_appid;
- (id)autorelease;
- (int)beginSession;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(retain, nonatomic) NSString *dataString; // @synthesize dataString=_dataString;
- (void)dealloc;
@property id <ISVEngineDelegate> delegate; // @synthesize delegate=_delegate;
- (_Bool)deleteModel:(id)arg1 ptxt:(id)arg2 auth_id:(id)arg3 errorCode:(int *)arg4;
- (int)getResult;
- (int)getVolume;
- (_Bool)haveResult;
- (id)init;
- (void)isTvp:(_Bool)arg1;
- (int)putData:(const void *)arg1 theWaveLen:(int)arg2 theAudioStatus:(int)arg3;
- (_Bool)putEndData;
- (int)putWaveData:(id)arg1 withLength:(unsigned int)arg2;
@property(retain, nonatomic) NSString *pwd; // @synthesize pwd=_pwd;
- (_Bool)queryModel:(id)arg1 ptxt:(id)arg2 auth_id:(id)arg3 errorCode:(int *)arg4;
- (oneway void)release;
- (id)retain;
- (unsigned long long)retainCount;
- (int)sessionEnd;
- (void)setConfig:(id)arg1;
@property(retain, nonatomic) NSString *usr; // @synthesize usr=_usr;

@end

