//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary;

@interface JLRRouteResponse : NSObject
{
    _Bool _match;
    NSDictionary *_parameters;
}

+ (id)invalidMatchResponse;
+ (id)validMatchResponseWithParameters:(id)arg1;
- (void).cxx_destruct;
- (id)description;
@property(nonatomic, getter=isMatch) _Bool match; // @synthesize match=_match;
@property(retain, nonatomic) NSDictionary *parameters; // @synthesize parameters=_parameters;

@end

