//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseViewController.h"

#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"
#import "UICollectionViewDelegateFlowLayout.h"
#import "UIGestureRecognizerDelegate.h"

@class AppViewCell, NSArray, NSMutableArray, NSString, NSTimer, UIAlertView, UICollectionView, WKNoResultView, WKSheetView;

@interface LaunchViewController : BaseViewController <UICollectionViewDataSource, UICollectionViewDelegate, UIGestureRecognizerDelegate, UICollectionViewDelegateFlowLayout>
{
    UICollectionView *appView;
    NSArray *_whiteListArr;
    NSArray *_blackListArr;
    NSArray *_recommendListArr;
    NSMutableArray *_appDataArray;
    NSMutableArray *_systemAppArr;
    NSMutableArray *_hiddenAppArr;
    long long _sectionCount;
    UIAlertView *_longPressAlertView;
    NSTimer *_cellTimer;
    AppViewCell *_currentCellView;
    NSArray *_originalAppArray;
    NSArray *_todayExtensionAppArray;
    NSArray *_topFeatureItemArr;
    NSMutableArray *_featureItemArr;
    WKSheetView *_sheetView;
    WKNoResultView *_noResultView;
}

- (void).cxx_destruct;
- (void)addHiddenApp:(id)arg1;
- (void)addSearchItems;
- (void)addUpAppByAppData:(id)arg1;
@property(retain, nonatomic) NSMutableArray *appDataArray; // @synthesize appDataArray=_appDataArray;
@property(retain, nonatomic) UICollectionView *appView; // @synthesize appView;
@property(retain, nonatomic) NSArray *blackListArr; // @synthesize blackListArr=_blackListArr;
- (void)buildUI;
- (void)cellTimeout:(id *)arg1;
@property(retain, nonatomic) NSTimer *cellTimer; // @synthesize cellTimer=_cellTimer;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (void)collectionView:(id)arg1 didHighlightItemAtIndexPath:(id)arg2;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (void)collectionView:(id)arg1 didUnhighlightItemAtIndexPath:(id)arg2;
- (struct UIEdgeInsets)collectionView:(id)arg1 layout:(id)arg2 insetForSectionAtIndex:(long long)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 referenceSizeForHeaderInSection:(long long)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (_Bool)collectionView:(id)arg1 shouldHighlightItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 viewForSupplementaryElementOfKind:(id)arg2 atIndexPath:(id)arg3;
@property(retain, nonatomic) AppViewCell *currentCellView; // @synthesize currentCellView=_currentCellView;
- (void)dealloc;
- (void)deletaUpAppByAppData:(id)arg1;
- (void)deviceChanged:(id)arg1;
- (void)didClickedFeatureBtn:(id)arg1;
- (id)disposeAlertTitleArray:(id)arg1;
- (void)disposeHandLongPressAction:(id)arg1;
@property(retain, nonatomic) NSMutableArray *featureItemArr; // @synthesize featureItemArr=_featureItemArr;
- (void)getInstallApplist;
- (void)getRecommendAppList;
- (void)getWhiteList;
- (void)handleLongPress:(id)arg1;
@property(retain, nonatomic) NSMutableArray *hiddenAppArr; // @synthesize hiddenAppArr=_hiddenAppArr;
- (void)initAppCollectionView;
- (void)initHelpView;
- (void)initTopView;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (_Bool)isShowNoDataView;
@property(retain, nonatomic) UIAlertView *longPressAlertView; // @synthesize longPressAlertView=_longPressAlertView;
- (void)mergeAppListWithWhiteAndBlack;
@property(retain, nonatomic) WKNoResultView *noResultView; // @synthesize noResultView=_noResultView;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (void)onAppFolderHandLongPress:(id)arg1;
- (void)onNetWrokChange:(id)arg1;
- (void)openAppFolder:(id)arg1;
- (void)openTVSetting;
@property(retain, nonatomic) NSArray *originalAppArray; // @synthesize originalAppArray=_originalAppArray;
@property(retain, nonatomic) NSArray *recommendListArr; // @synthesize recommendListArr=_recommendListArr;
- (void)removeHiddenApp:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
@property(nonatomic) long long sectionCount; // @synthesize sectionCount=_sectionCount;
- (void)sendChildLock:(long long)arg1;
- (void)serverApplistArrived:(id)arg1;
@property(retain, nonatomic) WKSheetView *sheetView; // @synthesize sheetView=_sheetView;
@property(retain, nonatomic) NSMutableArray *systemAppArr; // @synthesize systemAppArr=_systemAppArr;
@property(retain, nonatomic) NSArray *todayExtensionAppArray; // @synthesize todayExtensionAppArray=_todayExtensionAppArray;
@property(retain, nonatomic) NSArray *topFeatureItemArr; // @synthesize topFeatureItemArr=_topFeatureItemArr;
@property(retain, nonatomic) NSArray *whiteListArr; // @synthesize whiteListArr=_whiteListArr;
- (void)setupChildLock;
- (void)showNoDataView;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

