//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIColor;

@interface M13ProgressView : UIView
{
    _Bool _indeterminate;
    UIColor *_primaryColor;
    UIColor *_secondaryColor;
    double _animationDuration;
    double _progress;
}

- (void).cxx_destruct;
@property(nonatomic) double animationDuration; // @synthesize animationDuration=_animationDuration;
@property(nonatomic) _Bool indeterminate; // @synthesize indeterminate=_indeterminate;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)performAction:(int)arg1 animated:(_Bool)arg2;
@property(retain, nonatomic) UIColor *primaryColor; // @synthesize primaryColor=_primaryColor;
@property(readonly, nonatomic) double progress; // @synthesize progress=_progress;
@property(retain, nonatomic) UIColor *secondaryColor; // @synthesize secondaryColor=_secondaryColor;
- (void)setProgress:(double)arg1 animated:(_Bool)arg2;

@end

