//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface MiPushRPCID : NSObject
{
    NSString *rpcID;
    struct dispatch_source_s *timer;
}

- (void)cancelTimer;
- (void)dealloc;
- (unsigned long long)hash;
- (id)initWithRpcID:(id)arg1 timer:(struct dispatch_source_s *)arg2;
- (_Bool)isEqual:(id)arg1;
@property(readonly, nonatomic) NSString *rpcID; // @synthesize rpcID;
@property(readonly, nonatomic) struct dispatch_source_s *timer; // @synthesize timer;

@end

