//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MiPushGCDAsyncSocket, MiPushXMPPJID, MiPushXMPPStream, NSArray, NSDate, NSMutableArray, NSString;

@interface MiPushTURNSocket : NSObject
{
    int state;
    _Bool isClient;
    struct dispatch_queue_s *turnQueue;
    MiPushXMPPStream *xmppStream;
    MiPushXMPPJID *jid;
    NSString *uuid;
    id delegate;
    struct dispatch_queue_s *delegateQueue;
    struct dispatch_source_s *turnTimer;
    NSString *discoUUID;
    struct dispatch_source_s *discoTimer;
    NSArray *proxyCandidates;
    unsigned long long proxyCandidateIndex;
    NSMutableArray *candidateJIDs;
    unsigned long long candidateJIDIndex;
    NSMutableArray *streamhosts;
    unsigned long long streamhostIndex;
    MiPushXMPPJID *proxyJID;
    NSString *proxyHost;
    unsigned short proxyPort;
    MiPushGCDAsyncSocket *asyncSocket;
    NSDate *startTime;
    NSDate *finishTime;
}

+ (void)initialize;
+ (_Bool)isNewStartTURNRequest:(id)arg1;
+ (id)proxyCandidates;
+ (void)setProxyCandidates:(id)arg1;
- (void)abort;
- (void)cleanup;
- (void)dealloc;
- (void)doDiscoAddressTimeout:(id)arg1;
- (void)doDiscoInfoTimeout:(id)arg1;
- (void)doDiscoItemsTimeout:(id)arg1;
- (void)doTotalTimeout;
- (void)fail;
- (id)initWithStream:(id)arg1 incomingTURNRequest:(id)arg2;
- (id)initWithStream:(id)arg1 toJID:(id)arg2;
- (void)initiatorConnect;
- (_Bool)isClient;
- (void)performPostInitSetup;
- (void)processActivateResponse:(id)arg1;
- (void)processDiscoAddressResponse:(id)arg1;
- (void)processDiscoInfoResponse:(id)arg1;
- (void)processDiscoItemsResponse:(id)arg1;
- (void)processRequestResponse:(id)arg1;
- (void)queryCandidateJIDs;
- (void)queryNextCandidateJID;
- (void)queryNextProxyCandidate;
- (void)queryProxyAddress;
- (void)queryProxyCandidates;
- (void)sendActivate;
- (void)sendError;
- (void)sendReply;
- (void)sendRequest;
- (void)setupDiscoTimer:(double)arg1;
- (void)setupDiscoTimerForDiscoAddress;
- (void)setupDiscoTimerForDiscoInfo;
- (void)setupDiscoTimerForDiscoItems;
- (void)socket:(id)arg1 didConnectToHost:(id)arg2 port:(unsigned short)arg3;
- (void)socket:(id)arg1 didReadData:(id)arg2 withTag:(long long)arg3;
- (void)socketDidDisconnect:(id)arg1 withError:(id)arg2;
- (void)socksConnect;
- (void)socksOpen;
- (void)startWithDelegate:(id)arg1 delegateQueue:(struct dispatch_queue_s *)arg2;
- (void)succeed;
- (void)targetConnect;
- (void)targetNextConnect;
- (void)updateDiscoUUID;
- (_Bool)xmppStream:(id)arg1 didReceiveIQ:(id)arg2;

@end

