//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MiPushSDKCoreParam : NSObject
{
}

+ (_Bool)checkDeviceTokenCacheValid;
+ (id)getAppID;
+ (id)getAppPackageName;
+ (id)getAppSecretANDROID;
+ (id)getAppSecretIOS;
+ (id)getAppToken;
+ (id)getAppVersion;
+ (id)getDeviceID;
+ (id)getDeviceIMEI;
+ (id)getDeviceModel;
+ (id)getDevicePlatform;
+ (id)getResourceID;
+ (id)getSDKVersion;
+ (id)getServiceURLFlag;
+ (id)getSystemLanguage;
+ (id)getXMPPDomain;
+ (_Bool)isDistribution;

@end

