//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@protocol MiPushXMPPTrackingInfo <NSObject>
- (void)cancelTimer;
- (void)createTimerWithDispatchQueue:(struct dispatch_queue_s *)arg1;
@property(copy, nonatomic) NSString *elementID;
- (void)invokeWithObject:(id)arg1;
@property(readonly, nonatomic) double timeout;
@end

