//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MiPushDDXMLNode.h"

@interface MiPushDDXMLNamespaceNode : MiPushDDXMLNode
{
    struct _xmlNode *nsParentPtr;
}

+ (id)nodeWithNsPrimitive:(struct _xmlNs *)arg1 nsParent:(struct _xmlNode *)arg2 owner:(id)arg3;
+ (id)nodeWithPrimitive:(struct _miPushXmlKind *)arg1 owner:(id)arg2;
- (id)URI;
- (struct _miPushXmlStd *)_XPathPreProcess:(id)arg1;
- (_Bool)_hasParent;
- (struct _xmlNode *)_nsParentPtr;
- (void)_setNsParentPtr:(struct _xmlNode *)arg1;
- (id)childAtIndex:(unsigned long long)arg1;
- (unsigned long long)childCount;
- (id)children;
- (void)detach;
- (unsigned long long)index;
- (id)initWithNsPrimitive:(struct _xmlNs *)arg1 nsParent:(struct _xmlNode *)arg2 owner:(id)arg3;
- (id)initWithPrimitive:(struct _miPushXmlKind *)arg1 owner:(id)arg2;
- (unsigned long long)level;
- (id)localName;
- (id)name;
- (id)nextNode;
- (id)nextSibling;
- (id)parent;
- (id)prefix;
- (id)previousNode;
- (id)previousSibling;
- (id)rootDocument;
- (void)setName:(id)arg1;
- (void)setStringValue:(id)arg1;
- (void)setURI:(id)arg1;
- (id)stringValue;

@end

