//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MiPushUDID : NSObject
{
}

+ (id)appleIDFA;
+ (id)appleIDFV;
+ (id)randomUDID;
+ (void)save:(id)arg1;
+ (void)saveUDIDToKeychain:(id)arg1;
+ (void)saveUDIDToPasteboard:(id)arg1;
+ (void)saveUDIDToUserDefaults:(id)arg1;
+ (id)udidInKeychain;
+ (id)udidInPasteboard;
+ (id)udidInUserDefaults;
+ (id)value;

@end

