//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "XMXmppChannelProtocol.h"

@class NSString, XMXmppChannelBindInfo;

@interface MiPushXmppChannel : NSObject <XMXmppChannelProtocol>
{
    id <MLXmppConnectorProtocol> objXmppConnector;
    id <MiPushSDKDelegate> objConnectDelegate;
}

- (id)getMessageIndex;
- (id)getRC4Key:(id)arg1 source:(id)arg2;
@property(readonly, nonatomic) XMXmppChannelBindInfo *mBindInfo;
@property(readonly, nonatomic) NSString *mChannelDescription;
@property(readonly, nonatomic) int mChannelId;
- (void)miPushReceiveNotification:(id)arg1;
- (id)milliSecondTimeStamp;
- (void)mipushDebugLog:(id)arg1 data:(id)arg2;
@property(nonatomic) id <MiPushSDKDelegate> objConnectDelegate; // @synthesize objConnectDelegate;
@property(nonatomic) id <MLXmppConnectorProtocol> objXmppConnector; // @synthesize objXmppConnector;
- (void)onBecomeOffline:(_Bool)arg1;
- (void)onBecomeOnline;
- (_Bool)onReceiveIQ:(id)arg1;
- (void)onReceiveMessage:(id)arg1;
- (void)onServerConnected:(id)arg1;
- (void)onServerWillConnect;
- (void)parseMessage:(id)arg1;
- (void)registerXMPP;
- (void)sendACK:(id)arg1;
- (void)sendACKWithMessageID:(id)arg1;
- (void)sendMessage:(id)arg1;
- (void)sendMessage:(id)arg1 actionType:(int)arg2 messageIndex:(id)arg3;
- (void)sendSleepPing;
- (void)sendWakeupPing;
- (void)setAlias:(id)arg1;
- (void)subscribe:(id)arg1;
- (id)thrift2data:(id)arg1;
- (void)unsetAlias:(id)arg1;
- (void)unsubscribe:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

