//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MiPushXMPPElement.h"

@interface MiPushXMPPIQ : MiPushXMPPElement
{
}

+ (id)elementMethodCall;
+ (id)elementMethodName:(id)arg1;
+ (id)elementParams;
+ (id)elementRpcFeature;
+ (id)elementRpcIdentity;
+ (id)elementRpcQuery;
+ (void)initialize;
+ (id)iq;
+ (id)iqFromElement:(id)arg1;
+ (id)iqWithType:(id)arg1;
+ (id)iqWithType:(id)arg1 chid:(id)arg2 from:(id)arg3 to:(id)arg4 elementID:(id)arg5 child:(id)arg6;
+ (id)iqWithType:(id)arg1 to:(id)arg2;
+ (id)iqWithType:(id)arg1 to:(id)arg2 elementID:(id)arg3;
+ (id)iqWithType:(id)arg1 to:(id)arg2 elementID:(id)arg3 child:(id)arg4;
+ (id)paramElementFromObject:(id)arg1;
+ (id)rpcTo:(id)arg1 methodName:(id)arg2 parameters:(id)arg3;
+ (id)valueElementFromArray:(id)arg1;
+ (id)valueElementFromBoolean:(struct __CFBoolean *)arg1;
+ (id)valueElementFromData:(id)arg1;
+ (id)valueElementFromDate:(id)arg1;
+ (id)valueElementFromDictionary:(id)arg1;
+ (id)valueElementFromElementWithName:(id)arg1 value:(id)arg2;
+ (id)valueElementFromNumber:(id)arg1;
+ (id)valueElementFromObject:(id)arg1;
+ (id)valueElementFromString:(id)arg1;
+ (id)wrapElement:(id)arg1 aroundElement:(id)arg2;
+ (id)wrapValueElementAroundElement:(id)arg1;
- (id)childElement;
- (id)childErrorElement;
- (id)init;
- (id)initWithType:(id)arg1;
- (id)initWithType:(id)arg1 to:(id)arg2;
- (id)initWithType:(id)arg1 to:(id)arg2 elementID:(id)arg3;
- (id)initWithType:(id)arg1 to:(id)arg2 elementID:(id)arg3 child:(id)arg4;
- (_Bool)isErrorIQ;
- (_Bool)isFault;
- (_Bool)isGetIQ;
- (_Bool)isJabberRPC;
- (_Bool)isMethodResponse;
- (_Bool)isResultIQ;
- (_Bool)isSetIQ;
- (id)methodResponse:(id *)arg1;
- (id)methodResponseElement;
- (id)objectFromElement:(id)arg1;
- (id)parseArray:(id)arg1;
- (id)parseBoolean:(id)arg1;
- (id)parseData:(id)arg1;
- (id)parseDate:(id)arg1;
- (id)parseDateString:(id)arg1 withFormat:(id)arg2;
- (id)parseDouble:(id)arg1;
- (id)parseInteger:(id)arg1;
- (id)parseMember:(id)arg1;
- (id)parseString:(id)arg1;
- (id)parseStruct:(id)arg1;
- (_Bool)requiresResponse;
- (id)type;

@end

