//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MiPushASIHTTPRequest, NSData, NSDictionary, NSURL;

@protocol MiPushASIHTTPRequestDelegate <NSObject>

@optional
- (void)authenticationNeededForRequest:(MiPushASIHTTPRequest *)arg1;
- (void)proxyAuthenticationNeededForRequest:(MiPushASIHTTPRequest *)arg1;
- (void)request:(MiPushASIHTTPRequest *)arg1 didReceiveData:(NSData *)arg2;
- (void)request:(MiPushASIHTTPRequest *)arg1 didReceiveResponseHeaders:(NSDictionary *)arg2;
- (void)request:(MiPushASIHTTPRequest *)arg1 willRedirectToURL:(NSURL *)arg2;
- (void)requestFailed:(MiPushASIHTTPRequest *)arg1;
- (void)requestFinished:(MiPushASIHTTPRequest *)arg1;
- (void)requestRedirected:(MiPushASIHTTPRequest *)arg1;
- (void)requestStarted:(MiPushASIHTTPRequest *)arg1;
@end

