//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MiPushASIHTTPRequest, NSData, NSDate, NSDictionary, NSString, NSURL;

@protocol MiPushASICacheDelegate <NSObject>
- (NSData *)cachedResponseDataForURL:(NSURL *)arg1;
- (NSDictionary *)cachedResponseHeadersForURL:(NSURL *)arg1;
- (_Bool)canUseCachedDataForRequest:(MiPushASIHTTPRequest *)arg1;
- (void)clearCachedResponsesForStoragePolicy:(int)arg1;
- (int)defaultCachePolicy;
- (NSDate *)expiryDateForRequest:(MiPushASIHTTPRequest *)arg1 maxAge:(double)arg2;
- (_Bool)isCachedDataCurrentForRequest:(MiPushASIHTTPRequest *)arg1;
- (NSString *)pathToCachedResponseDataForURL:(NSURL *)arg1;
- (NSString *)pathToCachedResponseHeadersForURL:(NSURL *)arg1;
- (NSString *)pathToStoreCachedResponseDataForRequest:(MiPushASIHTTPRequest *)arg1;
- (NSString *)pathToStoreCachedResponseHeadersForRequest:(MiPushASIHTTPRequest *)arg1;
- (void)removeCachedDataForRequest:(MiPushASIHTTPRequest *)arg1;
- (void)removeCachedDataForURL:(NSURL *)arg1;
- (void)storeResponseForRequest:(MiPushASIHTTPRequest *)arg1 maxAge:(double)arg2;
- (void)updateExpiryForRequest:(MiPushASIHTTPRequest *)arg1 maxAge:(double)arg2;
@end

