//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MJPropertyType, NSMutableDictionary, NSString;

@interface MJProperty : NSObject
{
    struct objc_property *_property;
    NSString *_name;
    MJPropertyType *_type;
    Class _srcClass;
    NSMutableDictionary *_propertyKeysDict;
    NSMutableDictionary *_objectClassInArrayDict;
}

+ (id)cachedPropertyWithProperty:(struct objc_property *)arg1;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSString *name; // @synthesize name=_name;
@property(retain, nonatomic) NSMutableDictionary *objectClassInArrayDict; // @synthesize objectClassInArrayDict=_objectClassInArrayDict;
- (Class)objectClassInArrayForClass:(Class)arg1;
@property(nonatomic) struct objc_property *property; // @synthesize property=_property;
@property(retain, nonatomic) NSMutableDictionary *propertyKeysDict; // @synthesize propertyKeysDict=_propertyKeysDict;
- (id)propertyKeysForClass:(Class)arg1;
- (id)propertyKeysWithStringKey:(id)arg1;
- (void)setObjectClassInArray:(Class)arg1 forClass:(Class)arg2;
- (void)setOriginKey:(id)arg1 forClass:(Class)arg2;
- (void)setPorpertyKeys:(id)arg1 forClass:(Class)arg2;
@property(nonatomic) Class srcClass; // @synthesize srcClass=_srcClass;
- (void)setValue:(id)arg1 forObject:(id)arg2;
@property(readonly, nonatomic) MJPropertyType *type; // @synthesize type=_type;
- (id)valueForObject:(id)arg1;

@end

