//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary;

@interface MLSmartHost : NSObject
{
    struct dispatch_queue_s *objTaskQueue;
    NSDictionary *dicHosts;
    int nXmppWIFI;
    int nXmppWWAN;
}

- (void).cxx_destruct;
- (void)dealloc;
- (struct dispatch_queue_s *)getTaskQueue;
- (id)nextHostInfo;
- (id)nextURL;
- (void)resetHostInfo;
- (void)update;

@end

