//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MobClickJob : NSObject
{
    int _defcon;
    _Bool _jobRunning;
}

+ (_Bool)defconPass;
+ (double)elapsedTimeFromPost;
+ (void)preparePerformJob:(int)arg1;
+ (id)sharedInstance;
+ (_Bool)shouldCommitJob:(int)arg1;
@property(nonatomic) int defcon; // @synthesize defcon=_defcon;
- (id)description;
@property(nonatomic) _Bool jobRunning; // @synthesize jobRunning=_jobRunning;
- (_Bool)ready;

@end

