//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIScrollView.h"

#import "MWTapDetectingImageViewDelegate.h"
#import "MWTapDetectingViewDelegate.h"
#import "UIScrollViewDelegate.h"

@class MWCaptionView, MWPhotoBrowser, MWTapDetectingImageView, MWTapDetectingView, NSString, UIButton, UIImageView;

@interface MWZoomingScrollView : UIScrollView <UIScrollViewDelegate, MWTapDetectingImageViewDelegate, MWTapDetectingViewDelegate>
{
    MWPhotoBrowser *_photoBrowser;
    MWTapDetectingView *_tapView;
    MWTapDetectingImageView *_photoImageView;
    UIImageView *_loadingError;
    unsigned long long _index;
    id <MWPhoto> _photo;
    MWCaptionView *_captionView;
    UIButton *_selectedButton;
    UIButton *_playButton;
}

- (void).cxx_destruct;
@property(nonatomic) __weak MWCaptionView *captionView; // @synthesize captionView=_captionView;
- (void)dealloc;
- (void)displayImage;
- (void)displayImageFailure;
- (_Bool)displayingVideo;
- (void)handleDoubleTap:(struct CGPoint)arg1;
- (void)handleSingleTap:(struct CGPoint)arg1;
- (void)hideImageFailure;
- (void)imageView:(id)arg1 doubleTapDetected:(id)arg2;
- (void)imageView:(id)arg1 singleTapDetected:(id)arg2;
@property unsigned long long index; // @synthesize index=_index;
- (id)initWithPhotoBrowser:(id)arg1;
- (double)initialZoomScaleWithMinScale;
- (void)layoutSubviews;
@property(retain, nonatomic) id <MWPhoto> photo; // @synthesize photo=_photo;
@property(nonatomic) __weak UIButton *playButton; // @synthesize playButton=_playButton;
- (void)prepareForReuse;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewDidZoom:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)scrollViewWillBeginZooming:(id)arg1 withView:(id)arg2;
@property(nonatomic) __weak UIButton *selectedButton; // @synthesize selectedButton=_selectedButton;
- (void)setImageHidden:(_Bool)arg1;
- (void)setMaxMinZoomScalesForCurrentBounds;
- (void)view:(id)arg1 doubleTapDetected:(id)arg2;
- (void)view:(id)arg1 singleTapDetected:(id)arg2;
- (id)viewForZoomingInScrollView:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

