//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CustomIOSAlertView.h"

@interface NetWorkSwitchAlertView : CustomIOSAlertView
{
    _Bool _isShow;
    CDUnknownBlockType _buttonClickBlock;
}

- (void).cxx_destruct;
@property(copy, nonatomic) CDUnknownBlockType buttonClickBlock; // @synthesize buttonClickBlock=_buttonClickBlock;
- (void)close;
- (id)init;
@property(nonatomic) _Bool isShow; // @synthesize isShow=_isShow;
- (void)negativeBtnClick:(id)arg1;
- (void)positiveBtnClick:(id)arg1;
- (void)removeFromSuperview;
- (void)show;

@end

