//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface NSObject (MJClass)
+ (void)enumerateAllClasses:(CDUnknownBlockType)arg1;
+ (void)enumerateClasses:(CDUnknownBlockType)arg1;
+ (void)setupAllowedCodingPropertyNames:(CDUnknownBlockType)arg1;
+ (void)setupAllowedPropertyNames:(CDUnknownBlockType)arg1;
+ (void)setupBlockReturnValue:(CDUnknownBlockType)arg1 key:(const char *)arg2;
+ (void)setupIgnoredCodingPropertyNames:(CDUnknownBlockType)arg1;
+ (void)setupIgnoredPropertyNames:(CDUnknownBlockType)arg1;
+ (id)totalAllowedCodingPropertyNames;
+ (id)totalAllowedPropertyNames;
+ (id)totalIgnoredCodingPropertyNames;
+ (id)totalIgnoredPropertyNames;
+ (id)totalObjectsWithSelector:(SEL)arg1 key:(const char *)arg2;
@end

