//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

@interface OpenSecurityGuardManager : NSObject
{
    NSMutableDictionary *_sdkDict;
}

+ (id)getInstance;
- (void).cxx_destruct;
- (id)getAtlasEncryptComp;
- (id)getComponent:(int)arg1;
- (id)getDataCollectionComp;
- (id)getDynamicDataEncryptComp;
- (id)getDynamicDataStoreComp;
- (id)getInterface:(id)arg1;
- (id)getNoCaptchaComp;
- (id)getOpenOpenSDKComp;
- (id)getSDKVersion;
- (id)getSecureSignatureComp;
- (id)getSimulatorDetectComp;
- (id)getStaticDataEncryptComp;
- (id)getStaticDataStoreComp;
- (id)getStaticKeyEncryptComp;
- (id)getUMIDComp;
- (_Bool)isOpen;
@property(retain, nonatomic) NSMutableDictionary *sdkDict; // @synthesize sdkDict=_sdkDict;

@end

