//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableData;

@interface SBJsonUTF8Stream : NSObject
{
    const char *_bytes;
    NSMutableData *_data;
    unsigned long long _length;
    unsigned long long _index;
}

- (void).cxx_destruct;
- (void)appendData:(id)arg1;
- (_Bool)getNextUnichar:(unsigned short *)arg1;
- (_Bool)getStringFragment:(id *)arg1;
- (_Bool)getUnichar:(unsigned short *)arg1;
- (_Bool)haveRemainingCharacters:(unsigned long long)arg1;
@property unsigned long long index; // @synthesize index=_index;
- (id)init;
- (void)skip;
- (_Bool)skipCharacters:(const char *)arg1 length:(unsigned long long)arg2;
- (void)skipWhitespace;
- (id)stringWithRange:(struct _NSRange)arg1;

@end

