//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSMutableDictionary, NSString, SBJson4StreamWriterState;

@interface SBJson4StreamWriter : NSObject
{
    NSMutableDictionary *cache;
    _Bool _humanReadable;
    _Bool _sortKeys;
    SBJson4StreamWriterState *_state;
    NSMutableArray *_stateStack;
    id <SBJson4StreamWriterDelegate> _delegate;
    unsigned long long _maxDepth;
    CDUnknownBlockType _sortKeysComparator;
    NSString *_error;
}

+ (void)initialize;
- (void).cxx_destruct;
- (void)appendBytes:(const void *)arg1 length:(unsigned long long)arg2;
@property(nonatomic) __weak id <SBJson4StreamWriterDelegate> delegate; // @synthesize delegate=_delegate;
@property(copy, nonatomic) NSString *error; // @synthesize error=_error;
@property(nonatomic) _Bool humanReadable; // @synthesize humanReadable=_humanReadable;
- (id)init;
@property(nonatomic) unsigned long long maxDepth; // @synthesize maxDepth=_maxDepth;
@property(nonatomic) _Bool sortKeys; // @synthesize sortKeys=_sortKeys;
@property(copy, nonatomic) CDUnknownBlockType sortKeysComparator; // @synthesize sortKeysComparator=_sortKeysComparator;
@property(nonatomic) __weak SBJson4StreamWriterState *state; // @synthesize state=_state;
@property(readonly, nonatomic) NSMutableArray *stateStack; // @synthesize stateStack=_stateStack;
- (_Bool)writeArray:(id)arg1;
- (_Bool)writeArrayClose;
- (_Bool)writeArrayOpen;
- (_Bool)writeBool:(_Bool)arg1;
- (_Bool)writeNull;
- (_Bool)writeNumber:(id)arg1;
- (_Bool)writeObject:(id)arg1;
- (_Bool)writeObjectClose;
- (_Bool)writeObjectOpen;
- (_Bool)writeString:(id)arg1;
- (_Bool)writeValue:(id)arg1;

@end

