//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, SBJsonUTF8Stream;

@interface SBJsonTokeniser : NSObject
{
    NSString *_error;
    SBJsonUTF8Stream *_stream;
}

+ (void)initialize;
- (void).cxx_destruct;
- (void)appendData:(id)arg1;
- (_Bool)decodeEscape:(unsigned short)arg1 into:(unsigned short *)arg2;
- (_Bool)decodeHexQuad:(unsigned short *)arg1;
@property(copy) NSString *error; // @synthesize error=_error;
- (int)getNumberToken:(id *)arg1;
- (int)getStringToken:(id *)arg1;
- (int)getToken:(id *)arg1;
- (id)init;
- (int)match:(const char *)arg1 length:(unsigned long long)arg2 retval:(int)arg3;
@property(retain) SBJsonUTF8Stream *stream; // @synthesize stream=_stream;

@end

