//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SBJson4StreamWriterDelegate.h"

@class NSMutableData, NSString;

@interface SBJson4Writer : NSObject <SBJson4StreamWriterDelegate>
{
    _Bool _humanReadable;
    _Bool _sortKeys;
    unsigned long long _maxDepth;
    NSString *_error;
    CDUnknownBlockType _sortKeysComparator;
    NSMutableData *_acc;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableData *acc; // @synthesize acc=_acc;
- (id)dataWithObject:(id)arg1;
@property(copy, nonatomic) NSString *error; // @synthesize error=_error;
@property(nonatomic) _Bool humanReadable; // @synthesize humanReadable=_humanReadable;
- (id)init;
@property(nonatomic) unsigned long long maxDepth; // @synthesize maxDepth=_maxDepth;
@property(nonatomic) _Bool sortKeys; // @synthesize sortKeys=_sortKeys;
@property(copy, nonatomic) CDUnknownBlockType sortKeysComparator; // @synthesize sortKeysComparator=_sortKeysComparator;
- (id)stringWithObject:(id)arg1;
- (void)writer:(id)arg1 appendBytes:(const void *)arg2 length:(unsigned long long)arg3;

@end

