//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class NSString, UIColor, UIFont, UIImageView, UILabel;

@interface SDCollectionViewCell : UICollectionViewCell
{
    UILabel *_titleLabel;
    _Bool _hasConfigured;
    _Bool _onlyDisplayText;
    UIImageView *_imageView;
    NSString *_title;
    UIColor *_titleLabelTextColor;
    UIFont *_titleLabelTextFont;
    UIColor *_titleLabelBackgroundColor;
    double _titleLabelHeight;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool hasConfigured; // @synthesize hasConfigured=_hasConfigured;
@property(nonatomic) __weak UIImageView *imageView; // @synthesize imageView=_imageView;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
@property(nonatomic) _Bool onlyDisplayText; // @synthesize onlyDisplayText=_onlyDisplayText;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) UIColor *titleLabelBackgroundColor; // @synthesize titleLabelBackgroundColor=_titleLabelBackgroundColor;
@property(nonatomic) double titleLabelHeight; // @synthesize titleLabelHeight=_titleLabelHeight;
@property(retain, nonatomic) UIColor *titleLabelTextColor; // @synthesize titleLabelTextColor=_titleLabelTextColor;
@property(retain, nonatomic) UIFont *titleLabelTextFont; // @synthesize titleLabelTextFont=_titleLabelTextFont;
- (void)setupImageView;
- (void)setupTitleLabel;

@end

