//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SDiOSVersion : NSObject
{
}

+ (id)deviceNameForVersion:(long long)arg1;
+ (id)deviceNameString;
+ (id)deviceNamesByCode;
+ (long long)deviceSize;
+ (id)deviceSizeName:(long long)arg1;
+ (long long)deviceVersion;
+ (_Bool)isZoomed;
+ (long long)resolutionSize;
+ (_Bool)versionEqualTo:(id)arg1;
+ (_Bool)versionGreaterThan:(id)arg1;
+ (_Bool)versionGreaterThanOrEqualTo:(id)arg1;
+ (_Bool)versionLessThan:(id)arg1;
+ (_Bool)versionLessThanOrEqualTo:(id)arg1;

@end

