//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData, NSDate, NSString;

@interface STSimplePing : NSObject
{
    _Bool _nextSequenceNumberHasWrapped;
    unsigned short _identifier;
    unsigned short _nextSequenceNumber;
    NSString *_hostName;
    id <STSimplePingDelegate> _delegate;
    long long _addressStyle;
    NSData *_hostAddress;
    NSString *_IPAddress;
    long long _packetLength;
    struct __CFHost *_host;
    struct __CFSocket *_socket;
    NSDate *_pingStartDate;
}

+ (unsigned long long)icmpHeaderOffsetInIPv4Packet:(id)arg1 timeToLive:(long long *)arg2;
- (void).cxx_destruct;
@property(copy, nonatomic) NSString *IPAddress; // @synthesize IPAddress=_IPAddress;
@property(nonatomic) long long addressStyle; // @synthesize addressStyle=_addressStyle;
- (void)dealloc;
@property(nonatomic) __weak id <STSimplePingDelegate> delegate; // @synthesize delegate=_delegate;
- (void)didFailWithError:(id)arg1;
- (void)didFailWithHostStreamError:(CDStruct_87dc826d)arg1;
@property(retain, nonatomic) struct __CFHost *host; // @synthesize host=_host;
@property(copy, nonatomic) NSData *hostAddress; // @synthesize hostAddress=_hostAddress;
@property(readonly, nonatomic) unsigned char hostAddressFamily;
@property(readonly, copy, nonatomic) NSString *hostName; // @synthesize hostName=_hostName;
- (void)hostResolutionDone;
@property(readonly, nonatomic) unsigned short identifier; // @synthesize identifier=_identifier;
- (id)initWithHostName:(id)arg1;
@property(nonatomic) unsigned short nextSequenceNumber; // @synthesize nextSequenceNumber=_nextSequenceNumber;
@property(nonatomic) _Bool nextSequenceNumberHasWrapped; // @synthesize nextSequenceNumberHasWrapped=_nextSequenceNumberHasWrapped;
@property(readonly, nonatomic) long long packetLength; // @synthesize packetLength=_packetLength;
- (id)packetWithPingData:(id)arg1;
- (id)pingPacketWithType:(unsigned char)arg1 payload:(id)arg2 requiresChecksum:(_Bool)arg3;
@property(retain, nonatomic) NSDate *pingStartDate; // @synthesize pingStartDate=_pingStartDate;
- (void)readData;
- (void)sendPacket:(id)arg1;
@property(retain, nonatomic) struct __CFSocket *socket; // @synthesize socket=_socket;
- (void)start;
- (void)startWithHostAddress;
- (void)stop;
- (void)stopHostResolution;
- (void)stopSocket;
- (_Bool)validatePing4ResponsePacket:(id)arg1 sequenceNumber:(unsigned short *)arg2 timeToLive:(long long *)arg3;
- (_Bool)validatePing6ResponsePacket:(id)arg1 sequenceNumber:(unsigned short *)arg2;
- (_Bool)validatePingResponsePacket:(id)arg1 sequenceNumber:(unsigned short *)arg2 timeToLive:(long long *)arg3;
- (_Bool)validateSequenceNumber:(unsigned short)arg1;

@end

