//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSDate, NSDateFormatter, NSMutableArray, SVPullToRefreshArrow, UIActivityIndicatorView, UIColor, UILabel, UIScrollView;

@interface SVPullToRefreshView : UIView
{
    _Bool _showsPullToRefresh;
    _Bool _wasTriggeredByUser;
    _Bool _showsDateLabel;
    _Bool _isObserving;
    CDUnknownBlockType pullToRefreshActionHandler;
    UIColor *arrowColor;
    UIColor *textColor;
    long long activityIndicatorViewStyle;
    NSDate *lastUpdatedDate;
    NSDateFormatter *dateFormatter;
    unsigned long long _state;
    UIScrollView *_scrollView;
    SVPullToRefreshArrow *_arrow;
    UIActivityIndicatorView *_activityIndicatorView;
    UILabel *_titleLabel;
    UILabel *_dateLabel;
    UILabel *_subtitleLabel;
    NSMutableArray *_titles;
    NSMutableArray *_subtitles;
    NSMutableArray *_viewForState;
    double _originalTopInset;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIActivityIndicatorView *activityIndicatorView; // @synthesize activityIndicatorView=_activityIndicatorView;
@property(nonatomic) long long activityIndicatorViewStyle; // @synthesize activityIndicatorViewStyle;
@property(retain, nonatomic) SVPullToRefreshArrow *arrow; // @synthesize arrow=_arrow;
@property(retain, nonatomic) UIColor *arrowColor; // @synthesize arrowColor;
@property(retain, nonatomic) NSDateFormatter *dateFormatter; // @synthesize dateFormatter;
@property(readonly, nonatomic) UILabel *dateLabel; // @synthesize dateLabel=_dateLabel;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic) _Bool isObserving; // @synthesize isObserving=_isObserving;
@property(retain, nonatomic) NSDate *lastUpdatedDate; // @synthesize lastUpdatedDate;
- (void)layoutSubviews;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
@property(nonatomic) double originalTopInset; // @synthesize originalTopInset=_originalTopInset;
@property(copy, nonatomic) CDUnknownBlockType pullToRefreshActionHandler; // @synthesize pullToRefreshActionHandler;
- (void)resetScrollViewContentInset;
- (void)rotateArrow:(float)arg1 hide:(_Bool)arg2;
@property(nonatomic) __weak UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
- (void)scrollViewDidScroll:(struct CGPoint)arg1;
- (void)setCustomView:(id)arg1 forState:(unsigned long long)arg2;
- (void)setScrollViewContentInset:(struct UIEdgeInsets)arg1;
- (void)setScrollViewContentInsetForLoading;
@property(nonatomic) _Bool showsDateLabel; // @synthesize showsDateLabel=_showsDateLabel;
@property(nonatomic) _Bool showsPullToRefresh; // @synthesize showsPullToRefresh=_showsPullToRefresh;
@property(nonatomic) unsigned long long state; // @synthesize state=_state;
- (void)setSubtitle:(id)arg1 forState:(unsigned long long)arg2;
@property(retain, nonatomic) UILabel *subtitleLabel; // @synthesize subtitleLabel=_subtitleLabel;
@property(retain, nonatomic) NSMutableArray *subtitles; // @synthesize subtitles=_subtitles;
@property(retain, nonatomic) UIColor *textColor; // @synthesize textColor;
- (void)setTitle:(id)arg1 forState:(unsigned long long)arg2;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) NSMutableArray *titles; // @synthesize titles=_titles;
@property(retain, nonatomic) NSMutableArray *viewForState; // @synthesize viewForState=_viewForState;
@property(nonatomic) _Bool wasTriggeredByUser; // @synthesize wasTriggeredByUser=_wasTriggeredByUser;
- (void)startAnimating;
- (void)stopAnimating;
- (void)triggerRefresh;
- (void)willMoveToSuperview:(id)arg1;

@end

