//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "TTransport.h"

@class NSMutableData, NSString;

@interface TMemoryBuffer : NSObject <TTransport>
{
    NSMutableData *mBuffer;
    unsigned long long mOffset;
}

- (void).cxx_destruct;
- (void)dealloc;
- (void)flush;
- (id)getBuffer;
- (id)init;
- (id)initWithData:(id)arg1;
- (unsigned long long)readAll:(char *)arg1 offset:(unsigned long long)arg2 length:(unsigned long long)arg3;
- (void)write:(const char *)arg1 offset:(unsigned long long)arg2 length:(unsigned long long)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

