//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITextView.h"

@class NSAttributedString, NSString, UIColor, UILabel;

@interface UITextView (Placeholder)
+ (id)defaultPlaceholderColor;
+ (void)load;
+ (id)observingKeys;
@property(retain, nonatomic) NSAttributedString *attributedPlaceholder;
- (_Bool)needsUpdateFont;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
@property(retain, nonatomic) NSString *placeholder;
@property(retain, nonatomic) UIColor *placeholderColor;
@property(readonly, nonatomic) UILabel *placeholderLabel;
- (void)setNeedsUpdateFont:(_Bool)arg1;
- (void)swizzledDealloc;
- (void)updatePlaceholderLabel;
@end

