//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface UIView (frameAdjust)
- (double)bottom;
- (long long)calculateDirectionFromTouches:(struct CGPoint)arg1;
- (double)height;
- (struct CGPoint)origin;
- (double)right;
- (void)setBottom:(double)arg1;
- (void)setHeight:(double)arg1;
- (void)setOrigin:(struct CGPoint)arg1;
- (void)setRight:(double)arg1;
- (void)setSize:(struct CGSize)arg1;
- (void)setTail:(double)arg1;
- (void)setWidth:(double)arg1;
- (void)setX:(double)arg1;
- (void)setY:(double)arg1;
- (struct CGSize)size;
- (double)tail;
- (double)width;
- (double)x;
- (double)y;
@end

