//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UMANBaseEvent.h"

@class NSMutableDictionary, NSString;

@interface UMADplus : UMANBaseEvent
{
    NSString *_id;
    NSMutableDictionary *_values;
    NSMutableDictionary *dplusDic;
}

+ (void)event:(id)arg1 attributes:(id)arg2;
+ (id)propertyFilter:(id)arg1;
+ (id)sharedInstance;
- (void).cxx_destruct;
- (void)clearSuperProperties;
@property(retain) NSMutableDictionary *dplusDic; // @synthesize dplusDic;
- (void)encodeWithCoder:(id)arg1;
- (id)getSuperProperties;
- (id)getSuperProperty:(id)arg1;
@property(copy, nonatomic) NSString *id; // @synthesize id=_id;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (void)outputUMLog;
- (void)registerSuperProperty:(id)arg1;
- (void)setFirstLaunchEvent:(id)arg1;
@property(retain, nonatomic) NSMutableDictionary *values; // @synthesize values=_values;
- (void)track:(id)arg1 property:(id)arg2;
- (void)unregisterSuperProperty:(id)arg1;

@end

