//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate, NSString;

@interface UMSocialLogMessage : NSObject
{
    NSString *_message;
    unsigned long long _level;
    unsigned long long _flag;
    long long _context;
    NSString *_file;
    NSString *_fileName;
    NSString *_function;
    unsigned long long _line;
    id _tag;
    long long _options;
    NSDate *_timestamp;
    NSString *_threadID;
    NSString *_threadName;
    NSString *_queueLabel;
}

- (void).cxx_destruct;
@property(nonatomic) long long context; // @synthesize context=_context;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(retain, nonatomic) NSString *file; // @synthesize file=_file;
@property(retain, nonatomic) NSString *fileName; // @synthesize fileName=_fileName;
@property(nonatomic) unsigned long long flag; // @synthesize flag=_flag;
@property(retain, nonatomic) NSString *function; // @synthesize function=_function;
- (id)initWithMessage:(id)arg1 level:(unsigned long long)arg2 flag:(unsigned long long)arg3 context:(long long)arg4 file:(id)arg5 function:(id)arg6 line:(unsigned long long)arg7 tag:(id)arg8 options:(long long)arg9 timestamp:(id)arg10;
@property(nonatomic) unsigned long long level; // @synthesize level=_level;
@property(nonatomic) unsigned long long line; // @synthesize line=_line;
@property(retain, nonatomic) NSString *message; // @synthesize message=_message;
@property(nonatomic) long long options; // @synthesize options=_options;
@property(retain, nonatomic) NSString *queueLabel; // @synthesize queueLabel=_queueLabel;
@property(retain, nonatomic) id tag; // @synthesize tag=_tag;
@property(retain, nonatomic) NSString *threadID; // @synthesize threadID=_threadID;
@property(retain, nonatomic) NSString *threadName; // @synthesize threadName=_threadName;
@property(retain, nonatomic) NSDate *timestamp; // @synthesize timestamp=_timestamp;

@end

