//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, UIImage;

@interface UMSocialItemInfo : NSObject
{
    NSString *_itemImageName;
    NSString *_itemName;
    UIImage *_itemImageIcon;
    long long _platformType;
    double _itemWidth;
    double _itemHeight;
}

- (void).cxx_destruct;
@property(nonatomic) double itemHeight; // @synthesize itemHeight=_itemHeight;
@property(retain, nonatomic) UIImage *itemImageIcon; // @synthesize itemImageIcon=_itemImageIcon;
@property(retain, nonatomic) NSString *itemImageName; // @synthesize itemImageName=_itemImageName;
@property(retain, nonatomic) NSString *itemName; // @synthesize itemName=_itemName;
@property(nonatomic) double itemWidth; // @synthesize itemWidth=_itemWidth;
@property(nonatomic) long long platformType; // @synthesize platformType=_platformType;

@end

