//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDateFormatter, NSMutableDictionary, NSMutableSet, NSString;

@interface UMSocialComFMDatabase : NSObject
{
    void *_db;
    NSString *_databasePath;
    _Bool _logsErrors;
    _Bool _crashOnErrors;
    _Bool _traceExecution;
    _Bool _checkedOut;
    _Bool _shouldCacheStatements;
    _Bool _isExecutingStatement;
    _Bool _inTransaction;
    double _maxBusyRetryTimeInterval;
    double _startBusyRetryTime;
    NSMutableDictionary *_cachedStatements;
    NSMutableSet *_openResultSets;
    NSMutableSet *_openFunctions;
    NSDateFormatter *_dateFormat;
}

+ (id)databaseWithPath:(id)arg1;
- (void).cxx_destruct;
- (_Bool)beginDeferredTransaction;
- (_Bool)beginTransaction;
- (void)bindObject:(id)arg1 toColumn:(int)arg2 inStatement:(struct sqlite3_stmt *)arg3;
- (int)busyRetryTimeout;
- (id)cachedStatementForQuery:(id)arg1;
@property(retain) NSMutableDictionary *cachedStatements; // @synthesize cachedStatements=_cachedStatements;
@property _Bool checkedOut; // @synthesize checkedOut=_checkedOut;
- (void)clearCachedStatements;
- (_Bool)close;
- (void)closeOpenResultSets;
- (_Bool)commit;
@property _Bool crashOnErrors; // @synthesize crashOnErrors=_crashOnErrors;
- (_Bool)databaseExists;
- (id)databasePath;
- (id)dateFromString:(id)arg1;
- (void)dealloc;
- (id)errorWithMessage:(id)arg1;
- (id)executeQuery:(id)arg1;
- (id)executeQuery:(id)arg1 values:(id)arg2 error:(id *)arg3;
- (id)executeQuery:(id)arg1 withArgumentsInArray:(id)arg2;
- (id)executeQuery:(id)arg1 withArgumentsInArray:(id)arg2 orDictionary:(id)arg3 orVAList:(char *)arg4;
- (id)executeQuery:(id)arg1 withParameterDictionary:(id)arg2;
- (id)executeQuery:(id)arg1 withVAList:(char *)arg2;
- (id)executeQueryWithFormat:(id)arg1;
- (_Bool)executeStatements:(id)arg1;
- (_Bool)executeStatements:(id)arg1 withResultBlock:(CDUnknownBlockType)arg2;
- (_Bool)executeUpdate:(id)arg1;
- (_Bool)executeUpdate:(id)arg1 error:(id *)arg2 withArgumentsInArray:(id)arg3 orDictionary:(id)arg4 orVAList:(char *)arg5;
- (_Bool)executeUpdate:(id)arg1 values:(id)arg2 error:(id *)arg3;
- (_Bool)executeUpdate:(id)arg1 withArgumentsInArray:(id)arg2;
- (_Bool)executeUpdate:(id)arg1 withErrorAndBindings:(id *)arg2;
- (_Bool)executeUpdate:(id)arg1 withParameterDictionary:(id)arg2;
- (_Bool)executeUpdate:(id)arg1 withVAList:(char *)arg2;
- (_Bool)executeUpdateWithFormat:(id)arg1;
- (void)extractSQL:(id)arg1 argumentsList:(char *)arg2 intoString:(id)arg3 arguments:(id)arg4;
- (void)finalize;
- (_Bool)hadError;
- (_Bool)hasDateFormatter;
- (_Bool)hasOpenResultSets;
- (_Bool)inTransaction;
- (id)init;
- (id)initWithPath:(id)arg1;
- (id)lastError;
- (int)lastErrorCode;
- (id)lastErrorMessage;
@property _Bool logsErrors; // @synthesize logsErrors=_logsErrors;
- (void)makeFunctionNamed:(id)arg1 maximumArguments:(int)arg2 withBlock:(CDUnknownBlockType)arg3;
- (double)maxBusyRetryTimeInterval;
- (_Bool)open;
- (_Bool)openWithFlags:(int)arg1;
- (_Bool)openWithFlags:(int)arg1 vfs:(id)arg2;
- (void)resultSetDidClose:(id)arg1;
- (_Bool)rollback;
- (void)setBusyRetryTimeout:(int)arg1;
- (void)setCachedStatement:(id)arg1 forQuery:(id)arg2;
- (void)setDateFormat:(id)arg1;
- (void)setMaxBusyRetryTimeInterval:(double)arg1;
- (void)setShouldCacheStatements:(_Bool)arg1;
@property _Bool traceExecution; // @synthesize traceExecution=_traceExecution;
- (_Bool)shouldCacheStatements;
- (void *)sqliteHandle;
- (const char *)sqlitePath;
- (id)stringFromDate:(id)arg1;
- (void)warnInUse;

@end

