//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

@interface UMSocialDataManager : NSObject
{
    NSMutableDictionary *_allAuthorUserInfo;
}

+ (id)defaultManager;
- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableDictionary *allAuthorUserInfo; // @synthesize allAuthorUserInfo=_allAuthorUserInfo;
- (void)clearAllAuthorUserInfo;
- (void)deleteAuthorUserInfoFilePath;
- (void)deleteAuthorUserInfoWithPlatform:(long long)arg1;
- (id)getAuthorUserInfoWithPlatform:(long long)arg1;
- (_Bool)isAuth:(long long)arg1;
- (_Bool)isExpireDateWithDate:(id)arg1;
- (id)platformKeyWithPlatformType:(long long)arg1;
- (long long)platformTypeWithPlatformKey:(id)arg1;
- (void)saveAuthorUserInfo;
- (void)setAuthorUserInfo:(id)arg1 platform:(long long)arg2;

@end

