//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UILabel.h"

@interface UMSocialShareTitleView : UILabel
{
    unsigned long long _verticalAlignment;
}

- (void)configShareTitleView;
- (void)dealloc;
- (void)drawTextInRect:(struct CGRect)arg1;
- (struct CGSize)getShareTitleViewSize;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic) unsigned long long verticalAlignment; // @synthesize verticalAlignment=_verticalAlignment;
- (struct CGRect)textRectForBounds:(struct CGRect)arg1 limitedToNumberOfLines:(long long)arg2;

@end

