//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIColor, UMSocialGradientView, UMSocialShareCancelControl, UMSocialSharePageControl, UMSocialSharePageScrollView, UMSocialShareTitleView;

@interface UMSocialShareContainer : UIView
{
    unsigned long long _sharePostionType;
    _Bool _isShareContainerHaveGradient;
    UIView *_rootView;
    UMSocialShareTitleView *_shareTitleView;
    UMSocialSharePageScrollView *_sharePageScrollView;
    UMSocialSharePageControl *_sharePageControl;
    UMSocialShareCancelControl *_shareCancelControl;
    UMSocialGradientView *_shareLeftGradientView;
    UMSocialGradientView *_shareRightGradientView;
    id <UMSocialHandlePlatformTypeDelegate> _handlePlatformTypeDelegate;
    double _shareContainerMarginLeft;
    double _shareContainerMarginRight;
    double _shareContainerMarginTop;
    double _shareContainerMarginBottom;
    double _shareContainerCornerRadius;
    UIColor *_shareContainerGradientStartColor;
    UIColor *_shareContainerGradientEndColor;
    double _shareContainerGradientLeftWidth;
    double _shareContainerGradientRightWidth;
}

- (void).cxx_destruct;
- (void)addCustomPlatforms:(id)arg1 withCustomPlatformInfos:(id)arg2;
- (void)adjustRect;
- (void)configShareContainer;
- (void)creatShareScrollView;
- (void)creatShareTitleView;
- (void)createCancelControl;
- (void)createGradientView;
- (void)createPageControl;
- (void)createSubView;
- (void)dealloc;
@property(nonatomic) __weak id <UMSocialHandlePlatformTypeDelegate> handlePlatformTypeDelegate; // @synthesize handlePlatformTypeDelegate=_handlePlatformTypeDelegate;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic) _Bool isShareContainerHaveGradient; // @synthesize isShareContainerHaveGradient=_isShareContainerHaveGradient;
- (void)reset;
- (void)resetSelfFrame;
- (double)resetSubViewFrame;
@property(nonatomic) __weak UIView *rootView; // @synthesize rootView=_rootView;
- (void)setPlatformArray:(id)arg1;
@property(retain, nonatomic) UMSocialShareCancelControl *shareCancelControl; // @synthesize shareCancelControl=_shareCancelControl;
@property(nonatomic) double shareContainerCornerRadius; // @synthesize shareContainerCornerRadius=_shareContainerCornerRadius;
@property(retain, nonatomic) UIColor *shareContainerGradientEndColor; // @synthesize shareContainerGradientEndColor=_shareContainerGradientEndColor;
@property(nonatomic) double shareContainerGradientLeftWidth; // @synthesize shareContainerGradientLeftWidth=_shareContainerGradientLeftWidth;
@property(nonatomic) double shareContainerGradientRightWidth; // @synthesize shareContainerGradientRightWidth=_shareContainerGradientRightWidth;
@property(retain, nonatomic) UIColor *shareContainerGradientStartColor; // @synthesize shareContainerGradientStartColor=_shareContainerGradientStartColor;
@property(nonatomic) double shareContainerMarginBottom; // @synthesize shareContainerMarginBottom=_shareContainerMarginBottom;
@property(nonatomic) double shareContainerMarginLeft; // @synthesize shareContainerMarginLeft=_shareContainerMarginLeft;
@property(nonatomic) double shareContainerMarginRight; // @synthesize shareContainerMarginRight=_shareContainerMarginRight;
@property(nonatomic) double shareContainerMarginTop; // @synthesize shareContainerMarginTop=_shareContainerMarginTop;
@property(retain, nonatomic) UMSocialGradientView *shareLeftGradientView; // @synthesize shareLeftGradientView=_shareLeftGradientView;
@property(retain, nonatomic) UMSocialSharePageControl *sharePageControl; // @synthesize sharePageControl=_sharePageControl;
@property(retain, nonatomic) UMSocialSharePageScrollView *sharePageScrollView; // @synthesize sharePageScrollView=_sharePageScrollView;
@property(nonatomic) unsigned long long sharePostionType;
@property(retain, nonatomic) UMSocialGradientView *shareRightGradientView; // @synthesize shareRightGradientView=_shareRightGradientView;
@property(retain, nonatomic) UMSocialShareTitleView *shareTitleView; // @synthesize shareTitleView=_shareTitleView;

@end

