//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UMSocialHandlePlatformTypeDelegate.h"
#import "UMSocialShareCancelControlDelegate.h"
#import "UMSocialShareMenuViewDelegate.h"

@class NSMutableArray, NSString, UMSocialShareContainer;

@interface UMSocialSharePageGroupView : UIView <UMSocialHandlePlatformTypeDelegate, UMSocialShareCancelControlDelegate, UMSocialShareMenuViewDelegate>
{
    unsigned long long _sharePostionType;
    _Bool _isDestroyWhenHide;
    UMSocialShareContainer *_shareContainer;
    CDUnknownBlockType _shareSelectionBlock;
    id <UMSocialShareMenuViewDelegate> _shareMenuViewDelegate;
    id <UMSocialShareMenuViewInternalDelegate> _shareMenuViewInternalDelegate;
    UIView *_shareSuperView;
    UIView *_backgroundGrayView;
    NSMutableArray *_preDefinePlatforms;
    NSMutableArray *_customPlatforms;
    NSMutableArray *_customPlatformInfos;
    long long _curOrient;
    struct CGRect _preShareSuperViewBounds;
}

- (void).cxx_destruct;
- (void)addCustomPlatformWithoutFilted:(long long)arg1 withPlatformIcon:(id)arg2 withPlatformName:(id)arg3;
- (void)adjustFrame;
@property(retain, nonatomic) UIView *backgroundGrayView; // @synthesize backgroundGrayView=_backgroundGrayView;
- (long long)checkIndex:(long long)arg1;
- (void)configSharePageScrollView;
- (void)creatBackgroundGrayView;
- (void)createCustomPlatformArrrayAndPlatformInfo;
- (void)createShareContainer;
- (void)createSubView;
@property(nonatomic) long long curOrient; // @synthesize curOrient=_curOrient;
@property(retain, nonatomic) NSMutableArray *customPlatformInfos; // @synthesize customPlatformInfos=_customPlatformInfos;
@property(retain, nonatomic) NSMutableArray *customPlatforms; // @synthesize customPlatforms=_customPlatforms;
- (void)dealloc;
- (void)doRotateAction:(id)arg1;
- (void)getParentView;
- (void)handlePlatformType:(long long)arg1 withUserInfo:(id)arg2;
- (void)handleShareCancelControl;
- (void)hiddenShareMenuView;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
- (void)postSharePanelNotificationForStatisticsV2;
@property(retain, nonatomic) NSMutableArray *preDefinePlatforms; // @synthesize preDefinePlatforms=_preDefinePlatforms;
@property(nonatomic) struct CGRect preShareSuperViewBounds; // @synthesize preShareSuperViewBounds=_preShareSuperViewBounds;
- (void)regsiterObserver;
- (void)removeAllCustomPlatformWithoutFilted;
- (void)removeCustomPlatformWithoutFilted:(long long)arg1;
- (void)reset;
- (void)resetSelfFrame;
- (void)resetSubViewFrame;
- (void)setPlatformArray:(id)arg1;
@property(retain, nonatomic) UMSocialShareContainer *shareContainer; // @synthesize shareContainer=_shareContainer;
@property(nonatomic) __weak id <UMSocialShareMenuViewDelegate> shareMenuViewDelegate; // @synthesize shareMenuViewDelegate=_shareMenuViewDelegate;
@property(nonatomic) __weak id <UMSocialShareMenuViewInternalDelegate> shareMenuViewInternalDelegate; // @synthesize shareMenuViewInternalDelegate=_shareMenuViewInternalDelegate;
@property(nonatomic) unsigned long long sharePostionType;
@property(copy, nonatomic) CDUnknownBlockType shareSelectionBlock; // @synthesize shareSelectionBlock=_shareSelectionBlock;
@property(nonatomic) __weak UIView *shareSuperView; // @synthesize shareSuperView=_shareSuperView;
- (void)show;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

