//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSMutableString, NSString;

@interface UMSocialBaseEntity : NSObject
{
    NSString *_type;
    NSString *_entityKey;
    NSString *_uid;
    NSString *_appkey;
    NSMutableDictionary *_baseDic;
    NSString *_cuid;
    NSString *_wid;
    NSString *_sdkVersion;
    NSMutableString *_baseString;
    NSMutableString *_baseURLEncodeString;
}

- (void).cxx_destruct;
- (void)UMSocial_Init;
@property(copy, nonatomic) NSString *appkey; // @synthesize appkey=_appkey;
@property(retain, nonatomic) NSMutableDictionary *baseDic; // @synthesize baseDic=_baseDic;
@property(copy, nonatomic) NSMutableString *baseString; // @synthesize baseString=_baseString;
@property(copy, nonatomic) NSMutableString *baseURLEncodeString; // @synthesize baseURLEncodeString=_baseURLEncodeString;
@property(copy, nonatomic) NSString *cuid; // @synthesize cuid=_cuid;
@property(copy, nonatomic) NSString *entityKey; // @synthesize entityKey=_entityKey;
- (id)init;
@property(copy, nonatomic) NSString *sdkVersion; // @synthesize sdkVersion=_sdkVersion;
@property(copy, nonatomic) NSString *type; // @synthesize type=_type;
@property(copy, nonatomic) NSString *uid; // @synthesize uid=_uid;
@property(copy, nonatomic) NSString *wid; // @synthesize wid=_wid;
- (id)toDictionary;
- (id)toString;
- (id)toURLEncodeString;

@end

