//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSString;

@interface UMSocialMessageObject : NSObject
{
    NSString *_title;
    NSString *_text;
    id _shareObject;
    NSDictionary *_moreInfo;
}

+ (id)messageObject;
+ (id)messageObjectWithMediaObject:(id)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) NSDictionary *moreInfo; // @synthesize moreInfo=_moreInfo;
@property(retain, nonatomic) id shareObject; // @synthesize shareObject=_shareObject;
@property(copy, nonatomic) NSString *text; // @synthesize text=_text;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;

@end

