//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSOperation.h"

@class NSOperationQueue, NSRecursiveLock, NSURLRequest;

@interface UMSocialTaskOperation : NSOperation
{
    long long _state;
    NSURLRequest *_request;
    NSOperationQueue *_operationTaskQueue;
    id <UMSocialTaskOperationDelegate> _taskOperationDelegate;
    CDUnknownBlockType _dependencyTaskCompletionHandler;
    long long _tag;
    NSRecursiveLock *_lock;
}

+ (id)networkRequestThread;
+ (void)networkRequestThreadEntryPoint:(id)arg1;
- (void).cxx_destruct;
- (void)cancel;
- (void)cancelConnection;
- (void)dealloc;
@property(copy, nonatomic) CDUnknownBlockType dependencyTaskCompletionHandler; // @synthesize dependencyTaskCompletionHandler=_dependencyTaskCompletionHandler;
- (void)finish;
- (id)init;
- (id)initWithRequest:(id)arg1;
- (_Bool)isAsynchronous;
- (_Bool)isCancelled;
- (_Bool)isConcurrent;
- (_Bool)isExecuting;
- (_Bool)isFinished;
- (_Bool)isReady;
@property(retain, nonatomic) NSRecursiveLock *lock; // @synthesize lock=_lock;
- (void)operationDidStart;
@property(nonatomic) __weak NSOperationQueue *operationTaskQueue; // @synthesize operationTaskQueue=_operationTaskQueue;
@property(retain, nonatomic) NSURLRequest *request; // @synthesize request=_request;
@property(nonatomic) long long state; // @synthesize state=_state;
@property(nonatomic) long long tag; // @synthesize tag=_tag;
@property(nonatomic) __weak id <UMSocialTaskOperationDelegate> taskOperationDelegate; // @synthesize taskOperationDelegate=_taskOperationDelegate;
- (void)start;

@end

