//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, UTTracker;

@interface UTAnalytics : NSObject
{
    UTTracker *mDefaultTracker;
    NSMutableDictionary *mTrackers;
}

+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)getInstance;
+ (void)setDailyEnvironment;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)getDefaultTracker;
- (id)getTracker:(id)arg1;
- (id)init;
- (void)loadConfigMgr;
- (void)onCrashHandler;
- (void)setAppKey:(id)arg1 secret:(id)arg2;
- (void)setAppKeyAndSecret;
- (void)setAppVersion:(id)arg1;
- (void)setChannel:(id)arg1;
- (void)setCrashCaughtListener:(id)arg1;
- (void)setRequestAuthentication:(id)arg1;
- (void)turnOffCrashHandler;
- (void)turnOnDebug;
- (void)turnOnDev;
- (void)updateSessionProperties:(id)arg1;
- (void)updateUserAccount:(id)arg1 userid:(id)arg2;
- (void)userRegister:(id)arg1;

@end

