//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface UTDLogUploadManager : NSObject
{
    _Bool isUploading;
    long long winSize;
    float averagePackageSize;
    struct dispatch_queue_s *_uploadQueue;
    struct dispatch_source_s *_timer;
    int _eidsLevel;
    int _eidsLevelAll;
    long long _uploadInterval;
}

+ (id)sharedInstance;
- (void)_runUploadTimerWithDelay:(unsigned long long)arg1 interval:(unsigned long long)arg2;
- (void)adjustWinSize:(int)arg1 bytes:(long long)arg2 usingTime:(float)arg3;
- (id)compressStreams:(id)arg1;
- (void)dealloc;
- (id)getEventIdsByLevel:(int)arg1;
- (id)getUploadUrlByLevel:(int)arg1;
- (id)gzipDeflate:(id)arg1;
- (id)init;
- (id)initPrivate;
- (id)matchStream:(id)arg1;
- (long long)mtu;
- (id)packageStreams:(id)arg1;
- (void)setUpdateTimer:(long long)arg1;
@property long long uploadInterval; // @synthesize uploadInterval=_uploadInterval;
- (void)startUploadLogic;
- (void)startUploadLogic:(id)arg1;
- (void)updateAllLevel;
- (void)updateTimerInterval:(id)arg1;
- (void)uploadLoop;
- (long long)winSize;

@end

