//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData, NSString;

@interface UTDLogObject : NSObject
{
    NSString *_eventID;
    NSString *_priority;
    NSData *_content;
    long long _time;
    unsigned long long _rowID;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSData *content; // @synthesize content=_content;
- (id)description;
@property(copy, nonatomic) NSString *eventID; // @synthesize eventID=_eventID;
@property(copy, nonatomic) NSString *priority; // @synthesize priority=_priority;
@property(readonly, nonatomic) unsigned long long rowID; // @synthesize rowID=_rowID;
- (void)setRowID2:(unsigned long long)arg1;
@property(nonatomic) long long time; // @synthesize time=_time;

@end

