//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSString;

@interface UTDSDKInfo : NSObject
{
    NSDictionary *_meta;
    _Bool _daily;
    _Bool _securitySign;
    NSString *_SDKVersion;
    NSString *_appKey;
    NSString *_appSecret;
    NSString *_debugID;
    NSString *_channel;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *SDKVersion; // @synthesize SDKVersion=_SDKVersion;
@property(retain, nonatomic) NSString *appKey; // @synthesize appKey=_appKey;
@property(retain, nonatomic) NSString *appSecret; // @synthesize appSecret=_appSecret;
@property(retain, nonatomic) NSString *channel; // @synthesize channel=_channel;
@property(nonatomic) _Bool daily; // @synthesize daily=_daily;
@property(retain, nonatomic) NSString *debugID; // @synthesize debugID=_debugID;
- (id)globalReserves;
@property(readonly, nonatomic) NSDictionary *meta;
@property(nonatomic) _Bool securitySign; // @synthesize securitySign=_securitySign;
- (void)setAppKey:(id)arg1 setAppSecret:(id)arg2;

@end

