//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface UTDUtils : NSObject
{
}

+ (id)NSData2Base64:(id)arg1;
+ (id)convertUrlEncodeFormat:(id)arg1;
+ (id)encodeURL:(id)arg1;
+ (id)getDictDescribe:(id)arg1 urlendcode:(_Bool)arg2;
+ (_Bool)isEmpty:(id)arg1;
+ (_Bool)isSuccessResponse:(id)arg1;
+ (id)md5ForData:(id)arg1;
+ (id)md5StrForData:(id)arg1;
+ (id)md5StrForNSString:(id)arg1;
+ (long long)millseconds;
+ (char *)newBase64Encode:(const void *)arg1:(unsigned long long)arg2:(_Bool)arg3:(unsigned int *)arg4;
+ (unsigned int)nextInt;
+ (id)queryURLDictionaryUsingEncoding:(id)arg1 encodeing:(unsigned long long)arg2;
+ (id)rc4:(id)arg1 length:(unsigned long long)arg2;
+ (id)responseData:(id)arg1;
+ (id)sha1ForString:(id)arg1;
+ (id)sortNSArrayForNSString:(id)arg1 ascending:(_Bool)arg2;
+ (long long)timestamp;

@end

