//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSString, UTDDeviceInfo;

@interface UTMCGlobalVariables : NSObject
{
    _Bool mSyncOnlineConfStatus;
    int mUploadLag;
    NSString *mChannel;
    NSString *mLongNick;
    NSString *mNick;
    NSString *mUserId;
    NSString *mLongUserId;
    UTDDeviceInfo *mDeviceInfo;
    NSString *mDebugId;
    NSDictionary *mHostForEventidDict;
}

+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)getInstance;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)getMHostForEventidDict;
- (id)init;
@property(retain) NSString *mChannel; // @synthesize mChannel;
@property(retain) NSString *mDebugId; // @synthesize mDebugId;
@property(retain) UTDDeviceInfo *mDeviceInfo; // @synthesize mDeviceInfo;
@property(retain, nonatomic) NSDictionary *mHostForEventidDict; // @synthesize mHostForEventidDict;
@property(retain) NSString *mLongNick; // @synthesize mLongNick;
@property(retain) NSString *mLongUserId; // @synthesize mLongUserId;
@property(retain) NSString *mNick; // @synthesize mNick;
@property _Bool mSyncOnlineConfStatus; // @synthesize mSyncOnlineConfStatus;
@property int mUploadLag; // @synthesize mUploadLag;
@property(retain) NSString *mUserId; // @synthesize mUserId;

@end

