//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIScrollView.h"

@class NSArray, NSCache, NSMutableArray, NSMutableDictionary, NSString;

@interface VTContentView : UIScrollView
{
    _Bool _needPreloading;
    id <VTContentViewDataSource> _dataSource;
    unsigned long long _pageCount;
    unsigned long long _currentPage;
    NSMutableDictionary *_visibleDict;
    NSMutableArray *_indexList;
    NSMutableArray *_frameList;
    NSString *_identifier;
    NSCache *_pageCache;
}

- (void).cxx_destruct;
- (void)clearMemoryCache;
- (id)creatViewControllerAtPage:(unsigned long long)arg1;
@property(nonatomic) unsigned long long currentPage; // @synthesize currentPage=_currentPage;
@property(nonatomic) __weak id <VTContentViewDataSource> dataSource; // @synthesize dataSource=_dataSource;
- (void)dealloc;
- (id)dequeueReusablePageWithIdentifier:(id)arg1;
@property(retain, nonatomic) NSMutableArray *frameList; // @synthesize frameList=_frameList;
- (struct CGRect)frameOfViewControllerAtPage:(unsigned long long)arg1;
@property(retain, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
@property(retain, nonatomic) NSMutableArray *indexList; // @synthesize indexList=_indexList;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
- (id)loadViewControllerAtIndexPath:(id)arg1;
- (void)moveViewControllerToCache:(id)arg1;
@property(nonatomic) _Bool needPreloading; // @synthesize needPreloading=_needPreloading;
@property(retain, nonatomic) NSCache *pageCache; // @synthesize pageCache=_pageCache;
@property(nonatomic) unsigned long long pageCount; // @synthesize pageCount=_pageCount;
- (long long)pageIndexForViewController:(id)arg1;
- (void)reloadData;
- (void)resetCacheData;
- (void)resetPageFrames;
@property(retain, nonatomic) NSMutableDictionary *visibleDict; // @synthesize visibleDict=_visibleDict;
- (id)viewControllerAtPage:(unsigned long long)arg1;
- (id)viewControllerAtPage:(unsigned long long)arg1 autoCreate:(_Bool)arg2;
@property(readonly, nonatomic) NSArray *visibleList;

@end

