//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UIViewController, VTMagicView;

@protocol VTMagicProtocol <NSObject>
- (unsigned long long)appearanceState;
- (long long)currentPage;
- (UIViewController *)currentViewController;
- (void)setCurrentPage:(long long)arg1;
- (void)setCurrentViewController:(UIViewController *)arg1;

@optional
- (VTMagicView *)magicView;
@end

