//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface WatchExchangeInterface : NSObject
{
}

+ (id)shareInstance;
- (void)disposeWatchKitVideo:(id)arg1;
- (void)disposeWatchKitVoice:(id)arg1 replyBlock:(CDUnknownBlockType)arg2;
- (void)watchKitHandlerWithRequest:(id)arg1 reply:(CDUnknownBlockType)arg2;

@end

