//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface WKAbnormalModel : NSObject
{
    NSString *_info;
    NSString *_url;
    NSString *_info_switch;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *info; // @synthesize info=_info;
@property(retain, nonatomic) NSString *info_switch; // @synthesize info_switch=_info_switch;
- (void)pushWebView;
@property(retain, nonatomic) NSString *url; // @synthesize url=_url;

@end

