//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSArray;

@interface WKBannerBottomGuideView : UIView
{
    NSArray *_models;
}

- (void).cxx_destruct;
- (void)buildButtons;
- (void)buttonViewClick:(id)arg1;
@property(retain, nonatomic) NSArray *models; // @synthesize models=_models;

@end

