//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@class NSString, UIImageView;

@interface WKButton : UIButton
{
    UIImageView *imageView;
    NSString *_url;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView;
- (id)initWithFrame:(struct CGRect)arg1;
@property(retain, nonatomic) NSString *url; // @synthesize url=_url;

@end

