//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WKBaseSubFirstViewController.h"

@class NSArray, NSTimer, UIView, WKWebInstallListViewController;

@interface WKCategoryViewController : WKBaseSubFirstViewController
{
    NSArray *_dataSource;
    NSTimer *_timer;
    long long _clickCount;
    UIView *_mobBannerView;
    WKWebInstallListViewController *_webInstallListVc;
}

- (void).cxx_destruct;
- (void)beginRequestApi;
- (void)categoryButtonClicked:(id)arg1;
@property(nonatomic) long long clickCount; // @synthesize clickCount=_clickCount;
@property(retain, nonatomic) NSArray *dataSource; // @synthesize dataSource=_dataSource;
- (void)initBannerAdView;
- (void)initCategoryButton;
@property(retain, nonatomic) UIView *mobBannerView; // @synthesize mobBannerView=_mobBannerView;
- (void)resetCounter;
@property(retain, nonatomic) NSTimer *timer; // @synthesize timer=_timer;
@property(retain, nonatomic) WKWebInstallListViewController *webInstallListVc; // @synthesize webInstallListVc=_webInstallListVc;
- (void)startTimer:(double)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;

@end

