//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface WKCIBNVipModel : NSObject
{
    _Bool _isVideoAuthed;
    unsigned long long _status;
}

- (void)addStatus:(unsigned long long)arg1;
@property(nonatomic) _Bool isVideoAuthed; // @synthesize isVideoAuthed=_isVideoAuthed;
@property(nonatomic) unsigned long long status; // @synthesize status=_status;

@end

