//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WKBaseSubViewController.h"

#import "CIBNEpisodeCellDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "WKCIBNVideoDetailBannerViewDelegate.h"
#import "WKNavigationControllerDelegate.h"

@class CIBNPurchaseWebViewController, NSMutableDictionary, NSString, UITableView, WKCIBNVideoAuthModel, WKCIBNVideoDetailBannerView, WKCIBNVideoDetailModel, WKCIBNVipModel;

@interface WKCIBNVipVideoDetailViewController : WKBaseSubViewController <WKCIBNVideoDetailBannerViewDelegate, UITableViewDataSource, UITableViewDelegate, WKNavigationControllerDelegate, CIBNEpisodeCellDelegate>
{
    NSString *_cibnVideoID;
    WKCIBNVideoDetailModel *_detailModel;
    WKCIBNVideoDetailBannerView *_bannerView;
    WKCIBNVideoAuthModel *_videoAuthModel;
    WKCIBNVipModel *_vipModel;
    NSMutableDictionary *_modelDatasourceMapper;
    UITableView *_tableView;
    CIBNPurchaseWebViewController *_purchaseWebView;
}

- (void).cxx_destruct;
- (void)CIBNVideoAuth;
- (void)allEpisodeBtnDidClicked:(id)arg1;
@property(retain, nonatomic) WKCIBNVideoDetailBannerView *bannerView; // @synthesize bannerView=_bannerView;
@property(copy, nonatomic) NSString *cibnVideoID; // @synthesize cibnVideoID=_cibnVideoID;
- (void)dealloc;
@property(retain, nonatomic) WKCIBNVideoDetailModel *detailModel; // @synthesize detailModel=_detailModel;
- (void)episodeCellDidClicked:(id)arg1;
- (void)getVideoDetailFromNetwork;
- (void)hideBottomLine;
- (void)hideLoadingPage;
@property(retain, nonatomic) NSMutableDictionary *modelDatasourceMapper; // @synthesize modelDatasourceMapper=_modelDatasourceMapper;
- (void)onBannerViewLeftButtonClicked;
- (void)onBannerViewRightButtonClicked;
- (void)paySuccessNotification:(id)arg1;
- (long long)preferredStatusBarStyle;
@property(nonatomic) __weak CIBNPurchaseWebViewController *purchaseWebView; // @synthesize purchaseWebView=_purchaseWebView;
- (void)reqTrailOrPlayWithCIBNCode:(id)arg1 programCode:(id)arg2;
- (void)requestBuy;
- (void)scrollViewDidScroll:(id)arg1;
- (void)sendM3U8FileUrl:(id)arg1 trailTime:(id)arg2;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) WKCIBNVideoAuthModel *videoAuthModel; // @synthesize videoAuthModel=_videoAuthModel;
@property(retain, nonatomic) WKCIBNVipModel *vipModel; // @synthesize vipModel=_vipModel;
- (void)showErrorToastWithMsg:(id)arg1;
- (void)showLoadingPageIfNeed;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)updateUI;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

