//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@class NSTimer, WKBaseUILabel, WKCleanButtonLayer;

@interface WKCleanButton : UIButton
{
    int _value;
    _Bool _isAnmiation;
    NSTimer *_fallAnimationTimer;
    NSTimer *_raiseAnimationTimer;
    WKCleanButtonLayer *_cleanButtonLayer;
    WKBaseUILabel *_valueLabel;
    id <WKCleanButtonViewDelegate> _delegate;
}

- (void).cxx_destruct;
- (void)awakeFromNib;
- (void)changeToValue:(long long)arg1 fromDevice:(_Bool)arg2;
- (void)cleanButtonClicked;
- (void)dealloc;
@property(nonatomic) __weak id <WKCleanButtonViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)initButton;
- (void)layoutSubviews;
- (void)onRecvMemoryHeartBeat:(id)arg1;
- (void)raiseAnimation;
@property(retain, nonatomic) WKBaseUILabel *valueLabel; // @synthesize valueLabel=_valueLabel;
- (void)startAnimation;
- (void)startCleanAnmiation;
- (void)stopAnimation;
- (void)swipeGesture:(id)arg1;

@end

