//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIButton, UIImageView, UILabel;

@interface WKConnectDeviceTipView : UIView
{
    UILabel *_titleLbl;
    UILabel *_descLbl;
    UIImageView *_deviceImgV;
    UIButton *_rightBtn;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UILabel *descLbl; // @synthesize descLbl=_descLbl;
@property(retain, nonatomic) UIImageView *deviceImgV; // @synthesize deviceImgV=_deviceImgV;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)openSearchDevice;
@property(retain, nonatomic) UIButton *rightBtn; // @synthesize rightBtn=_rightBtn;
@property(retain, nonatomic) UILabel *titleLbl; // @synthesize titleLbl=_titleLbl;
- (void)showConnectedState:(_Bool)arg1;

@end

