//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WKBaseSubViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSMutableArray, NSString, UIButton, UILabel, UITableView, UITableViewCell, WKAllChildCommentModel, WKReplyInputView;

@interface WKCommentsViewController : WKBaseSubViewController <UITableViewDelegate, UITableViewDataSource>
{
    long long loadAllSection;
    _Bool _isZan;
    NSString *_wkid;
    NSString *_cid;
    UITableView *_tvMain;
    WKAllChildCommentModel *_childCommentModel;
    UIButton *_bgBtn;
    WKReplyInputView *_replyInputView;
    UITableViewCell *_loadAllCell;
    UILabel *_loadAllLbl;
    NSMutableArray *_dianZanArr;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIButton *bgBtn; // @synthesize bgBtn=_bgBtn;
- (void)buildUI;
- (void)cancelDianzan:(id)arg1;
- (void)cancelInput;
@property(retain, nonatomic) WKAllChildCommentModel *childCommentModel; // @synthesize childCommentModel=_childCommentModel;
@property(retain, nonatomic) NSString *cid; // @synthesize cid=_cid;
- (void)dealloc;
- (void)dianZan:(id)arg1;
@property(retain, nonatomic) NSMutableArray *dianZanArr; // @synthesize dianZanArr=_dianZanArr;
- (void)footerRereshing;
@property(nonatomic) _Bool isZan; // @synthesize isZan=_isZan;
@property(retain, nonatomic) UITableViewCell *loadAllCell; // @synthesize loadAllCell=_loadAllCell;
@property(nonatomic) __weak UILabel *loadAllLbl; // @synthesize loadAllLbl=_loadAllLbl;
- (void)loadData;
- (long long)numberOfSectionsInTableView:(id)arg1;
@property(retain, nonatomic) WKReplyInputView *replyInputView; // @synthesize replyInputView=_replyInputView;
- (void)requestCommentWithId:(id)arg1 comment:(id)arg2;
- (void)sendCommentRequestCommentId:(id)arg1 comment:(id)arg2;
@property(nonatomic) __weak UITableView *tvMain; // @synthesize tvMain=_tvMain;
@property(retain, nonatomic) NSString *wkid; // @synthesize wkid=_wkid;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

