//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WKBaseSubViewController.h"

#import "UISearchBarDelegate.h"

@class NSLayoutConstraint, NSString, PingNetView, UIButton, UISearchBar, UISwitch, UITextView, UIView;

@interface WKDebugViewController : WKBaseSubViewController <UISearchBarDelegate>
{
    NSLayoutConstraint *_infoTextViewHeightConstraint;
    UISearchBar *_searchBar;
    UITextView *_infoTextView;
    UISwitch *_ignoreNetworkCacheSwitcher;
    UISwitch *_useTestAPISwitcher;
    UISwitch *_loadTestJSPatchSwitcher;
    UIView *_useTestApiSwitchContainerView;
    UIView *_ignoreNetworkCacheSwitchContainerView;
    UIView *_loadTestJSPatchContainerView;
    UIButton *_pingButton;
    PingNetView *_pingnetView;
    UIView *_pingnetWrapView;
}

- (void).cxx_destruct;
- (void)disposeDebugInfo;
- (void)getGradleInfo;
@property(nonatomic) __weak UIView *ignoreNetworkCacheSwitchContainerView; // @synthesize ignoreNetworkCacheSwitchContainerView=_ignoreNetworkCacheSwitchContainerView;
@property(nonatomic) __weak UISwitch *ignoreNetworkCacheSwitcher; // @synthesize ignoreNetworkCacheSwitcher=_ignoreNetworkCacheSwitcher;
@property(nonatomic) __weak UITextView *infoTextView; // @synthesize infoTextView=_infoTextView;
@property(nonatomic) __weak NSLayoutConstraint *infoTextViewHeightConstraint; // @synthesize infoTextViewHeightConstraint=_infoTextViewHeightConstraint;
- (_Bool)isAdHoc;
@property(nonatomic) __weak UIView *loadTestJSPatchContainerView; // @synthesize loadTestJSPatchContainerView=_loadTestJSPatchContainerView;
@property(nonatomic) __weak UISwitch *loadTestJSPatchSwitcher; // @synthesize loadTestJSPatchSwitcher=_loadTestJSPatchSwitcher;
- (void)openButtonClick:(id)arg1;
- (void)openWebViewWithUrlStr:(id)arg1;
@property(nonatomic) __weak UIButton *pingButton; // @synthesize pingButton=_pingButton;
- (void)pingButtonAction:(id)arg1;
- (void)pingNetWrapViewTap;
@property(retain, nonatomic) PingNetView *pingnetView; // @synthesize pingnetView=_pingnetView;
@property(retain, nonatomic) UIView *pingnetWrapView; // @synthesize pingnetWrapView=_pingnetWrapView;
@property(nonatomic) __weak UISearchBar *searchBar; // @synthesize searchBar=_searchBar;
- (void)searchBar:(id)arg1 textDidChange:(id)arg2;
- (void)searchBarSearchButtonClicked:(id)arg1;
@property(nonatomic) __weak UISwitch *useTestAPISwitcher; // @synthesize useTestAPISwitcher=_useTestAPISwitcher;
@property(nonatomic) __weak UIView *useTestApiSwitchContainerView; // @synthesize useTestApiSwitchContainerView=_useTestApiSwitchContainerView;
- (void)showToastForSwitch:(_Bool)arg1;
- (void)toggleIgnoreNetworkCache:(id)arg1;
- (void)toggleLoadTestJSPatchBundle:(id)arg1;
- (void)toggleTestAPI:(id)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

