//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WKBaseControlView.h"

@class NSTimer, UIButton, UIImageView, UILongPressGestureRecognizer;

@interface WKDirectionView : WKBaseControlView
{
    UILongPressGestureRecognizer *_lastGesture;
    NSTimer *_longPressTimer;
    UIImageView *_backgroundView;
    UIButton *_upButton;
    UIButton *_downButton;
    UIButton *_leftButton;
    UIButton *_rightButton;
    UIButton *_centerButton;
}

- (void).cxx_destruct;
- (void)awakeFromNib;
- (void)backgroundImageViewLongPressGestureAction:(id)arg1;
@property(nonatomic) __weak UIImageView *backgroundView; // @synthesize backgroundView=_backgroundView;
- (void)buttonTouchCancel:(id)arg1;
@property(nonatomic) __weak UIButton *centerButton; // @synthesize centerButton=_centerButton;
- (void)dealloc;
- (void)displayKeyCodeImageHover:(long long)arg1;
@property(nonatomic) __weak UIButton *downButton; // @synthesize downButton=_downButton;
- (void)drawRect:(struct CGRect)arg1;
- (long long)getDirectWithPoint:(struct CGPoint)arg1;
- (_Bool)isDownButtonTap:(struct CGPoint)arg1;
- (_Bool)isLeftButtonTap:(struct CGPoint)arg1;
- (_Bool)isRightButtonTap:(struct CGPoint)arg1;
- (_Bool)isUpButtonTap:(struct CGPoint)arg1;
- (void)keyCodeAction:(id)arg1;
- (void)keyCodeActionDragOutside:(id)arg1;
- (void)keyCodeTouchDown:(id)arg1;
@property(nonatomic) __weak UIButton *leftButton; // @synthesize leftButton=_leftButton;
- (void)longPressGestureAction:(id)arg1;
@property(retain, nonatomic) NSTimer *longPressTimer; // @synthesize longPressTimer=_longPressTimer;
- (void)onRecvHdLiveStart;
- (void)onRecvHdLiveStop;
- (_Bool)pointInTriangle:(struct CGPoint)arg1 withv1:(struct CGPoint)arg2 withV2:(struct CGPoint)arg3 withV3:(struct CGPoint)arg4;
@property(nonatomic) __weak UIButton *rightButton; // @synthesize rightButton=_rightButton;
- (void)sendKeyCodeAction:(id)arg1;
@property(nonatomic) __weak UIButton *upButton; // @synthesize upButton=_upButton;
- (void)showHDliveTitle:(_Bool)arg1;
- (void)startLongPressTimer:(long long)arg1;
- (void)stopLongPressTimer:(int)arg1;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;

@end

