//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionView.h"

#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"
#import "UIGestureRecognizerDelegate.h"

@class AppViewCell, NSArray, NSString, NSTimer;

@interface WKFolderCollectionView : UICollectionView <UICollectionViewDataSource, UICollectionViewDelegate, UIGestureRecognizerDelegate>
{
    NSArray *_appDataSources;
    id <WKFolderCollectionViewDelegate> _hideDelegate;
    NSTimer *_cellTimer;
    AppViewCell *_currentCellView;
}

- (void).cxx_destruct;
- (void)cellTimeout:(id *)arg1;
@property(retain, nonatomic) NSTimer *cellTimer; // @synthesize cellTimer=_cellTimer;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
@property(retain, nonatomic) AppViewCell *currentCellView; // @synthesize currentCellView=_currentCellView;
- (void)handleLongPress:(id)arg1;
@property(nonatomic) __weak id <WKFolderCollectionViewDelegate> hideDelegate; // @synthesize hideDelegate=_hideDelegate;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1 collectionViewLayout:(id)arg2;
- (void)setCollectionViewDataSources:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

