//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIButton, UILabel;

@interface WKGlobalSearchNoResultView : UIView
{
    UIButton *_actionButton;
    UILabel *_tipsLabel;
}

- (void).cxx_destruct;
@property(nonatomic) __weak UIButton *actionButton; // @synthesize actionButton=_actionButton;
- (void)awakeFromNib;
@property(nonatomic) __weak UILabel *tipsLabel; // @synthesize tipsLabel=_tipsLabel;

@end

