//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class UIImageView, UILabel, WKHDLiveFindGirdViewModel;

@interface WKGridCollectionViewCell : UICollectionViewCell
{
    WKHDLiveFindGirdViewModel *_dataModel;
    UILabel *titleLabel;
    UILabel *subTitleLabel;
    UIImageView *iconImageView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIImageView *iconImageView; // @synthesize iconImageView;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
- (void)setFindHorizontalViewData:(id)arg1;
@property(retain, nonatomic) UILabel *subTitleLabel; // @synthesize subTitleLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel;

@end

