//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class CALayer;

@interface WKHDLiveFindOftenTableViewCell : UITableViewCell
{
    CALayer *_bottomLayer;
    id <WKHDLiveFindOftenTableViewCellDelegate> _delegate;
}

- (void).cxx_destruct;
- (void)awakeFromNib;
- (void)buttonAction:(id)arg1;
@property(nonatomic) __weak id <WKHDLiveFindOftenTableViewCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void)initBottomLayer;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)layoutSubviews;
- (void)setHDLiveDatasource:(id)arg1;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;

@end

