//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WKBaseSubFirstViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "WKtonightItemsTableviewcellDelegate.h"
#import "wktonightBannerClickedDelegate.h"

@class NSString, UITableView, WKHDLiveFindHeaderCollectionView, WKHDLiveFindModel;

@interface WKHDLiveFindViewController : WKBaseSubFirstViewController <UITableViewDelegate, UITableViewDataSource, wktonightBannerClickedDelegate, WKtonightItemsTableviewcellDelegate>
{
    _Bool _isFromNotify;
    _Bool _isFristIn;
    _Bool _isDataLoadFinish;
    NSString *_showid;
    WKHDLiveFindModel *_findViewModel;
    UITableView *_hdliveFindTableView;
    WKHDLiveFindHeaderCollectionView *_headerView;
}

- (void).cxx_destruct;
- (void)clieckAction:(id)arg1 cell:(id)arg2 itemView:(id)arg3;
- (void)dealloc;
@property(retain, nonatomic) WKHDLiveFindModel *findViewModel; // @synthesize findViewModel=_findViewModel;
- (void)getHDLiveFindData:(_Bool)arg1;
@property(retain, nonatomic) UITableView *hdliveFindTableView; // @synthesize hdliveFindTableView=_hdliveFindTableView;
@property(retain, nonatomic) WKHDLiveFindHeaderCollectionView *headerView; // @synthesize headerView=_headerView;
@property(nonatomic) _Bool isDataLoadFinish; // @synthesize isDataLoadFinish=_isDataLoadFinish;
@property(nonatomic) _Bool isFristIn; // @synthesize isFristIn=_isFristIn;
@property(nonatomic) _Bool isFromNotify; // @synthesize isFromNotify=_isFromNotify;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)scrollByRules;
- (void)scrollToCurrentTimeView;
- (void)scrollToShowid:(id)arg1;
@property(copy, nonatomic) NSString *showid; // @synthesize showid=_showid;
- (id)tableHearderView;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (void)tableViewScrollToIndex:(id)arg1;
- (id)tablefooterView;
- (void)tonightItemsTableViewCellClicked:(id)arg1 cell:(id)arg2 itemView:(id)arg3;
- (void)updateFindData;
- (void)updateHearder;
- (void)updateOftenDataDource;
- (void)updateTimeIcon;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)wktonightBannerClicked:(id)arg1 cell:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

