//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class UIImageView, UILabel;

@interface WKHDLiveFindHeaderCollectionViewCell : UICollectionViewCell
{
    UIImageView *_tvLogoImageView;
    UILabel *_tvNameLabel;
}

- (void).cxx_destruct;
- (void)awakeFromNib;
- (void)setModel:(id)arg1;
@property(nonatomic) __weak UIImageView *tvLogoImageView; // @synthesize tvLogoImageView=_tvLogoImageView;
@property(nonatomic) __weak UILabel *tvNameLabel; // @synthesize tvNameLabel=_tvNameLabel;

@end

