//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseViewController.h"

#import "VTMagicViewDataSource.h"
#import "VTMagicViewDelegate.h"

@class NSArray, NSString, VTMagicController, WKHDLiveFindViewController, WKHDLiveListViewController;

@interface WKHDLiveViewController : BaseViewController <VTMagicViewDelegate, VTMagicViewDataSource>
{
    WKHDLiveFindViewController *_findViewController;
    WKHDLiveListViewController *_listViewController;
    VTMagicController *_pagerController;
    NSArray *_jsonArray;
}

- (void).cxx_destruct;
@property(retain, nonatomic) WKHDLiveFindViewController *findViewController; // @synthesize findViewController=_findViewController;
@property(retain, nonatomic) NSArray *jsonArray; // @synthesize jsonArray=_jsonArray;
@property(retain, nonatomic) WKHDLiveListViewController *listViewController; // @synthesize listViewController=_listViewController;
- (id)magicView:(id)arg1 menuItemAtIndex:(unsigned long long)arg2;
- (id)magicView:(id)arg1 viewControllerAtPage:(unsigned long long)arg2;
- (id)menuTitlesForMagicView:(id)arg1;
@property(retain, nonatomic) VTMagicController *pagerController; // @synthesize pagerController=_pagerController;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

