//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WKBaseIdcPacket.h"

@interface WKHeartBeatPacket : WKBaseIdcPacket
{
    int _seq;
}

- (id)init;
- (void)param_decode:(id)arg1;
- (void)param_encode:(id)arg1;
- (int)param_length;
- (void)param_preEncode;
@property(nonatomic) int seq; // @synthesize seq=_seq;

@end

