//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "CustomIOSAlertViewDelegate.h"

@class CustomIOSAlertView, UIActivityIndicatorView;

@interface WKInstallingTVView : UIView <CustomIOSAlertViewDelegate>
{
    CustomIOSAlertView *_alertView;
    UIActivityIndicatorView *_activityIndicator;
}

+ (id)shareInstances;
- (void).cxx_destruct;
@property(retain, nonatomic) UIActivityIndicatorView *activityIndicator; // @synthesize activityIndicator=_activityIndicator;
@property(retain, nonatomic) CustomIOSAlertView *alertView; // @synthesize alertView=_alertView;
- (void)closeInstallingTVView;
- (id)createDemoView;
- (void)customIOS7dialogButtonTouchUpInside:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)showInstallingTVView;

@end

