//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@class NSTimer, UIColor;

@interface WKLoadingView : UIButton
{
    _Bool _isAnimating;
    double _lineWidth;
    UIColor *_lineColor;
    double _anglePer;
    NSTimer *_timer;
}

- (void).cxx_destruct;
@property(nonatomic) double anglePer; // @synthesize anglePer=_anglePer;
- (void)drawGradientInContext:(struct CGContext *)arg1 startingAngle:(float)arg2 endingAngle:(float)arg3 intRadius:(CDUnknownBlockType)arg4 outRadius:(CDUnknownBlockType)arg5 withGradientBlock:(CDUnknownBlockType)arg6 withSubdiv:(int)arg7 withCenter:(struct CGPoint)arg8 withScale:(float)arg9;
- (void)drawPathAnimation:(id)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(readonly, nonatomic) _Bool isAnimating; // @synthesize isAnimating=_isAnimating;
@property(retain, nonatomic) UIColor *lineColor; // @synthesize lineColor=_lineColor;
@property(nonatomic) double lineWidth; // @synthesize lineWidth=_lineWidth;
- (struct CGPoint)pointForTrapezoidWithAngle:(float)arg1 andRadius:(float)arg2 forCenter:(struct CGPoint)arg3;
- (void)setTheLineColor:(id)arg1;
@property(retain, nonatomic) NSTimer *timer; // @synthesize timer=_timer;
- (void)startAnimation;
- (void)startRotateAnimation;
- (void)stopAnimation;
- (void)stopRotateAnimation;

@end

