//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class BoardView, NSArray, WKAbnormalModel, WKHitTestWindow, WKMingPaiLabelView, WKPromotionModel;

@interface WKMingPaiTipsView : NSObject
{
    _Bool _isAnimation;
    WKHitTestWindow *_boardWindow;
    WKPromotionModel *_promotionModel;
    BoardView *_boardView;
    _Bool _running;
    WKMingPaiLabelView *mingPaiView;
    NSArray *promotionArray;
    WKAbnormalModel *abnormalModel;
    id <WKMingPaiTipsViewDelegate> _delegatge;
}

+ (id)defaultTipsView;
- (void).cxx_destruct;
@property(retain, nonatomic) WKAbnormalModel *abnormalModel; // @synthesize abnormalModel;
- (_Bool)checkOverFlowClickCount:(id)arg1;
@property(nonatomic) id <WKMingPaiTipsViewDelegate> delegatge; // @synthesize delegatge=_delegatge;
- (id)disposePromotionDataArray:(id)arg1;
- (id)getPromotionMingPaiID:(long long)arg1;
- (_Bool)hasMingPaiMsg;
- (void)hiddenMingPaiView;
- (id)init;
- (void)initBoardView;
- (void)initBoardWindow;
- (_Bool)isRunning;
- (void)mingPaiHidden;
- (void)mingPaiShown;
@property(retain, nonatomic) WKMingPaiLabelView *mingPaiView; // @synthesize mingPaiView;
- (void)mingPaiViewTap;
@property(retain, nonatomic) NSArray *promotionArray; // @synthesize promotionArray;
- (void)setMingPaiButtonForAbnormalMingPai;
- (void)setMingPaiButtonForPromotionMingPai;
- (void)setNoticeMessage;
- (void)showMingPaiView;
- (void)startRunning;
- (void)stopRunning;
- (void)tapGesHundel:(id)arg1;

@end

