//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseWebPageViewController.h"

@class NSString;

@interface WKModalWebViewController : BaseWebPageViewController
{
    NSString *_titleName;
}

- (void).cxx_destruct;
- (void)buildUI;
- (void)dismissView;
- (id)initWithUrl:(id)arg1 title:(id)arg2 fromPage:(id)arg3;
- (long long)preferredStatusBarStyle;
@property(retain, nonatomic) NSString *titleName; // @synthesize titleName=_titleName;
- (void)viewDidLoad;

@end

