//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WKBaseSubViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSMutableArray, NSString, UITableView;

@interface WKMyCollectViewController : WKBaseSubViewController <UITableViewDelegate, UITableViewDataSource>
{
    UITableView *_tvMain;
    NSMutableArray *_videoCollectArr;
}

- (void).cxx_destruct;
- (void)buildUI;
- (void)collectVideoRequest:(id)arg1;
- (void)loadData;
- (long long)numberOfSectionsInTableView:(id)arg1;
@property(nonatomic) __weak UITableView *tvMain; // @synthesize tvMain=_tvMain;
@property(retain, nonatomic) NSMutableArray *videoCollectArr; // @synthesize videoCollectArr=_videoCollectArr;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)tableView:(id)arg1 titleForDeleteConfirmationButtonForRowAtIndexPath:(id)arg2;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

