//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class NSLayoutConstraint, UIImageView, UILabel, UIView;

@interface WKMyCenterCell : UITableViewCell
{
    UIImageView *_iconV;
    UILabel *_titleLbl;
    UIView *_bottomLine;
    NSLayoutConstraint *_bottomLineLeft;
}

+ (id)myCenterCellWith:(id)arg1;
- (void).cxx_destruct;
- (void)awakeFromNib;
@property(nonatomic) __weak UIView *bottomLine; // @synthesize bottomLine=_bottomLine;
@property(nonatomic) __weak NSLayoutConstraint *bottomLineLeft; // @synthesize bottomLineLeft=_bottomLineLeft;
@property(nonatomic) __weak UIImageView *iconV; // @synthesize iconV=_iconV;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
@property(nonatomic) __weak UILabel *titleLbl; // @synthesize titleLbl=_titleLbl;

@end

