//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class GDTNativeAdData, UIImageView, UILabel;

@interface WKNativeAdView : UIView
{
    UIImageView *_adImageview;
    UIImageView *_iconImageVIew;
    UILabel *_nameLabel;
    UILabel *_desLabel;
    GDTNativeAdData *_adData;
}

- (void).cxx_destruct;
@property(retain, nonatomic) GDTNativeAdData *adData; // @synthesize adData=_adData;
@property(nonatomic) __weak UIImageView *adImageview; // @synthesize adImageview=_adImageview;
- (void)awakeFromNib;
@property(nonatomic) __weak UILabel *desLabel; // @synthesize desLabel=_desLabel;
@property(nonatomic) __weak UIImageView *iconImageVIew; // @synthesize iconImageVIew=_iconImageVIew;
@property(nonatomic) __weak UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
- (void)setData:(id)arg1;

@end

