//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@class WKPlayControlEpisodeModel, WKPlayControlModel, WKRoundView;

@interface WKRemotePlusButton : UIButton
{
    WKPlayControlEpisodeModel *_episodeModel;
    WKPlayControlModel *_playControlModel;
    WKRoundView *roundButton;
    id <WKRemotePlusButtonDelegate> _delegate;
}

- (void).cxx_destruct;
- (void)dealloc;
@property(nonatomic) __weak id <WKRemotePlusButtonDelegate> delegate; // @synthesize delegate=_delegate;
- (void)initRoundButton;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
- (void)longPressGesture:(id)arg1;
- (void)onRecvHeartBeatModel:(id)arg1;
- (void)onRecvHeartBeatStop:(id)arg1;
- (void)onRecvVideoControlErrorData:(id)arg1;
- (void)registerNotification;
@property(retain, nonatomic) WKRoundView *roundButton; // @synthesize roundButton;
- (void)setEpisodeData:(id)arg1;
- (void)tapPressGesture;

@end

