//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionReusableView.h"

@class CALayer;

@interface WKRecommendVideoFooterView : UICollectionReusableView
{
    _Bool _hiddenLine;
    CALayer *bottomLayer;
}

- (void).cxx_destruct;
@property(retain, nonatomic) CALayer *bottomLayer; // @synthesize bottomLayer;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic, getter=isHiddenLine) _Bool hiddenLine; // @synthesize hiddenLine=_hiddenLine;

@end

