//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSLayoutConstraint, UIButton, UILabel;

@interface WKSearchDeviceHelpView : UIView
{
    long long _status;
    UILabel *_tipsLabel;
    UIButton *_networkButton;
    UIButton *_buybuybuyButton;
    UIButton *_wifiConnectButton;
    NSLayoutConstraint *_networkButtonHeightConstraint;
}

- (void).cxx_destruct;
- (void)awakeFromNib;
@property(nonatomic) __weak UIButton *buybuybuyButton; // @synthesize buybuybuyButton=_buybuybuyButton;
- (void)buybuybuyButtonClick:(id)arg1;
- (void)changeStatusByStatus:(long long)arg1;
@property(nonatomic) __weak UIButton *networkButton; // @synthesize networkButton=_networkButton;
- (void)networkButtonClick:(id)arg1;
@property(nonatomic) __weak NSLayoutConstraint *networkButtonHeightConstraint; // @synthesize networkButtonHeightConstraint=_networkButtonHeightConstraint;
@property(nonatomic) __weak UILabel *tipsLabel; // @synthesize tipsLabel=_tipsLabel;
@property(nonatomic) __weak UIButton *wifiConnectButton; // @synthesize wifiConnectButton=_wifiConnectButton;
- (void)updateWiFiBtn;
- (void)wifiConnectButtonClicked:(id)arg1;

@end

