//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class CAShapeLayer, NSArray, NSString, NSTimer, UIButton, UIImageView, UITableView, UIView, WKSearchDeviceHelpView, WKWaterWaveDangYaDangView;

@interface WKSearchDevicesViewController : UIViewController <UITableViewDelegate, UITableViewDataSource>
{
    CAShapeLayer *_loadingLayer;
    long long _discoverRetryTime;
    WKSearchDeviceHelpView *_footerView;
    WKWaterWaveDangYaDangView *_bottomWaveView;
    _Bool _isTopInWindow;
    UIImageView *headerView;
    NSTimer *animationTimer;
    CAShapeLayer *shapeLayer;
    UIView *_searchDevicesBackgroundView;
    NSArray *_devicesArray;
    UIButton *_backButton;
    UIButton *_questionButton;
    UITableView *_devicesTableView;
    WKWaterWaveDangYaDangView *_findWifiImageView;
    NSString *_lastSSID;
}

- (void).cxx_destruct;
- (_Bool)adbConnectDevice:(id)arg1;
@property(nonatomic) __weak NSTimer *animationTimer; // @synthesize animationTimer;
- (void)appWillEnterBackground:(id)arg1;
- (void)appWillEnterForeground:(id)arg1;
@property(nonatomic) __weak UIButton *backButton; // @synthesize backButton=_backButton;
- (void)backButtonClick:(id)arg1;
- (void)changeCurrentDeivce:(id)arg1;
- (void)closeAdbConnect:(id)arg1;
- (void)configFindWifiImageView;
- (void)dealloc;
- (long long)deviceStatus;
@property(retain, nonatomic) NSArray *devicesArray; // @synthesize devicesArray=_devicesArray;
@property(nonatomic) __weak UITableView *devicesTableView; // @synthesize devicesTableView=_devicesTableView;
- (id)disposeNewDevice:(id)arg1;
@property(nonatomic) __weak WKWaterWaveDangYaDangView *findWifiImageView; // @synthesize findWifiImageView=_findWifiImageView;
@property(retain, nonatomic) UIImageView *headerView; // @synthesize headerView;
- (void)initPrivate;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (_Bool)installServerApk:(id)arg1;
@property(nonatomic) _Bool isTopInWindow; // @synthesize isTopInWindow=_isTopInWindow;
@property(copy, nonatomic) NSString *lastSSID; // @synthesize lastSSID=_lastSSID;
- (void)onDeviceDiscoverFinished;
- (void)onNetWrokChange:(id)arg1;
- (long long)preferredStatusBarStyle;
@property(nonatomic) __weak UIButton *questionButton; // @synthesize questionButton=_questionButton;
- (void)questionButtonClick:(id)arg1;
- (void)resetDeviceArray;
- (id)sameDevice:(id)arg1;
@property(nonatomic) __weak UIView *searchDevicesBackgroundView; // @synthesize searchDevicesBackgroundView=_searchDevicesBackgroundView;
- (void)searchDevicesIfNeed;
@property(retain, nonatomic) CAShapeLayer *shapeLayer; // @synthesize shapeLayer;
- (void)showInitDeviceFailure;
- (void)showInitDeviceSuccess;
- (void)startBottomWaveAnimation;
- (_Bool)startProxyActivity1:(id)arg1;
- (void)startScanDevices;
- (void)startWaterWaveAnimation;
- (void)stopScanDevices;
- (void)stopWaterWaveAnimation;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (void)updateSSIDTitle;
- (void)updateSubviewsConstraints;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)waterWaveAnimation;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

