//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WKBaseSubViewController.h"

@class NSArray, NSString, UITableView;

@interface WKSettingVideoSrcViewController : WKBaseSubViewController
{
    NSString *_titleName;
    NSArray *_itemArr;
    long long _originSelectedIndex;
    long long _srcType;
    CDUnknownBlockType _refreshTableViewBlock;
    UITableView *_tvMain;
    long long _selectedIndex;
}

- (void).cxx_destruct;
- (void)buildUI;
@property(retain, nonatomic) NSArray *itemArr; // @synthesize itemArr=_itemArr;
- (long long)numberOfSectionsInTableView:(id)arg1;
@property(nonatomic) long long originSelectedIndex; // @synthesize originSelectedIndex=_originSelectedIndex;
@property(copy, nonatomic) CDUnknownBlockType refreshTableViewBlock; // @synthesize refreshTableViewBlock=_refreshTableViewBlock;
@property(nonatomic) long long selectedIndex; // @synthesize selectedIndex=_selectedIndex;
@property(nonatomic) long long srcType; // @synthesize srcType=_srcType;
@property(retain, nonatomic) NSString *titleName; // @synthesize titleName=_titleName;
@property(nonatomic) __weak UITableView *tvMain; // @synthesize tvMain=_tvMain;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidLoad;

@end

