//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSOperation.h"

@class WKDeviceItem;

@interface WKTraverseProtocol : NSOperation
{
    WKDeviceItem *_device;
}

+ (id)findAllOf:(Class)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) WKDeviceItem *device; // @synthesize device=_device;
- (id)initWithDevice:(id)arg1;
- (void)main;
- (void)tryAllProtocolForControlDevices:(id)arg1;

@end

