//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class WKVideoNewCommentModel, WkVideoInfo;

@interface WkVideoCommentData : NSObject
{
    WKVideoNewCommentModel *_comment;
    WkVideoInfo *_detail;
}

- (void).cxx_destruct;
@property(retain, nonatomic) WKVideoNewCommentModel *comment; // @synthesize comment=_comment;
@property(retain, nonatomic) WkVideoInfo *detail; // @synthesize detail=_detail;

@end

