//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseViewController.h"

#import "VTMagicViewDataSource.h"
#import "VTMagicViewDelegate.h"

@class NSArray, NSMutableArray, NSString, VTMagicController, WKDianboChosenViewController, WKPushWebPageCollectionViewController, WKVideoCategoryViewController, WKViedoFindViewController;

@interface WKVideoViewController : BaseViewController <VTMagicViewDelegate, VTMagicViewDataSource>
{
    long long _currentPageIndex;
    NSString *_currentSrc;
    NSArray *_videoModelArray;
    NSMutableArray *_viewArray;
    NSString *_lastRequestHash;
    VTMagicController *_pagerController;
    WKDianboChosenViewController *_chosenVC;
    WKViedoFindViewController *_findViewVC;
    WKVideoCategoryViewController *_categoryVC;
    WKPushWebPageCollectionViewController *_pushwebPageVc;
}

- (void).cxx_destruct;
- (void)addSearchItems;
- (void)applicationWillEnterForegroundNotification:(id)arg1;
- (void)beginRequestApiWithLoadingAnimation:(_Bool)arg1;
@property(retain, nonatomic) WKVideoCategoryViewController *categoryVC; // @synthesize categoryVC=_categoryVC;
@property(retain, nonatomic) WKDianboChosenViewController *chosenVC; // @synthesize chosenVC=_chosenVC;
- (void)dealloc;
@property(retain, nonatomic) WKViedoFindViewController *findViewVC; // @synthesize findViewVC=_findViewVC;
@property(copy, nonatomic) NSString *lastRequestHash; // @synthesize lastRequestHash=_lastRequestHash;
- (void)magicView:(id)arg1 didSelectItemAtIndex:(unsigned long long)arg2;
- (id)magicView:(id)arg1 menuItemAtIndex:(unsigned long long)arg2;
- (id)magicView:(id)arg1 viewControllerAtPage:(unsigned long long)arg2;
- (id)menuTitlesForMagicView:(id)arg1;
@property(retain, nonatomic) VTMagicController *pagerController; // @synthesize pagerController=_pagerController;
@property(retain, nonatomic) WKPushWebPageCollectionViewController *pushwebPageVc; // @synthesize pushwebPageVc=_pushwebPageVc;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

