//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "WKVideoDetailBannerPlayToolsViewDelegate.h"

@class NSString, UIImageView, UILabel, WKVideoDetailBannerPlayToolsView, WKVideoDetailModel;

@interface WKVideoDetailBannerView : UIView <WKVideoDetailBannerPlayToolsViewDelegate>
{
    WKVideoDetailModel *_detailModel;
    UIImageView *bannerImageView;
    UILabel *videoTitleLabel;
    UILabel *directorLabel;
    UILabel *actorLabel;
    UILabel *yearLabel;
    UILabel *areaLabel;
    UILabel *feedbackLabel;
    WKVideoDetailBannerPlayToolsView *playToolsView;
    UIImageView *blurImageView;
    id <WKVideoDetailBannerViewDelegate> _delegate;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UILabel *actorLabel; // @synthesize actorLabel;
@property(retain, nonatomic) UILabel *areaLabel; // @synthesize areaLabel;
- (id)attributedString:(id)arg1;
@property(retain, nonatomic) UIImageView *bannerImageView; // @synthesize bannerImageView;
- (void)bannerImageViewLongClick:(id)arg1;
@property(retain, nonatomic) UIImageView *blurImageView; // @synthesize blurImageView;
- (void)dealloc;
@property(nonatomic) __weak id <WKVideoDetailBannerViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) UILabel *directorLabel; // @synthesize directorLabel;
- (void)disposeFeedbackLabel;
@property(retain, nonatomic) UILabel *feedbackLabel; // @synthesize feedbackLabel;
- (void)feedbackLabelTapGesture;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)onBannerViewPlayButtonClicked;
- (void)onBannerViewSourceButtonClicked;
@property(retain, nonatomic) WKVideoDetailBannerPlayToolsView *playToolsView; // @synthesize playToolsView;
- (void)setBannerViewDataSource:(id)arg1;
@property(retain, nonatomic) UILabel *videoTitleLabel; // @synthesize videoTitleLabel;
@property(retain, nonatomic) UILabel *yearLabel; // @synthesize yearLabel;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

