//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WKBaseSubViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "VideoHistoryTableViewCellDelegate.h"
#import "WKPlayHistoryTableHeaderViewDelegate.h"

@class NSArray, NSString, UITableView, WKPlayHistoryTableHeaderView;

@interface WKVideoPlayHistoryViewController : WKBaseSubViewController <UITableViewDataSource, UITableViewDelegate, WKPlayHistoryTableHeaderViewDelegate, VideoHistoryTableViewCellDelegate>
{
    UITableView *_historyTableview;
    NSArray *_hdliveHistroyArray;
    NSArray *_vodHistoryArray;
    WKPlayHistoryTableHeaderView *headerView;
}

- (void).cxx_destruct;
- (void)clearAllVodHistroy;
- (void)clearHistoryBtnClicked:(id)arg1;
- (void)getAllVodHistroy;
@property(retain, nonatomic) NSArray *hdliveHistroyArray; // @synthesize hdliveHistroyArray=_hdliveHistroyArray;
- (id)init;
- (void)initHistroyTable;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)onPlayHistroyTableHistoryHeaderViewDelegate:(long long)arg1;
- (void)setupTableHeaderView;
- (_Bool)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)tableView:(id)arg1 titleForDeleteConfirmationButtonForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (void)videoHistoryTableViewCellDidPlayButtonClick:(id)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)wkPlayHistoryfoldHeaderView:(double)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

