//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class FXBlurView, NSArray, UILabel, WKWaterWaveDangYaDangView;

@interface WKVoiceRecognView : UIView
{
    NSArray *_localTipsArray;
    NSArray *_onlineOperateTipsArray;
    NSArray *_onlineLiveTipsArray;
    NSArray *_onlineAppTipsArray;
    FXBlurView *visualEfView;
    id <WKVoiceRecognViewDelegate> _voiceViewDelegate;
    WKWaterWaveDangYaDangView *_voiceAnimationImageView;
    UILabel *_voiceTipsLabel;
    UILabel *_voiceCmdLabel;
}

- (void).cxx_destruct;
- (void)awakeFromNib;
- (void)changeStatus:(unsigned long long)arg1 withExecutingString:(id)arg2;
- (id)getVoiceRandomTip;
@property(retain, nonatomic) FXBlurView *visualEfView; // @synthesize visualEfView;
@property(nonatomic) __weak WKWaterWaveDangYaDangView *voiceAnimationImageView; // @synthesize voiceAnimationImageView=_voiceAnimationImageView;
@property(nonatomic) __weak UILabel *voiceCmdLabel; // @synthesize voiceCmdLabel=_voiceCmdLabel;
@property(nonatomic) __weak UILabel *voiceTipsLabel; // @synthesize voiceTipsLabel=_voiceTipsLabel;
@property(nonatomic) __weak id <WKVoiceRecognViewDelegate> voiceViewDelegate; // @synthesize voiceViewDelegate=_voiceViewDelegate;
- (void)tapHidden;
- (void)tipStringData;

@end

