//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WKBaseSubFirstViewController.h"

#import "UIScrollViewDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "WKAppTableViewCellOperationButtonClickDelegate.h"

@class NSMutableArray, NSString, UITableView;

@interface WKWebinstallTableViewController : WKBaseSubFirstViewController <UITableViewDataSource, UITableViewDelegate, UIScrollViewDelegate, WKAppTableViewCellOperationButtonClickDelegate>
{
    _Bool _alreadyRequest;
    _Bool _hasData;
    UITableView *_tableView;
    NSString *_appStoreBaseUrl;
    long long _pageIndex;
    NSMutableArray *_appDataSource;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool alreadyRequest; // @synthesize alreadyRequest=_alreadyRequest;
@property(retain, nonatomic) NSMutableArray *appDataSource; // @synthesize appDataSource=_appDataSource;
@property(retain, nonatomic) NSString *appStoreBaseUrl; // @synthesize appStoreBaseUrl=_appStoreBaseUrl;
- (void)beginRequsetApi:(long long)arg1 withLoadingAnimation:(_Bool)arg2;
- (void)dealloc;
- (void)footerRereshing;
@property(nonatomic) _Bool hasData; // @synthesize hasData=_hasData;
- (void)onAppTableViewCellOperationButtonClicked:(id)arg1;
@property(nonatomic) long long pageIndex; // @synthesize pageIndex=_pageIndex;
- (void)serverApplistArrived:(id)arg1;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
- (void)setupRefresh;
- (void)setupTableView;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)toDealDataArray:(id)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

