//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSTimer, WKDeviceItem;

@interface WKWeiJingInstallServer : NSObject
{
    WKDeviceItem *_device;
    NSTimer *_checkTimer;
    CDUnknownBlockType _block;
    long long _checkInstallIndex;
}

- (void).cxx_destruct;
- (void)checkInstallSuccess:(CDUnknownBlockType)arg1;
- (void)install:(CDUnknownBlockType)arg1;
- (void)installServer:(id)arg1 withResultBlock:(CDUnknownBlockType)arg2;
- (void)openServer:(id)arg1 withResultBlock:(CDUnknownBlockType)arg2;
- (void)startCheckInstallStatus;
- (void)startTimer;
- (void)stopTimer;

@end

