//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WKBaseSubViewController.h"

#import "UIScrollViewDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "WKAppTableViewCellOperationButtonClickDelegate.h"

@class NSMutableArray, NSString, UITableView;

@interface WKWebInstallListViewController : WKBaseSubViewController <WKAppTableViewCellOperationButtonClickDelegate, UITableViewDataSource, UITableViewDelegate, UIScrollViewDelegate>
{
    _Bool _hasData;
    UITableView *_tableViewList;
    unsigned long long _showTableType;
    NSMutableArray *appDataSourceArray;
    long long _categoryIndex;
    long long _pageIndex;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableArray *appDataSourceArray; // @synthesize appDataSourceArray;
- (void)beginRequsetApi:(long long)arg1 withAnimation:(_Bool)arg2;
@property long long categoryIndex; // @synthesize categoryIndex=_categoryIndex;
- (void)dealloc;
- (void)footerRereshing;
- (id)getRequestUrl:(long long)arg1;
- (void)initTableViewList;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2 withType:(unsigned long long)arg3;
- (void)onAppTableViewCellOperationButtonClicked:(id)arg1;
@property long long pageIndex; // @synthesize pageIndex=_pageIndex;
- (void)serverApplistArrived:(id)arg1;
- (void)setViewCtrTitle:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)toDealDataArray:(id)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)viewWillDisappear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

