//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UISearchBarDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSArray, NSString, UIButton, UISearchBar, UITableView;

@interface WKWebSearchHistoryHeaderView : UIView <UISearchBarDelegate, UITableViewDelegate, UITableViewDataSource>
{
    UIView *_topNavBarView;
    UISearchBar *_searchBar;
    UIButton *_cancelBtn;
    id <WKWebSearchHistoryHeaderViewDelegate> _delegate;
    UITableView *_tableView;
    NSArray *_histories;
}

- (void).cxx_destruct;
- (void)awakeFromNib;
@property(nonatomic) __weak UIButton *cancelBtn; // @synthesize cancelBtn=_cancelBtn;
- (void)cancelBtnClick:(id)arg1;
@property(nonatomic) __weak id <WKWebSearchHistoryHeaderViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)didMoveToSuperview;
@property(retain, nonatomic) NSArray *histories; // @synthesize histories=_histories;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)openWebPageAndSaveHistory:(id)arg1;
- (void)reloadWithHistories:(id)arg1;
@property(nonatomic) __weak UISearchBar *searchBar; // @synthesize searchBar=_searchBar;
- (void)searchBarSearchButtonClicked:(id)arg1;
@property(nonatomic) __weak UITableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) __weak UIView *topNavBarView; // @synthesize topNavBarView=_topNavBarView;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (double)viewHeightForHistories;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

