//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WKBaseProtocol.h"

@interface WKWeiXinHisenseProtocal : WKBaseProtocol
{
    CDUnknownBlockType _successBlock;
}

- (void).cxx_destruct;
- (void)autoInstallServerApp:(CDUnknownBlockType)arg1;
- (_Bool)canAutoInstallServer;
- (id)getHisenseKeyCodeStr:(int)arg1;
- (void)sendGetMessageToTVWith:(id)arg1 resultBlock:(CDUnknownBlockType)arg2;
- (void)sendHisenseKeycode:(id)arg1;
- (void)sendProtocolKey:(int)arg1;
- (id)urlencode:(id)arg1;
- (void)willWorkWithDevice:(id)arg1 WithSuccessBlock:(CDUnknownBlockType)arg2;
- (_Bool)willWorkWithKey:(int)arg1;

@end

