//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseViewController.h"

@class UIButton, UILabel;

@interface WKWifiConnectViewController : BaseViewController
{
    UILabel *_helpLabel;
    UIButton *_goNextButton;
    UIButton *_wifiButton;
}

- (void).cxx_destruct;
- (void)dealloc;
@property(nonatomic) __weak UIButton *goNextButton; // @synthesize goNextButton=_goNextButton;
- (void)goNextButtonClicked:(id)arg1;
- (void)gotoHelpCenter:(id)arg1;
@property(nonatomic) __weak UILabel *helpLabel; // @synthesize helpLabel=_helpLabel;
@property(nonatomic) __weak UIButton *wifiButton; // @synthesize wifiButton=_wifiButton;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)wifiButtonAction:(id)arg1;

@end

