//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "GCDAsyncSocketDelegate.h"

@class GCDAsyncSocket, NSMutableData, NSTimer, WKDeviceItem, WKNewALiDataTrans;

@interface WKYunOsDataTrans : NSObject <GCDAsyncSocketDelegate>
{
    WKDeviceItem *_device;
    CDUnknownBlockType _successBlock;
    CDUnknownBlockType _openAppBlock;
    CDUnknownBlockType _installAppBlock;
    struct {
        unsigned int key;
        unsigned int mkey;
        unsigned int packetID;
        unsigned int i;
    } _heartBeatMsg;
    int _msgKey;
    int _heartCount;
    _Bool _isReadPic;
    int _mid;
    NSTimer *heartBeatTimer;
    GCDAsyncSocket *_socket;
    WKNewALiDataTrans *_aliNewDataTrans;
    NSMutableData *_imagData;
    long long _randomInt;
}

- (void).cxx_destruct;
@property(retain, nonatomic) WKNewALiDataTrans *aliNewDataTrans; // @synthesize aliNewDataTrans=_aliNewDataTrans;
- (id)convertDataToHexStr:(id)arg1;
- (id)createCodeBuffer:(int)arg1;
- (void)disposeInstallAppResult:(id)arg1;
- (void)disposeOpenAppResult:(id)arg1;
- (void)getAppStoreMidFromData:(id)arg1;
@property(retain, nonatomic) NSTimer *heartBeatTimer; // @synthesize heartBeatTimer;
@property(retain, nonatomic) NSMutableData *imagData; // @synthesize imagData=_imagData;
- (id)init;
- (_Bool)isConnected;
@property(nonatomic) _Bool isReadPic; // @synthesize isReadPic=_isReadPic;
- (_Bool)isSupportScreenShot;
- (void)launchAppStoreBuffer;
@property int mid; // @synthesize mid=_mid;
@property(nonatomic) long long randomInt; // @synthesize randomInt=_randomInt;
- (void)releaseResources;
- (void)sendHeartBeat;
- (void)sendKeyCode:(int)arg1;
- (void)sendLoginReq;
- (void)sendMouseClick;
- (void)sendMsg:(id)arg1;
- (void)sendOpenAppBuffer:(id)arg1 withResultBlock:(CDUnknownBlockType)arg2;
- (void)sendPointerMoveWithX:(float)arg1 withY:(float)arg2 withMill:(int)arg3;
- (void)sendScreenShot;
- (void)setInstallResultCallBack:(CDUnknownBlockType)arg1;
- (void)setKey:(int)arg1;
@property(retain, nonatomic) GCDAsyncSocket *socket; // @synthesize socket=_socket;
- (_Bool)shouldScaleMouseCoordinate;
- (void)socket:(id)arg1 didConnectToHost:(id)arg2 port:(unsigned short)arg3;
- (void)socket:(id)arg1 didReadData:(id)arg2 withTag:(long long)arg3;
- (void)socketDidDisconnect:(id)arg1 withError:(id)arg2;
- (void)synAppStoreModelBuffer;
- (void)willWork:(id)arg1 withResultBlock:(CDUnknownBlockType)arg2;

@end

