//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSString, Target;

@interface XmPushActionRegistration : NSObject <NSCoding>
{
    NSString *__debug;
    Target *__target;
    NSString *__id;
    NSString *__appId;
    NSString *__appVersion;
    NSString *__packageName;
    NSString *__token;
    NSString *__deviceId;
    NSString *__aliasName;
    NSString *__sdkVersion;
    _Bool __debug_isset;
    _Bool __target_isset;
    _Bool __id_isset;
    _Bool __appId_isset;
    _Bool __appVersion_isset;
    _Bool __packageName_isset;
    _Bool __token_isset;
    _Bool __deviceId_isset;
    _Bool __aliasName_isset;
    _Bool __sdkVersion_isset;
}

@property(retain, nonatomic, getter=aliasName, setter=setAliasName:) NSString *aliasName;
- (_Bool)aliasNameIsSet;
@property(retain, nonatomic, getter=appId, setter=setAppId:) NSString *appId;
- (_Bool)appIdIsSet;
@property(retain, nonatomic, getter=appVersion, setter=setAppVersion:) NSString *appVersion;
- (_Bool)appVersionIsSet;
- (void)dealloc;
@property(retain, nonatomic, getter=debug, setter=setDebug:) NSString *debug;
- (_Bool)debugIsSet;
- (id)description;
@property(retain, nonatomic, getter=deviceId, setter=setDeviceId:) NSString *deviceId;
- (_Bool)deviceIdIsSet;
- (void)encodeWithCoder:(id)arg1;
@property(retain, nonatomic, getter=id, setter=setId:) NSString *id;
- (_Bool)idIsSet;
- (id)initWithCoder:(id)arg1;
- (id)initWithDebug:(id)arg1 target:(id)arg2 id:(id)arg3 appId:(id)arg4 appVersion:(id)arg5 packageName:(id)arg6 token:(id)arg7 deviceId:(id)arg8 aliasName:(id)arg9 sdkVersion:(id)arg10;
@property(retain, nonatomic, getter=packageName, setter=setPackageName:) NSString *packageName;
- (_Bool)packageNameIsSet;
- (void)read:(id)arg1;
@property(retain, nonatomic, getter=sdkVersion, setter=setSdkVersion:) NSString *sdkVersion;
- (_Bool)sdkVersionIsSet;
@property(retain, nonatomic, getter=target, setter=setTarget:) Target *target;
@property(retain, nonatomic, getter=token, setter=setToken:) NSString *token;
- (_Bool)targetIsSet;
- (_Bool)tokenIsSet;
- (void)unsetAliasName;
- (void)unsetAppId;
- (void)unsetAppVersion;
- (void)unsetDebug;
- (void)unsetDeviceId;
- (void)unsetId;
- (void)unsetPackageName;
- (void)unsetSdkVersion;
- (void)unsetTarget;
- (void)unsetToken;
- (void)write:(id)arg1;

@end

