//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSDictionary, NSString, Target;

@interface XmPushActionNotification : NSObject <NSCoding>
{
    NSString *__debug;
    Target *__target;
    NSString *__id;
    NSString *__appId;
    NSString *__type;
    _Bool __requireAck;
    NSString *__payload;
    NSDictionary *__extra;
    NSString *__packageName;
    NSString *__category;
    _Bool __debug_isset;
    _Bool __target_isset;
    _Bool __id_isset;
    _Bool __appId_isset;
    _Bool __type_isset;
    _Bool __requireAck_isset;
    _Bool __payload_isset;
    _Bool __extra_isset;
    _Bool __packageName_isset;
    _Bool __category_isset;
}

@property(retain, nonatomic, getter=appId, setter=setAppId:) NSString *appId;
- (_Bool)appIdIsSet;
@property(retain, nonatomic, getter=category, setter=setCategory:) NSString *category;
- (_Bool)categoryIsSet;
- (void)dealloc;
@property(retain, nonatomic, getter=debug, setter=setDebug:) NSString *debug;
- (_Bool)debugIsSet;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
@property(retain, nonatomic, getter=extra, setter=setExtra:) NSDictionary *extra;
- (_Bool)extraIsSet;
@property(retain, nonatomic, getter=id, setter=setId:) NSString *id;
- (_Bool)idIsSet;
- (id)initWithCoder:(id)arg1;
- (id)initWithDebug:(id)arg1 target:(id)arg2 id:(id)arg3 appId:(id)arg4 type:(id)arg5 requireAck:(_Bool)arg6 payload:(id)arg7 extra:(id)arg8 packageName:(id)arg9 category:(id)arg10;
@property(retain, nonatomic, getter=packageName, setter=setPackageName:) NSString *packageName;
- (_Bool)packageNameIsSet;
@property(retain, nonatomic, getter=payload, setter=setPayload:) NSString *payload;
- (_Bool)payloadIsSet;
- (void)read:(id)arg1;
@property(nonatomic, getter=requireAck, setter=setRequireAck:) _Bool requireAck;
- (_Bool)requireAckIsSet;
@property(retain, nonatomic, getter=target, setter=setTarget:) Target *target;
@property(retain, nonatomic, getter=type, setter=setType:) NSString *type;
- (_Bool)targetIsSet;
- (_Bool)typeIsSet;
- (void)unsetAppId;
- (void)unsetCategory;
- (void)unsetDebug;
- (void)unsetExtra;
- (void)unsetId;
- (void)unsetPackageName;
- (void)unsetPayload;
- (void)unsetRequireAck;
- (void)unsetTarget;
- (void)unsetType;
- (void)write:(id)arg1;

@end

