//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSData, NSString, PushMetaInfo, Target;

@interface XmPushActionContainer : NSObject <NSCoding>
{
    int __action;
    _Bool __encryptAction;
    _Bool __isRequest;
    NSData *__pushAction;
    NSString *__appid;
    NSString *__packageName;
    Target *__target;
    PushMetaInfo *__metaInfo;
    _Bool __action_isset;
    _Bool __encryptAction_isset;
    _Bool __isRequest_isset;
    _Bool __pushAction_isset;
    _Bool __appid_isset;
    _Bool __packageName_isset;
    _Bool __target_isset;
    _Bool __metaInfo_isset;
}

@property(nonatomic, getter=action, setter=setAction:) int action;
- (_Bool)actionIsSet;
@property(retain, nonatomic, getter=appid, setter=setAppid:) NSString *appid;
- (_Bool)appidIsSet;
- (void)dealloc;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
@property(nonatomic, getter=encryptAction, setter=setEncryptAction:) _Bool encryptAction;
- (_Bool)encryptActionIsSet;
- (id)initWithAction:(int)arg1 encryptAction:(_Bool)arg2 isRequest:(_Bool)arg3 pushAction:(id)arg4 appid:(id)arg5 packageName:(id)arg6 target:(id)arg7 metaInfo:(id)arg8;
- (id)initWithCoder:(id)arg1;
@property(nonatomic, getter=isRequest, setter=setIsRequest:) _Bool isRequest;
- (_Bool)isRequestIsSet;
@property(retain, nonatomic, getter=metaInfo, setter=setMetaInfo:) PushMetaInfo *metaInfo;
- (_Bool)metaInfoIsSet;
@property(retain, nonatomic, getter=packageName, setter=setPackageName:) NSString *packageName;
- (_Bool)packageNameIsSet;
@property(retain, nonatomic, getter=pushAction, setter=setPushAction:) NSData *pushAction;
- (_Bool)pushActionIsSet;
- (void)read:(id)arg1;
@property(retain, nonatomic, getter=target, setter=setTarget:) Target *target;
- (_Bool)targetIsSet;
- (void)unsetAction;
- (void)unsetAppid;
- (void)unsetEncryptAction;
- (void)unsetIsRequest;
- (void)unsetMetaInfo;
- (void)unsetPackageName;
- (void)unsetPushAction;
- (void)unsetTarget;
- (void)write:(id)arg1;

@end

