//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface YWLightUMUtil : NSObject
{
}

+ (id)JSONFragment:(id)arg1;
+ (id)JSONValue:(id)arg1;
+ (id)URLQueryParameters:(id)arg1;
+ (id)accessString;
+ (id)appDisplayNameString;
+ (id)appPackageNameString;
+ (id)appShortVersionString;
+ (id)appVersionString;
+ (id)carrierString;
+ (id)countryString;
+ (id)dateString;
+ (id)deviceMacAddressString;
+ (id)deviceModelString;
+ (id)getAsQueryParams:(id)arg1;
+ (_Bool)isJailBreak;
+ (_Bool)isPad;
+ (id)languageString;
+ (id)md5Value:(id)arg1;
+ (id)orientationString;
+ (id)osString;
+ (id)osVersionString;
+ (id)resolutionString;
+ (id)returnCheck:(id)arg1;
+ (id)sdkTypeString;
+ (id)sdkVersionString;
+ (id)timeString;
+ (id)timezoneString;
+ (id)umStringDecode:(id)arg1;
+ (id)umStringEncode:(id)arg1;
+ (id)urlDecode:(id)arg1;
+ (id)urlEncode:(id)arg1;
+ (id)uuidString;
- (id)JSONRepresentation:(id)arg1;

@end

